### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by txau** [huridocs/UwaziDocs#3]
This is a test issue

[HowToImproviseJazz.pdf](https://github.com/huridocs/UwaziDocs/files/270165/HowToImproviseJazz.pdf)

**Comment by danicatalan** [comment]
I think this could work:
![louis_armstrong_restored_o_1250](https://cloud.githubusercontent.com/assets/6364153/15355135/59bfe0c4-1cf1-11e6-929a-e077b5607ab3.jpg)
