### ISSUE TITLE
Zoom controls position

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4398]
Both in library and entity view, the position of the zoom controls overlaps the provider logo:

![image](https://user-images.githubusercontent.com/489831/158282614-b4420afa-bad2-4448-9de7-47961495a83a.png)

making it easy to accidentally click on the logo instead of the "minus" button. Also the left bottom emplacement seems a little bit counter intuitive. On other mapping apps it is located on the top left or the bottom left.

**Comment by mfacar** [comment]
@txau I interchanged the buttons. The zoom buttons were moved to the bottom right and layers control to the bottom left of the map.

**Comment by txau** [comment]
> 

Ok, just make sure that there is no overlapping between the logo of the provider and the layer selection controls. BTW, I think they can both be placed on the bottom right. Just like this:

![image](https://user-images.githubusercontent.com/489831/158382135-0d819c88-4892-4305-8bdd-bbebb8f56f4e.png)

or this:

![image](https://user-images.githubusercontent.com/489831/158382260-7eddf023-4d42-4f25-918d-4e02037e20d1.png)

**Comment by mfacar** [comment]
I left the last proposal, I put the layers button on zoom buttons because it changes at mouseover.

<img width="69" alt="Screen Shot 2022-03-15 at 10 44 35" src="https://user-images.githubusercontent.com/5322716/158416448-c6ec0dbe-5701-44df-9da1-6748e5db9f61.png">
