### ISSUE TITLE
Bypass captcha key

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#4413]
Allow sending entities to public endpoint without passing a captcha challenge by setting a header/param on the request. Accepting this types of requests has to be enabled from the collection settings.

**Comment by Zasa-san** [comment]
This is the proposed UI implementation:
![screen](https://user-images.githubusercontent.com/71732018/158826740-5d54b7cd-9da2-480d-a934-7d5cb67a00a4.jpg)

This is going to requiere a tooltip text for users:
`By toggling this on you can allow users to submit to your whitelisted templates without having to fill a CAPTCHA.`
I think this tip should say something about the implications of doing this. Any suggestions on how to phrase it?

@txau @juanmnl

**Comment by txau** [comment]
@Zasa-san to avoid the ugly two-liner can we just call the option "Allow captcha bypass"?

If I recall correctly we agreed this will not disable the captcha for the forms, but only if a special header is sent to the end-point. This could be explained in the tool tip:

> The form will still present the captcha to end users, but API end-point will allow submissions without CAPTCHA validation if a header "bypass-captcha: true" is sent along. This option is insecure and can be leveraged to flood your instance with spam or malicious content.
