### ISSUE TITLE
Sync does not take into account inherited properties.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#4420]
The scenario is as follows:
- Property A inherits Property B
- Property A is synced but Property B is not
- Target instance throws a bunch of errors when trying to process Property A since B does not exist in this DB.

**Comment by elreplicante** [comment]
After opening a synced entity containing Property A on the child instance, we get a blank UI and some errors on the browser console as it is trying to get a property that does not exist.

<img width="1347" alt="Screenshot 2022-04-05 at 11 26 32" src="https://user-images.githubusercontent.com/1397196/161723615-aab91901-af18-4dff-a783-4ea73c576946.png">
