### ISSUE TITLE
IX: change of wording for the add properties dialog

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4426]
![image](https://user-images.githubusercontent.com/489831/159154783-8e71f177-9e8f-4b2e-b85c-e48e7b64c7b8.png)

"Add supported properties*" => "Add properties*"

"*Only supported properties are shown" => "*Only text, number and date properties are currently supported.".

**Comment by juanmnl** [comment]
<img width="794" alt="Screen Shot 2022-03-21 at 17 28 41" src="https://user-images.githubusercontent.com/699945/159373703-87e1498b-a951-457e-886c-63839a3e2c10.png">
