### ISSUE TITLE
IX: add type icons to properties

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4427]
Display our standard property type icon besides the property name.

![image](https://user-images.githubusercontent.com/489831/159154959-17c9178f-6289-400b-93f1-40f6491cd8ed.png)

![image](https://user-images.githubusercontent.com/489831/159154973-52479390-c180-43ca-8e60-f59eb5347bba.png)

**Comment by juanmnl** [comment]
This was already contemplated on the designs.

<img width="794" alt="Screen Shot 2022-03-21 at 17 28 41" src="https://user-images.githubusercontent.com/699945/159373647-59156635-7d36-40d6-a8a5-2548b928d91e.png">
