### ISSUE TITLE
IX: blank state for suggestions (8 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4428]
Suggestions' blank state should be a list of documents instead of a blank page. So even without pressing the "Find suggestions" button, the user already has the document title, language, current value and a state. This blank state allows users to label the first samples before training.

A possible solution is to make sure we inject a "placeholder" suggestion when there are no suggestions for that particular file+property. The state for this placeholder could be "Pending".

Also, the button to display the PDF on the side panel is not rendered when there is no "segment" coming from the model, we need to make sure this button is present and clickable when there is no suggestion.

**Comment by txau** [comment]
Moreover, right after configuring the property, if the suggestions collection is empty in the DB, it will throw and error:
```
url: /api/suggestions?page=%7B%22number%22%3A1%2C%22size%22%3A100%7D&filter=%7B%22propertyName%22%3A%22title%22%7D
query: {
 "page": {
  "number": 1,
  "size": 100
 },
 "filter": {
  "propertyName": "title"
 }
}
TypeError: Cannot read property 'creationDate' of undefined
    at Object.get (/home/txau/work/uwazi/prod/app/api/suggestions/suggestions.js:161:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /home/txau/work/uwazi/prod/app/api/suggestions/routes.js:60:29
    at async /home/txau/work/uwazi/prod/app/api/utils/routesErrorHandler.js:6:5
original error: {}
```

This should be properly handled showing a blank state message: `Suggestions hasn't been create yet, this operation may take some minutes`

**Comment by LaszloKecskes** [comment]
Closing after merging to the feature branch.
