### ISSUE TITLE
IX: display training process (8 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4430]
Currently, when training the model and retrieving the new suggestions, the user goes from seeing a "Training..." message in the button to nothing (needing to refresh the page to get new suggestions).

@gabriel-piles confirmed that the model will send a flag via Redis when it is done training. So ideally we have these steps displayed as UI feedback for the user:
1. "Sending labeled data..." (Optional, if possible)
2. (Optional) "Waiting in queue..." (because the service will train one model at a time, it can happen that after sending the materials we have to wait until the service is free. If we have a flag for this we should use it, if not skip this for now)
3. "Training model..." (Ideally we have estimates based on the volume of data or previous trainings, but this can wait for another iteration).
4. "Retrieving suggestions XX/YYY" (because we know the version of the suggestion based on the model timestamp, so we can create this progress).
5. When finished, go back to "Find suggestions" button state

While the training process goes on, suggestions need to be displayed in the "obsolete" state as described here: https://github.com/huridocs/uwazi/issues/4431

Also, currently while the model is training users are allowed to click on the "Training..." button which relaunches the training process. It is unclear if this cancels the previous training our queues a new training. We should disambiguate this situation by making a explicit "Stop training".

**Comment by txau** [comment]
https://www.figma.com/file/VbnNs1Iy8qbOet3oLwMgfe/Information-Extraction?node-id=250%3A126

**Comment by RafaPolit** [comment]
Comments from the team:
- currently there is no "stop training" option, team is unsure if there is even such a method built into the service
- there are no designs for the XX/YYY label cc @juanmnl

**Comment by gabriel-piles** [comment]
> Comments from the team:
> 
> * currently there is no "stop training" option, team is unsure if there is even such a method built into the service
> * there are no designs for the XX/YYY label cc @juanmnl

The service can't cancel tasks... right now.

**Comment by txau** [comment]
> The service can't cancel tasks... right now.

Then we should make sure that the "Find suggestions" button is disabled when the model is being trained.
