### ISSUE TITLE
IX: suggestion states (13 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4431]
Replace the current states with the described bellow and add a tool-tip on mouse-over on each label displaying the description. Allow filtering by these states.

Suggestions can have the following states:
- **label match** -> It has a current value and a text selection matching with the model suggested value and selection. It will be used as a training sample.
- **label mismatch** -> It has a current value and text selection but they do not match the model prediction. Accepting the suggestion will replace the current value and text selection with the suggested ones becoming a "labeled match". If the labeled data is correct and the suggestion is wrong no action is needed. It will be used as a training sample.
- **label empty*** -> Accepting is not available. If the value is correct and the suggestion is wrong no action is needed. It will be used as a training sample.
- **value match** -> It has a current value that matches the suggested one, but it doesn't have a text selection. Accepting will keep the value as it is and enrich it with the suggested text selection becoming a "label match" that can be used as a training sample.
- **value mismatch** -> Accepting the suggestion will replace the current value and text selection with the suggested ones becoming a "label match" that will be used as a training sample. If the value is correct you can still click to fill the text selection so it becomes a "label mismatch" that will be used as a training sample.
- **value empty*** -> Accepting is not available. If the value is correct you can click to fill the text selection so it becomes a "label empty" that will be used as a training sample.
- **empty** -> Both the current value and the suggestion are empty. You can click to fill the value and text selection so it becomes a "label empty" that will be used as a training sample.
- **obsolete** -> A new model is training and processing suggestions and this suggestion was created by a previous model. No actions are possible.

note: we are currently labeling the **empty** state as match because both values match. This is wrong. If both values are empty the state needs to be **empty**.

For the record, there is an extra state considered rare that we don't want to track for now:
- labeled empty + match empty -> there is a text selection and the correct value is empty, the model is also correctly returning an empty value. This can happen if the expected result is and empty string.

**Comment by juanmnl** [comment]
New arrow button styles and states.

![button styles](https://user-images.githubusercontent.com/699945/162509914-663b293a-64e2-4f73-81b9-c332479f677f.png)

![button states](https://user-images.githubusercontent.com/699945/162511720-2c65b67e-8989-44ba-9b3d-30b52d70a7f1.png)

**Comment by txau** [comment]
Some changes over the initial proposal:
- We are going to switch the order of the states from current value / suggestion to suggestion / current value so they match with the current flow of the table.
- We are going to add a slash between them for better readability.
- The state "empty" becomes "empty / empty" so it follows the same pattern as the rest.
- There is a new state "mismatch / empty".
- Descriptions updated accordingly, use the new ones please.

The list now looks like:
- match / label ->  It has a current value and a text selection matching with the model suggested value and selection. It will be used as a training sample.
- mismatch / label -> It has a current value and text selection but they do not match the model prediction. Accepting the suggestion will replace the current value and text selection with the suggested ones becoming a "match / labeled". If the labeled data is correct and the suggestion is wrong no action is needed. It will be used as a training sample.
- empty / label -> Accepting is not available since there is no suggestion. If the value is correct and the suggestion is wrong no action is needed. It will be used as a training sample.
- match / value -> It has a current value that matches the suggestion, but it doesn't have a text selection. Accepting will keep the value as it is and enrich it with the suggested text selection becoming a "match / label" that can be used as a training sample.
- mismatch / value -> Accepting the suggestion will replace the current value and text selection with the suggested ones becoming a "match / label" that will be used as a training sample. If the current value is correct, you can still click to fill the text selection so it becomes a "mismatch / label" that will be used as a training sample.
- **mismatch / empty** -> There is no current value and the model is suggesting a value. Accepting the suggestion will replace the current (empty) value and text selection with the suggested ones becoming a "match / label" that will be used as a training sample. Alternatively you can ignore the suggestion and click to fill the text selection so it becomes a "mismatch / label" that will be used as a training sample.
- empty / value -> Accepting is not available since there is no suggestion. If the current value is correct, you can click to fill the text selection so it becomes a "empty / label" that will be used as a training sample.
- empty / empty -> Both the current value and the suggestion are empty. You can click to fill the value and text selection so it becomes a "empty / label" that will be used as a training sample.
- obsolete -> A new model is training and processing suggestions. This suggestion was created by a previous model so no actions are possible until the new suggestion is received.

There is a correspondence between these states and the possible actions/colors suggested by @juanmnl :
- green: "match / label"
- yellow: "mismatch / label", "mismatch / value"
- blue: "match / value", "mismatch / empty"
- grey: "empty / label", "empty / value", "empty / empty", "obsolete"

**Comment by txau** [comment]
@konzz @grafitto there another possible state when the model sends an error. It would be great to add the state as "Error" and the message as the suggestion text.
