### ISSUE TITLE
IX: click to fill is not evident

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4435]
In this image the possibility of clicking in the context to open the PDF and fill the data is obfuscated. We need a better UI solution way more explicit than this.

![image](https://user-images.githubusercontent.com/489831/159193989-e6679160-e44f-4e49-a805-b6cbef95ab79.png)

More over, when the segment is blank the link disappears and you can access the click to fill functionality.

**Comment by juanmnl** [comment]
We could go with a more present button (PDF -> Open PDF) and underlining the whole text block on hover, making the whole cell "clickable". Or go with a column (actions) that contains the "Open PDF" button.

![2022-03-21 17 19 59](https://user-images.githubusercontent.com/699945/159372880-61fbafde-26c3-47e7-b5e9-b01cf7d38d01.gif)

**Comment by txau** [comment]
@juanmnl thanks, that works!
