### ISSUE TITLE
IX: avoid losing context after update (5 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4438]
If a user is filtering the list and "clicks to fill" or "accepts" a suggestion, the state of the suggestion will change and the table gets refreshed. The UX problem is that upon refresh, the suggestion disappears from sight, so the user is not receiving a visual cue of the changes being committed.

IMO we should keep the just modified entity in the exact same position it was to avoid this lose of context.

After that, in order to eventually achieve a clean state, we should wait for a user action (refresh, navigate, paginate or use the filters).

**Comment by juanmnl** [comment]
Agree that we should wait for user action to apply the changes, yet we can still show the previous and current states in the same status cell. (so the user understands that the change has been applied, but we just don't do anything with that row –visually–)

<img width="653" alt="Screen Shot 2022-03-22 at 09 27 40" src="https://user-images.githubusercontent.com/699945/159507119-f678df66-f3c4-4e49-a3b1-29e0d6c58e5c.png">

@txau What do you think?

**Comment by txau** [comment]
@juanmnl I'm ok with the proposed solution but we also need to make sure that the table doesn't jump around or changes the sizes and positions of the information.

**Comment by mfacar** [comment]
depends on #4431
