### ISSUE TITLE
CSV path for attachments is exporting an obsolete path

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4449]
We are exporting attachments' path as:

/api/attachments/download?_id=something

But we have modified this endpoint and now it is server as

/api/files/something

**Comment by RafaPolit** [comment]
We have this "burned" into the code in several different places. We need to make this a variable to avoid further problems with this paths.

**Comment by RafaPolit** [comment]
Include the DOMAIN in the URL as well.
