### ISSUE TITLE
Improved sorting component (8 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4459]
- Extend the component so it supports the direction (ASC, DESC) of the sort as a separate control
- Simplify the options inside the list so they do not need to be duplicated per direction (ie. Title A-Z, Title Z-A)
- Make sure the component can handle lots of sorting options (#3584)
- Resolve how sorting criteria should be display in cards. Right now, the sorted property is force to appear in cards and has a light blue background (#1938)
- Resolve how sorting criteria is displayed in table view (#3217 )

**Comment by juanmnl** [comment]
- The sorting dropdown should be as big as the biggest string it contains
- Toggling button for ascending vs descending

https://www.figma.com/file/Wr0zUf6gS7UscjvOM56oUm/Current?node-id=518%3A3185

<img width="1294" alt="Screen Shot 2022-04-19 at 08 30 46" src="https://user-images.githubusercontent.com/699945/164015215-ff5d26b3-0955-404d-9b1a-c93cb476c91d.png">

<img width="181" alt="toggle" src="https://user-images.githubusercontent.com/699945/164042565-03e0a952-caac-47e2-ad32-6f3cdb13b820.png">

**Comment by txau** [comment]
The biggest sorting option can be very big, I think it needs to wrap or hide part of the content.

**Comment by juanmnl** [comment]
@txau we should define max-char limit and then add an ellipsis (...) Any suggestion? (~40 chars?)

**Comment by konzz** [comment]
The estimation is for the first 3 points.

**Comment by txau** [comment]
> @txau we should define max-char limit and then add an ellipsis (...) Any suggestion? (~40 chars?)

whatever you think is a good length @juanmnl . Just pointing out that some options could be 200 chars.
