### ISSUE TITLE
Pages map default CSS

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#4461]
After the migration to Leaflet (#4339) the maps rendered in pages don't show up unless you give the container some width and height. Previously we had some default styles for the map so the users creating pages can see the map and style it accordingly.

@juanmnl What would be a good default? something like this:
```
.page-viewer .map-container {
    width: 300px;
    height: 300px;
}
```
<img width="1440" alt="Screenshot 2022-03-25 at 15 45 23" src="https://user-images.githubusercontent.com/948117/160143507-a7a9f2e7-38a3-459b-a28f-a0d3f26f3cc6.png">

**Comment by juanmnl** [comment]
I understand this, it has happened to me before. This shape looks good for the side-panel but not sure it works for the main one. Can we try to get the content container width before the render? and then apply a 2:1 ratio to the map-container?

**Comment by RafaPolit** [comment]
Our pages have a fixed with container of 960px I think, so yeah, we can give it a 2:1 ratio.

**Comment by RafaPolit** [comment]
I cannot seem to reproduce this error.

Using the `<EntityData value-of="property_geolocation" />` component, our system wraps the map in a `<div>` and assigns it the class `map-container` which has the correct values of `width: 100%; height: 370px` assigned to it.

Maybe in the above scenario it was included inside a floating or absolute component that had no intrinsic width?  If so, the solution is to assign a width to the parent document containing the map.

As long as the map is child to an element with a given width (or a div which naturally uses 100% of the available space), this should render correctly.

I'm closing this for now, if this error is reported again, please include the page code that generated the error.

**Comment by meegido** [comment]
Hi @RafaPolit! 

You can try to reproduce it adding the Map component. Is the way I've always seen it and worked with maps in the pages. 

The way to reproduce is adding: `<Dataset geolocation="true" />` and `<Map />` to show it. 

With the `<Map />` component, you get a `<div class="Map">` and the div with the class `map-container` inside of it. The Map class has not any style (with and height px) assigned so this is the problem. The `map-container` class has the percentages as you mention (but is not the container). 

```
.map-container {
    height: 100%;
    width: 100%;
    z-index: 1;
}
``` 

**Update:** I've just discovered that if you add `aspect-ratio` (as Juanma said) and `width: 100%` to the `map-container` class, you will show the map without adding styles to the `Map` class :) 

This aspect ratio works for full width map: 
```
.map-container {
  aspect-ratio: 4 / 4;
  width: 100%;
}
``` 

I hope it helps :)
