### ISSUE TITLE
Changing a template name makes it not translatable.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#4462]
To replicate:
 * Update template with a new name
 * Navigate to library and activate inline translation
 * The new name is the only one that does not get highlighted
 * Navigate to setting -> translations for that template
 * The old name is in the list of translations but not the new one

Updating the name again to the old one "fixes" the problem but this makes changing template names basically not an option if you have multiple languages.

Probably a migration is required.

**Comment by mennaelmassry** [comment]
Hello, 

I have the same issue with another instance. 

I tried to do live translations of the name of two out of three templates, and it did not give me the option to do live translations.

I also tried to translate the title through settings ---> translations and I found 2 things:
1) the name of the template under translations was the old name not the update one
2) after translating it, it did not show as translated in the library

I reported the issue on Gitlab as well

CCing @MatelSow
