### ISSUE TITLE
Untranslatable system UI terms

### ISSUE THREAD

**Issue by hyebin-bina** [huridocs/uwazidocs#4467]
Hello,

The program team documented the system UI terms that are not translatable and thus need support from the development team. 
There are three types of terms that are not translatable as below. 

1) Terms that do not exist on the translations list under Settings > Translations > User Interface:

- Show in cards
- Collection name
- Custom favicon
- Use custom landing page
- Google Analytics
- Matomo Analytics
- Contact Form
- Receiving email
- Sending email
- Public Endpoints
- Custom starting location
- Create user
- No label
- admin
- collaborator
- viewer
- - select "Create group" below to group filters under a label e.g ("Documents " or "People")

2) Terms do not exist on the translations list and that are Property Types of Templates:

- Rich Text
- Link
- Image
- Preview
- Media
- Geolocation
- Generated ID

3) Terms that exist on the Translations list but cannot import through CSV import:

- OCR button tip:  This will process the document to recognize it's text. The original file will be added as a supporting file.
- OCR description tip 1: This will enable the Optical Character Recognition (OCR) functionality for PDF documents. This service will recognize text inside images, such as scanned documents and photos, and convert it into machine-readable text data.
- OCR description tip 2 :  When activated, this will enable administrator and editor users to send PDF documents to the OCR service.
- OCR error tip: The OCR engine couldn't read the document due to a malformed format. Last updated
- If you want to track analytics related to your collection visits, Uwazi supports both Google Analytics and Matomo.
- Here you can configure the public form destination and the whitelisted templates
- You can configure the URL of a different Uwazi to receive the submits from your Public Form
- If you wish to include a public form on your page, you must white-list the template by selecting it from the list.
- This language will be used as default translation when adding new languages, and the default language for the site when no other language has been selected.
- By default, users can filter the entities in the library based on the types you have defined. However, you can configure how these entity types will be displayed:
- - Filters
- FEATURED
- ALL
- Add user
- Cards view
- Create entity
- Discard Changes

**Comment by Zasa-san** [comment]
I've tried some of the point 3 translations and have been able to translate via CSV import. I've only tried a few, but point 3 could be due to an error on the CSV. I've attached the example CSV I used for reference.
[translation-test.csv](https://github.com/huridocs/uwazi/files/8952617/translation-test.csv)

**Comment by Zasa-san** [comment]
About number 2, template property type selectors are not translatable at all.
I've made them translatable and added them to the UI term list as `Property type [type]`

**Comment by hyebin-bina** [comment]
Thank you very much for your work, Santi! 

Point 3: Thank you for testing! I can see that the error was due to having different key and string. 
Point 2: I cannot find the UI term list named "Property Type" either on a normal instance or a staging instance, could you kindly let me know where we can find the list?

**Comment by llfinch** [comment]
Hi @hyebin-bina! I believe what Santi means (@Zasa-san please fact check me!) is that he's developed the code which will fix the Point 2 issue of Property Types not being present in the Settings-->Translations-->User Interface list, but we're not going to be able to see it and test it till it's merged to a staging release with other development (the same that happens each week).

**Comment by Zasa-san** [comment]
@hyebin-bina Thanks @llfinch for clarifiying. After this is merged and deployed into staging you will be able to translate the template property types (ie Text, Numeric, Select, Date, Multiselect, etc...) by using live translate, CSV or Settings-->Translations-->User Interface
