### ISSUE TITLE
Add a code editor for the front end.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#4473]
Creating pages is slow, working in the pages text area or css is slow and does not work well. We want to add an editor to speed the development of pages.

Checkout [codemirror](https://codemirror.net/)

**Comment by txau** [comment]
Alternatively consider integration with GIT for version controlling pages.

**Comment by Zasa-san** [comment]
A code editor will be added in https://github.com/huridocs/uwazi/pull/6380

@konzz @txau should we close this issue and open a separate one for version controlling pages?

**Comment by konzz** [comment]
I would just close it.
