### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by AhmadQadi1** [huridocs/uwazidocs#4475]
We still have a technical issue with Captcha, it doesn't work on most of the forms, specificall smear campaigns, hate speech and fake news.
![Untitled](https://user-images.githubusercontent.com/95572565/160789965-f8c860aa-5c16-4adb-acee-67b46d74293e.png)

**Comment by MatelSow** [comment]
@AhmadQadi1 - we have not been able to replicate the issue neither on the Arabic no English UIs. Would you share the steps that you have taken which create the error? Perhaps a screen recording of the process.
Thanks

**Comment by MatelSow** [comment]
User identified the issue - spaces were used with the captcha which caused the submission error. Issue resolved.
