### ISSUE TITLE
Improve mobile side bar navigation

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4481]

**Comment by nwyu** [comment]
Relate to #1899

**Comment by RafaPolit** [comment]
- Icons are all scrambled
- the side panel has no labels for certain icons
- there is some reserved space at the top when few menu items are present, but then there is not enough space or scrolling when several menu items are present
- there is no "active" state on the menu

**Comment by juanmnl** [comment]
https://www.figma.com/file/Wr0zUf6gS7UscjvOM56oUm/Current?node-id=732%3A301
