### ISSUE TITLE
Language detection and list of available languages for documents

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4495]
Currently our language detector and selector has some arbitrariness:
- Despite [Franc](https://github.com/wooorm/franc) being able to detect hundreds of languages we only support a few
- The list of available languages has no evident particular order, alphabetical or whatever
- The list doesn't allow you to select a language even if it is added in settings > languages

![image](https://user-images.githubusercontent.com/489831/161675735-727777c4-9b4e-48a7-a81c-0af34452d4f6.png)

[edit]

Taking a closer look I realized that the order is based on the language code, which is not displayed anywhere. It wouldn't harm to sort them by the official name instead of the code:

```
arb: { franc: 'arb', elastic: 'arabic', ISO639_1: 'ar' },
  bul: { franc: 'bul', elastic: 'bulgarian', ISO639_1: 'bg' },
  cat: { franc: 'cat', elastic: 'catalan', ISO639_1: 'ca' },
  cjk: { franc: 'cjk', elastic: 'cjk', ISO639_1: null },
  ckb: { franc: 'ckb', elastic: 'sorani', ISO639_1: null },
  ces: { franc: 'ces', elastic: 'czech', ISO639_1: 'cs' },
  dan: { franc: 'dan', elastic: 'danish', ISO639_1: 'da' },
  deu: { franc: 'deu', elastic: 'german', ISO639_1: 'de' },
  ell: { franc: 'ell', elastic: 'greek', ISO639_1: 'el' },
  eng: { franc: 'eng', elastic: 'english', ISO639_1: 'en' },
  eus: { franc: 'eus', elastic: 'basque', ISO639_1: 'eu' },
  fas: { franc: 'fas', elastic: 'persian', ISO639_1: 'fa' },
  fin: { franc: 'fin', elastic: 'finnish', ISO639_1: 'fi' },
  ```

**Comment by txau** [comment]
Also consider using the searchable select component that we already use for selecting icon/flag.

**Comment by llfinch** [comment]
Hi @txau! I realize this issue is closed, but since it's related I wanted to ask before opening an issue (since the complexities of this feature are a bit beyond me): Is it a technical limitation that the language detection labels aren't translatable, or is this something we could theoretically do, adding them to the `Settings-->Translations-->User Interface` list?

**Comment by txau** [comment]
@llfinch I'm not sure at the moment. I think @RafaPolit can answer that question better. My hunch is that we could make them translatable.
