### ISSUE TITLE
Create a list of key areas of Uwazi.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#4498]
List down the key features of Uwazi so we keep them in mind while making decisions.

**Comment by RafaPolit** [comment]
WIP:

## Key concepts

- Uwazi is a platform that needs to cater to different cultures, languages and be fully accessible.  Localization and accessibility should be top priority in any area we design
- Every page, section, status, filter, area, etc. should be reachable by URL without the need of further user interaction.  This is very important for speed of the app (SSR), and also for SEO.
- The app should be analyzable through different tools

## Key areas and functionality

- Main library with several display possibilities: cards, table view, map.  Ability to render dozens of cards, hundreds of rows and potentially thousands of map markers
- Search area and filtering by aggregation results, which requires ability to view, filter and lookup from amongst thousands of results in specific filters
- clear requirement to visualize the same data in different formats: as a card, as a row, as a side panel info, as a main central-screen entity, etc.
- At the core, Uwazi was born as a "PDF Viewer"-first collection of data.  While this is no longer it's only purpose, PDF rendering is still medullar to  Uwazi, including text selection and highlighting.  Ideally, potential for commenting, etc.
- Uwazi evolved into a relationship-based system where the relationships between entities are as or even more important than the entities themselves.  How to showcase those relationships and the amount they can grow into (several tens of thousands in particular cases) is critial
- Uwazi is also a data analysis tool: graphs and charts should be part of the core of Uwazi tools
- A lot of users depend heavily on Maps and Geolocation.  Uwazi needs to be able to be a Map viewer tool and consume data with geolocation essence.
- Uwazi has become a fully fledged CMS.  Ability to create custom global CSS overrides, custom pages with global and local overrides and local JS code, and per-template custom pages.... all with access to Graphs and pre-made components is indispensable to telling the story of the data.
- One of Uwazi's strengths is the incorporation of additional services on data: Information Extraction, OCR, etc.  This external services need to be integrated into Uwazi, but also allow for them to be off and have a seamless experience in both scenarios.
- Uwazi need to be strong visually: lots of media, images, video, sound, etc. support
- Uwazi is a collection of data heavily dependent on Admin configurations.  These need to be central to data management.
