### ISSUE TITLE
Inherited properties may produce problems on partially synced collections

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#4515]
An inherited property has all the info it needs to render it's own data.  Still, the actual source for the inherited data may NOT exist on the database / elastic index because the source is NOT synced.

When that happens, we need to treat the rendering of links and side panel openings a little different, because that relationship may point to an entity that doesn't exist on the child database.

**Comment by fnocetti** [comment]
Related to #4420

**Comment by txau** [comment]
Same as https://github.com/huridocs/uwazi/issues/4527
