### ISSUE TITLE
Custom uploads - Problems to read (2 pts)

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#4521]
The "Settings - Custom Uploads" screen has a problem to show the characters:

![image](https://user-images.githubusercontent.com/73410334/162820086-b9d79735-cad1-428a-9e5c-7e01602b787a.png)

The problem is similar, no matter if you zoom in or out the browser screen.

**Comment by nwyu** [comment]
Relates to #4022.

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/1784
