### ISSUE TITLE
Loss of image property from Prisoner template and thus corresponding images from the entities

### ISSUE THREAD

**Issue by pddocs** [huridocs/uwazidocs#4523]
The public[ instance](https://tppd.tchrd.org/) had an image property that was populated using the supporting file route. The partner has come back with a concern that: The images were no longer rendering on the entity cards view and found that the corresponding image property was not longer found in the template. They reconfigured it. All image files were however present in the supporting files section. 

What could explain this behaviour? The partner confirmed that no new users have logged in the database from their side, and the admins have not removed the property either. 

Will the partner need to add this this property and manually add the images files on the entity, or could we offer a backend support for this?

Total number of entities affected are ~ 100

**Comment by RafaPolit** [comment]
Is the missing property only missing on the public instance but present on the parent instance? Did someone change the PARENT instance in some way?

**Comment by pddocs** [comment]
There is only one instance. [It](https://tppd.tchrd.org/) is a public facing one. No properties were deleted by the admin on it.
