### ISSUE TITLE
Maps in Arabic interface show the wrong geolocations (3 pts)

### ISSUE THREAD

**Issue by mennaelmassry** [huridocs/uwazidocs#4524]
Hello, 

We have an issue with the maps.
In english they rendere the correct coordinates however when moving to the Arabic interface they give different locations as seen below.  

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/75305030/162919220-9a03db2f-ce16-43be-8149-52ac8cf2483f.png">

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/75305030/162919330-3ba11ad8-0a2a-4357-ad77-092271abcad2.png">

**Comment by RafaPolit** [comment]
I removed the mention to the specific instance and URL.  Info an pictures should be enough to replicate the issue.
