### ISSUE TITLE
PR #4417 broke relationship display of more than one value in metadata

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#4528]
Pull Request #4417 broke the rendering of Relationship links for properties that have more than one value.

Previously, relationships went through the `default` in `Metadata.js`.  This process took into account that values should be rendered with `<ValueList>` with interposed a comma between values when there is more than one.

This is no longer used and values with more than one relationship are rendered next to each other with no separation.  This should have been an easy catch if the dev and QA tests would have been done with more than one value.

cc @grafitto

**Comment by txau** [comment]
Already merged
