### ISSUE TITLE
Map controls render over modals

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4529]
![image](https://user-images.githubusercontent.com/489831/163051206-9fbc879d-331f-45a7-a931-fc42824c64f4.png)

**Comment by konzz** [comment]
<img width="362" alt="Screenshot 2022-07-06 at 11 16 48" src="https://user-images.githubusercontent.com/948117/177516133-83e723b4-7a7a-47cc-95f4-bc295fff17cc.png">
Checked library, pages, with different modals and does not seem to be happening any more, closing for now.

**Comment by txau** [comment]
On entity view, tested with firefox for linux

![image](https://user-images.githubusercontent.com/489831/177568783-7123e32f-99c5-4348-8649-9e8e08b988b4.png)

**Comment by konzz** [comment]
Ok, thanks, will se if its the entity pages, or a browser specific problem
