### ISSUE TITLE
Segmentation queue grows beyond 50 tasks

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4540]
The segmentation service is supposed to not send to queue more than 50 tasks at a time, then wait for the queue to clear up before sending 50 more. On a local run, it was piling up tasks up to 900+

**Comment by gabriel-piles** [comment]
I can't reproduce this issue, with the correct setup only 50 tasks at maximum are in mongodb with the status "processing". If the redis setup is not correct, Uwazi is not adding new tasks to mongodb.

**Comment by txau** [comment]
Ok. I'll try to reproduce and reopen if it persists.
