### ISSUE TITLE
Inconsistent tests in app/api/templates/specs/reindex.spec.js

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#4561]
The tests use the `checkIfReindex` and `templates.save` functions in a way that is inconsistent with the usage in the actual code.

The signature of `templates.save` is:
```
async save(template: TemplateSchema, language: string, reindex = true, templateStructureChanges = true) 
```

In `app/api/templates/routes.js`  it is used as:
```
const saveTemplate = async (template: TemplateSchema, language: string, fullReindex?: boolean) => {
  const templateStructureChanges = await checkIfReindex(template);
  return templates.save(
    template,
    language,
    !fullReindex && !template.synced,
    templateStructureChanges
  );
};
```

In the tests, through a helper function:
```
const getAndUpdateTemplate = async props => {
  const [template] = await templates.get({ _id: templateWithContents });
  Object.keys(props).forEach(key => {
    template[key] = props[key];
  });
  return { reindex: await checkIfReindex(template), template };
};
...
...
    it('should not reindex if name has changed', async () => {
      const { reindex, template } = await getAndUpdateTemplate({ name: 'Updated name' });

      expect(reindex).toEqual(false);

      await templates.save(template, 'en', reindex);
      expect(search.indexEntities).not.toHaveBeenCalled();
    });
...
...
```

That is, the output of `checkIfReindex` is put in 3th parameter instead of the 4th, and we are always using the default true for the 4th parameter.

**Comment by fnocetti** [comment]
Team comment: It may be worth it taking a look at the need for separate parameters, and check if they can be unified.

**Comment by LaszloKecskes** [comment]
> Team comment: It may be worth it taking a look at the need for separate parameters, and check if they can be unified.

After going through the code, it seems it is reasonable to keep this separate. They are different, based on source:
- the `reindex` parameter is the opposite of the fullreindex flag coming from the ui: i.e. if we are not forcing a full reindex on the route explicitly, we are reindexing just the template in question
- the `templateStructureChanges` flag shows the internal changes of the template

Second reason: `templateStructureChanges` is used for other things as well (updating translations, extracted metadata properties for info extraction, etc.) that do not care for the state of reindexing.

However, we could entirely remove tSC, and refactor the check to be part of the regular template update.
