### ISSUE TITLE
Problems if 2FA is reseted

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#4563]
Managing a user account with 2FA, it appears a mistake if:

1. Click "Reset 2FA" in user settings.
2. Delete the linked account in Google Authenticator.
3. Try to add again 2FA.
4. Appers a "The token does not validate against the secret key!" message, and 2FA is not added again.

![image](https://user-images.githubusercontent.com/73410334/165787100-de4b6192-fba8-4c61-9dbf-bec9c5037ba0.png)

**Comment by RafaPolit** [comment]
Cannot reproduce this.  Please, ensure that device with the authenticator has the correct timezone and time configured.

**Comment by salvalacruz** [comment]
Hi, the problem happens in different devices. In my own mobile timezone and time are properly configured.

**Comment by salvalacruz** [comment]
Partner have fixed the problem while re-installing Google Authenticator. Thank you!
