### ISSUE TITLE
IX: suggestion errors on dates (13 pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4608]
When the metadata being extracted is a date three problems are happening.

1. when the model returns a null date, it should be treated as empty. Instead tries to set the value to "null" and gives an error:
![image](https://user-images.githubusercontent.com/489831/167893815-24db96d1-a5de-49a1-81e7-c84b164a2585.png)

2. when the model (service?) throws an error the suggestion is not appearing in the list. it should be display with status "error".

3. Despite the values being the same it is being reported as "mistach / value", but it should actually be "match / value", probably something related to comparing timestamps across different timezones.
![image](https://user-images.githubusercontent.com/489831/167895333-9c29c63f-b905-45a8-a359-e1665a7a8d86.png)

4. Accepting the suggestion displays the modal for multiple languages, but dates have always the same language for all languages. This modal should not appear.
![image](https://user-images.githubusercontent.com/489831/167895694-d456eb65-6c69-42b7-a562-07cb6c094170.png)

5. Trying to accept the suggestion gives an error:
![image](https://user-images.githubusercontent.com/489831/167895735-5b76aaf6-9d35-4f80-a397-c98a1e7ede0e.png)

**Comment by RafaPolit** [comment]
cc @txau do you have a PDF that creates scenario 2 that we can use to replicate the issue?

**Comment by txau** [comment]
@RafaPolit this one: https://summa.cejil.org/es/entity/0u8orp7z2etawcdi
