### ISSUE TITLE
Formatting on simple relationship property is difficult to read (3 pts)

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazidocs#4609]
I've got an entity template which includes a multiselect field ("Membership in Intergovernmental Organisations") and a simple relationship field ("Key Structural Bodies") without inheritance. When creating an entity with this template, the data in the multiselect field is nice and orderly in a list with line breaks. However, the data in the relationship field is really hard to read. In the sidebar view, it's all one long line broken up by commas. In the full view, some wonky spacing is happening that I don't understand. See these screenshots: 

<img width="648" alt="relationship field on entity (full view)" src="https://user-images.githubusercontent.com/56080527/167907702-9d84b358-d515-4192-8739-eb1f9f07bf11.png">
<img width="271" alt="relationship field on entity (sidebar)" src="https://user-images.githubusercontent.com/56080527/167907713-30a73587-ae4f-47bc-acf1-d1250a41f9fd.png">

Not sure about that wonky spacing in full view, but I've seen in other instances that the sidebar formatting (in which it's all one continuous line with items separated by commas) is how it's meant to be. I think the ideal would be that the relationship field is formatted like the multiselect field, one item per line, because this aids skimming, especially when the name of entities are more than just a word or two (as is the case here).

(If you'd like to explore the instance yourself, please message me.)

**Comment by RafaPolit** [comment]
Discussed solution:
- Sidepanel will keep the comma separated list as is
- full entity view will now show one per row (not with bullets)
- Achieve this via CSS selectors and media queries as needed so that it can be overridden by user
