### ISSUE TITLE
URL and source (domain) on preserve integration templates

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#4622]
If a property named url exists and is of type text, use that to add the original evidence url
If a source text property exists, use that to add the original domain of the url.

**Comment by daneryl** [comment]
@txau  The original idea for Source 

> Strip the site from the URL and add it as an extra property to the template so that sources can be aggregated in a filter.

does not work to get aggregates and automatic filters, text properties do not do that, we can do that by creating a special thesauri, and generating values when evidences are imported ... or should we have them as text for now ?

**Comment by daneryl** [comment]
> does not work to get aggregates and automatic filters, text properties do not do that, we can do that by creating a special thesauri, and generating values when evidences are imported ... or should we have them as text for now ?

Working on the thesauri solution as is the only one that makes sense...

**Comment by txau** [comment]
Let's do the thesauri option for now. This makes me think of improving the text filter so users can use it as an aggregation, but until that is a reality this solution is a good solution.

We need to make sure that the process is harnessed so Uwazis using Preserve have that thesauri the same way they need to have the basic template.

**Comment by daneryl** [comment]
> We need to make sure that the process is harnessed so Uwazis using Preserve have that thesauri the same way they need to have the basic template.

this is a manual process at the moment, should we add an issue to autmate this somehow ?

**Comment by txau** [comment]
@daneryl yes. I'll do that.
