### ISSUE TITLE
Fix right click copy/paste glitch

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4632]
After highlighting a text snippet in the document viewer, trying to copy paste the text via right click contextual menu removes the text selection and does not present the "Copy" option in the menu.

Users can still copy paste with control+c shortcut, or right clicking outside the document in the document view (the selection does not get removed).

(tested on FF on linux).

![image](https://user-images.githubusercontent.com/489831/169051740-6cf48269-d691-40c0-ae1e-29011c0008c9.png)

**Comment by Zasa-san** [comment]
https://github.com/huridocs/uwazi/pull/7103 will fix this issue. Please keep in mind that our text selection handler uses the browser selection API, so there's some slight difference in behavior in Firefox vs Chrome based browsers. In Firefox you can right click anywhere after selecting text and it will open the right click menu with the copy option. Chrome requires the user to right click on the highlighted text, clicking anywhere else will clear the selection.
