### ISSUE TITLE
IX - Sort exceeded memory limit

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#4657]
On #4597 @txau posted:

> I'm getting this error when trying to access the suggestion list for a property date. This may be due to an inconsistent state on my end caused by running the code incomplete:
> 
> ```
> 2022-05-17T15:07:35.723Z [localhost] requestId: 8108 
> url: /api/suggestions?page=%7B%22number%22%3A1%2C%22size%22%3A100%7D&filter=%7B%22propertyName%22%3A%22fecha%22%7D
> query: {
>  "page": {
>   "number": 1,
>   "size": 100
>  },
>  "filter": {
>   "propertyName": "fecha"
>  }
> }
> MongoError: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.
>     at MessageStream.messageHandler (/home/txau/work/uwazi/prod/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:272:20)
>     at MessageStream.emit (events.js:400:28)
>     at MessageStream.emit (domain.js:475:12)
>     at processIncomingData (/home/txau/work/uwazi/prod/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
>     at MessageStream._write (/home/txau/work/uwazi/prod/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
>     at writeOrBuffer (internal/streams/writable.js:358:12)
>     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
>     at Socket.ondata (internal/streams/readable.js:731:22)
>     at Socket.emit (events.js:400:28)
>     at Socket.emit (domain.js:475:12)
>     at addChunk (internal/streams/readable.js:293:12)
>     at readableAddChunk (internal/streams/readable.js:267:9)
>     at Socket.Readable.push (internal/streams/readable.js:206:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
>     at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
> original error: {
>  "ok": 0,
>  "code": 16819,
>  "codeName": "Location16819",
>  "name": "MongoError"
> }
> ```

**Comment by LaszloKecskes** [comment]
Closing after merging to the feature branch.
