### ISSUE TITLE
Issue with table view in Uwazi demo instance 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazidocs#4741]
When clicking on the table view button in Uwazi's demo instance: https://demo.uwazi.io , the page directs to a completely blank page and the Uwazi navigation bar also disappears.
![Screenshot 2022-06-12 at 6 15 43 PM](https://user-images.githubusercontent.com/60774708/173233301-d0a78303-e5f7-468c-adad-6509f989d7df.png)

**Comment by txau** [comment]
Apparently this is caused by the rich text property in the "Person" template.

**Comment by nwyu** [comment]
This problem has been resolved. A rich text field on one of the templates held an image that was Base64-encoded `![image of CN](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQ.......)` and not able to be rendered on table view.
