### ISSUE TITLE
Power Bi connection 

### ISSUE THREAD

**Issue by agsabbagh** [huridocs/uwazidocs#4746]
Is there a way to connect the data published in uwazi tenant in power Bi desktop without exporting the data to csv , I mean live connection?

for exmaple,
![image](https://user-images.githubusercontent.com/66379177/173458241-9466ff31-5820-4775-8050-3a3ceea00bc1.png)

**Comment by txau** [comment]
@agsabbagh I am not very familiar with Power Bi so I cannot provide a precise answer, apologizes. Reading their documentation it seems like JSON is supported as format to connect to (https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources).

Uwazi's API is a REST API that returns results as JSON, which is supported by Power Bi. I quick search on G found some detailed instructions such as https://hevodata.com/learn/power-bi-json/.

Uwazi's API is not properly documented at the moment so you'll need to copy the queries from your browser console. So if you are interested in pulling data from the public library, look for a GET request to yoursite/api/search?[query params here] such as 

https://summa.cejil.org/api/search?allAggregations=false&filters=%7B%7D&from=0&includeUnpublished=false&limit=30&order=asc&sort=title&types=%5B%2258b2f3a35d59f31e1345b48a%22%5D&unpublished=false&aggregateGeneratedToc=true&include=%5B%22permissions%22%5D 

which is the query feeding this results page: https://summa.cejil.org/es/library/?q=(allAggregations:!f,filters:(),from:0,includeUnpublished:!f,limit:30,order:asc,sort:title,types:!(%2758b2f3a35d59f31e1345b48a%27),unpublished:!f)

All of this assuming you are requesting publicly accessible information. In the case of protected resources, you'll need to perform that same request with an authenticated cookie first, which is slightly more complicated as explained here: https://community.powerbi.com/t5/Desktop/How-to-Authenticate-a-REST-API-in-Power-BI/td-p/1883942

How to authenticate:

A POST request is performed against /api/login containing the params “username” and “password” in the body.
The endpoint will respond with some cookie params (session id, language) in case of success or an error in case of failure. These params need to be kept for subsequent authenticated requests.

Along with the cookie params these two headers are also required:
- 'Content-Type': 'application/json'
- 'X-Requested-With': 'XMLHttpRequest'

I hope this helps.
