### ISSUE TITLE
Fix timelinks

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4747]
Since we updated the media field timelinks cannot be edited. They are supported but once the URL is submitted it cannot be updated:

![image](https://user-images.githubusercontent.com/489831/173469326-c62aea4d-8ad4-4a56-b0a9-70804e924eb5.png)

Meaning that users need to delete the current content and add it again in order to add/edit timelinks.

**Comment by juanmnl** [comment]
We are doing a not-so-little revamp of the timelinks interaction and UI with this issue.

<img width="919" alt="Screenshot 2022-11-21 at 08 59 40" src="https://user-images.githubusercontent.com/699945/203073597-b6f8155b-edb0-45a9-8201-da42798c667f.png">

**1. Play media**
<img width="469" alt="Screenshot 2022-11-21 at 09 06 36" src="https://user-images.githubusercontent.com/699945/203075017-3a9cb691-1a7c-4b84-9c3a-90ae004765fd.png">

- Clicking/tapping the video should play/pause (as we currently do)
- Clicking/tapping a timelink block/row should take you to that fragment of video, if the video was already playing, it should continue to do so from the start of the timelink, if the video was paused, it should take you to the beginning of that fragment
- Clicking/tapping the play/pause button should allow the user to play/pause directly from a timelink.

**2. Entity Edit**
- Move the edit/unlink actions to the top of the media field block.

<img width="417" alt="Screenshot 2022-11-21 at 09 13 28" src="https://user-images.githubusercontent.com/699945/203076453-363bdf7c-230b-42ac-a5e4-79705ebc0f61.png">

2.1 Adding timelinks manually
- An input should be always available for the user to manually input a timestamp and a label/title for the timelink. After hitting enter or clicking/tapping the plus icon, a new input should become available to the bottom of the recently created timelink.

2.2 Adding timelinks w/trigger
- We are adding a button to the bottom-left of the video, where users will be allowed to click/tap while the video is playing (or paused at a specific timestamp), which should add a new timelink with the timestamp prefilled of the exact moment the button was clicked/tapped.
- The timelinks list should be ordered by timestamp, in case a user adds a timelink with a timestamp in-between two existing timelinks, the new one should be added between the existing ones.  

<img width="966" alt="Screenshot 2022-11-21 at 09 17 06" src="https://user-images.githubusercontent.com/699945/203077281-9965a1cd-06cd-4cba-93d4-3f5c9489a364.png">

* Same behavior is expected in full entity view/edit, but with an enlarged interactive block.

[Prototype](https://www.figma.com/proto/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?page-id=1200%3A8091&node-id=1341%3A8820&viewport=1269%2C-573%2C0.33&scaling=min-zoom&starting-point-node-id=1341%3A8820)
