### ISSUE TITLE
Preserve integration (13 pts)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#4753]
Integrate Uwazi into the preserve flow.

https://www.figma.com/file/fhDpIi4fP2DgrFBMoHodiT/browser-extension?node-id=0%3A1

**Comment by juanmnl** [comment]
Here's a direct link to the updated designs.
- Extension button (if browser detection and store is possible)
- Extension link for static links to all the stores the extension is available.

- Request token + Copy token.

[In-Uwazi Preserve settings](https://www.figma.com/file/fhDpIi4fP2DgrFBMoHodiT/?node-id=43%3A353)

**Comment by konzz** [comment]
Preserve Settings:
https://github.com/huridocs/uwazi/blob/b8ac0efc9be63505aab1a2a30b2a66289ad1131a/app/shared/types/settingsType.d.ts#L32-L39

Preserve template can be empty but the 2 supported props are: 
```
{ name: 'url' type: 'link' }
{ name: 'source' type: 'select'}  ->associate with empty thesauri 
```

**Comment by txau** [comment]
Template creation needs to be implemented as well: https://github.com/huridocs/uwazi/issues/4631

**Comment by elreplicante** [comment]
The URL on Preserve to generate the token will be `POST /api/tokens`.  It will receive an `Authorization` header with the Preserve master token and return the generated token.

```json
{ 
  "data":  { 
    "token": "<generated_token>"
  }
}

```

It should be enough to associate the token with the user that requested it.

**Comment by txau** [comment]
- Remove text "You have not connected an Uwazi instance, yet"
- Remove text "Some information about the token"
