### ISSUE TITLE
Preserve extension styling

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#4754]
https://www.figma.com/file/fhDpIi4fP2DgrFBMoHodiT/browser-extension?node-id=0%3A1

**Comment by daneryl** [comment]
@RafaPolit should not this issue be on the extension repo ?

**Comment by RafaPolit** [comment]
Yes, we were just "organizing" the sprint.  Bad habit.

**Comment by RafaPolit** [comment]
Done in the Preserve repo.
