### ISSUE TITLE
Re sync from scratch normally results in mid sync errors due to elastic index miss match

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#4755]
**Describe the bug**
Re sync from scratch normally results in mid sync errors due to elastic index miss match.

**To Reproduce**
probably depends on the dateset to resync, not sure, this needs to be further debuged.
After some more testing i belive this happens when an entity is synced before its template, elastic creates dinamyc mappings, and when the template is finally synced, it throws a mapping error when they are different.

**Expected behavior**
resync from scratch finishes without errors.

**Comment by txau** [comment]
Sync should have a particular order when syncing data:
- First sync stuff that has no other data dependencies (thesauri, relationship types)
- Then sync templates (depend on thesauri and relationship types)
- Then sync entities

**Comment by daneryl** [comment]
Still happening, pretty anoying, lost a full day on this, bumping priority.
