### ISSUE TITLE
Long / too many Menu items simply extend out of the screen

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#4765]
**Describe the bug**
If you configure more than X amount of items in menus, or give them very long names, they extend out of the screen.

**To Reproduce**
Configure a lot of menu items with long names.

**Expected behavior**
Detecting the screen width (and on screen resize), it should hide the "un-seable" items into an ellipsis button.  Language selector and buttons should still be "fixed" to the right of the window and not disappear behind the ellipsis.

**Comment by nwyu** [comment]
Related to #2909.

**Comment by txau** [comment]
Make sure settings menu always renders on the top right without being pushed by the menus. quick fix.

**Comment by mfacar** [comment]
After some attempts, it was not possible to introduce a quick fix that hides/collapses the options that go outside the allocated area, at the moment the applied solution is to set a maximum width so that, in the case of long elements, the action buttons will remain accessible. 
cc. @RafaPolit
