### ISSUE TITLE
Responsive text mode for mobile (3pts)

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4779]
**Is your feature request related to a problem? Please describe.**
When consuming PDF documents in a mobile device, the screen is to small to properly render the PDF. Our current text mode has formatted text, that is line breaks try to keep the original document layout, which renders ok for big screens but it is problematic for small screens.

**Describe the solution you'd like**
Ideas:
- Have yet another copy of the extracted texts without any format. This poses some overhead on the database as this information is redundant. This is the version that will be offered if a smaller screen is detected.
- Change our text mode to un-formatted text, even for big screens. The down side is that it can greatly affect readability.
- Wait for a PDF to responsive HTML convertor. We can research available open source libraries for this purpose or wait for the ML team to create their own one (we are close to this objective at the moment).

**Comment by RafaPolit** [comment]
We quickly looked and we can do a nice trick:
- take the plain text outside the `<pre>` tag into a `<div>`
- make that `div` behave like a `pre` with `white-space: pre` or `white-space: pre-line`
- IMPORTANT! Do that ONLY for targeted sizes larger than SM (or MD)

That way, the text will wrap as the original as it did before, but it will collapse nicely on small devices.
