### ISSUE TITLE
Rendering Icons in Relationship properties is broken

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#4791]
**Describe the bug**
When assigning an icon to an entity, if you create a relationship property pointing to that entity, the icon is not being shown.

**To Reproduce**
1. Create Entity A and assign an icon to it
2. Create a Template with a relationship property pointing to Template of Entity A
3. Assign Entity A to that property

**Expected behavior**
The icon should appear and be respected.

**Comment by txau** [comment]
same as https://github.com/huridocs/uwazi/issues/4545

**Comment by RafaPolit** [comment]
The function `renderRelationshipLinks` in Metadata.js is doing something weird when sending values to `RelationshipLink`.  I have narrowed down the problem to that specific area, needs further debugging.
