### ISSUE TITLE
IX labeled dates are inconsistent

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#4795]
Depending of how you fill labeled dates in the IX feature, it takes different shapes in the database:
- Accepting a suggestion puts a string timestamp into the extra ted metadata for the file.
- Manually labeling through the PDF view in the IX UI puts the textual reference on the PDF.
- Some other scenarios may be possible.
This results in wrong state calculations for the suggestions.

Adding to that, the date formats accepted are not enough in some cases. For example `Jun 28, 2022` won't be properly parsed.

**Comment by LaszloKecskes** [comment]
Closing after merging to the feature branch.
