### ISSUE TITLE
IX manually editing a labeled field leads to intermediate selection state

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#4797]
When a labeled field is edited manually, the selection rectangles are removed but not the extracted metadata, leading to wrong states for suggestions because the field is detected as labeled.

**Comment by LaszloKecskes** [comment]
On further testing, it might be that it is not the editing that causes this, but that the selection rectangles are missing for titles.

**Comment by LaszloKecskes** [comment]
Closing, since unable to reproduce the issue on the current feature branch.
