### ISSUE TITLE
Adding languages requires reload

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#4841]
**Describe the bug**
When adding more than one language the UI requires a reload in order for translations to work properly. Without the reload, live translate might not show all available languages, and will fail when trying to save a translation.

**To Reproduce**
1. On an instance add 2 languages.
2. Without navigation or reloading, try to live translate. 

**Expected behavior**
Not requiring a reload to work properly.

**Screenshots**
This is what appears for live translate when adding French and trying to live translate the term `FILTERS` on the library, without reloading previously.
![image](https://user-images.githubusercontent.com/71732018/177615181-804f9ea0-86e3-4c51-a25b-8c9ba78f4aa8.png)

**Device (please select all that apply)**
Desktop

**Browser**
Firefox

**Additional context**
Deleting more than one language can also cause problems. This is very likely to Redux not updating correctly.

**Comment by RafaPolit** [comment]
Will be worked on #5933

**Comment by LaszloKecskes** [comment]
Closing in favor of #5960 and #5961.
