### ISSUE TITLE
Register event listeners automatically on tests

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#4858]
Currently, the event listeners on the back end event bus are loaded explicitly in the tests that need them. However, if we will continue to add more functionality to this framework, we may start to loose important side effects in how the code works. We should make all eventListeners automatically register on test setup.

**Comment by fnocetti** [comment]
Updating after discussion:
This makes sense for integration tests from non-core features. We want any other test that's testing for events, to explicitly register listeners.
