### ISSUE TITLE
IX: Blank states are not created when a file is added to a new entity

### ISSUE THREAD

**Issue by grafitto** [huridocs/uwazidocs#4863]
**Describe the bug**
Blank suggestion states are not created when a user adds a file to a new entity

**To Reproduce**
1. Go to metadata extraction section, configure `title` property in the `document` template
2. Create a new entity of template `document`
3. Upload a file to primary documents
4. Label some data and click to fill `title`
5. Move to metadata extraction section in settings
6. Move to suggestions table of property `title`
7. No suggestion for the newly uploaded file on the newly created entity.

**Expected behavior**
A blank suggestion should appear in the suggestions table, for the newly uploaded file in the entity created.

**Device (please select all that apply)**
 - [x] Desktop
 - [ ] Mobile

**Browser**
Microsoft Edge (Chromium), though browser should not matter

**Additional context**
None

**Comment by LaszloKecskes** [comment]
Closed by merging to the feature branch.
