### ISSUE TITLE
Import System UI translations from a "predefined" remote repo

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#4872]
We are going to create an Uwazi-assets repo in github to contain UI translations, common Thesauri (like countries, or some HURIDCOS predefined ones), and, further down the line, common Entity CSVs for example, for extended Countries with flags, etc.

For the System Translations values, we want a small flow that will allow:
- From Translations system list select: Import UI translations (final name to be defined)
- use the GitHub API to fetch the current options available in the new Github repo (within a known path)
- select a "Download & Install" button to install it

Let's see the best path to do the actual download: ideally the client should fetch the data and send it to the backend so that we don't pollute the backend with extra options.  Alternatives: have a route in backend that downloads the data and sends it to the client and the client uses that data to create the translations (this has the advantage of not polluting the Translation routes, but it adds some backend request to the "outside world"). Finally we could expand the Translations routes to have a "from external repo" functionality.

Alternatively, we could import the assets repo into Uwazi and they could be simply loaded and used from within Uwazi.

This *could* include Backend work.

Related to #4871

**Comment by juanmnl** [comment]
A couple of changes with this one:

1. Translations page
- Move the UI translations to the top in it's own group
- Add a flag separator to identify both groups (System translations & Content translations)
- 
<img width="1064" alt="Screen Shot 2022-08-22 at 11 56 51" src="https://user-images.githubusercontent.com/699945/185894544-dca712bb-f09a-4d8b-a1ab-344a2ab530cc.png">


2. Languages page
- Upon adding a language, if the translation is available on the repo, we'll add that csv. We'll also add a new button to reset/update the translations from the repo.
- "Set as default" should be always visible and active only on the selected one.
- "Delete language" should be available always, except for the default language. If the user deletes the language they're in, the page should reload into the default language state.
- Remove the warning to the side of the available languages
- Add a pill with the message "Available default translation" to show which ones are available.

<img width="1036" alt="Screen Shot 2022-08-22 at 16 39 40" src="https://user-images.githubusercontent.com/699945/185948780-de17f42d-6b00-4fdf-9227-3c0236b88c92.png">


[Designs](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=276%3A2815)
