### ISSUE TITLE
IX: When accepting a suggestion sets the wrong status

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#4874]
**Describe the bug**
When accepting an IX suggestion, the client sets the status to Match / Value, but now when we accept a suggestion we also store the label data, that means the correct status is Match / Label

**To Reproduce**
Accept an IX suggestion

**Expected behavior**
The client should set the status Match / Label

**Comment by grafitto** [comment]
This behavior seems not to be happening any more.
