### ISSUE TITLE
IX Find sugestion buttons loses status when going away from the panel and can be pressed again

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#4875]
**Describe the bug**
If you press Find sugestion in IX a training process starts, and then  starts fetching suggestions, this statuses are updated to the client on every event, but if you leave the screen and come back the button will show "Find sugestions" until one of those events finishies.

**To Reproduce**
1 - Go to IX for any property and start a training
2 - Go back to the IX config panel
3 - Enter again in the same property

**Expected behavior**
The button should have the current status, and if pressed should stop sending any batch for fetching suggestions. (Training can not be stopped for now)

**Comment by txau** [comment]
@konzz 

- wrt to the current status, is it possible to show the current batch number when it is finding suggestions? Right now it recovers the state but it only says "Finding suggestions" with no indication of the progress. (optional)
- We said that we cannot stop training, but we can stop sending suggestions. Right now when pressing the button again, we are re-sending the training data and initiating the process again. I think we could do:
  - When the button is in the state "Training" the button cannot be pressed. It needs to wait until the model is finished even if you want to stop.
  - When the button is in the state of "Finding", it can be pressed and presents a confirmation message "Do you want to stop finding suggestions?" with the options Yes/No.
