### ISSUE TITLE
Integrate S3 file hosting

### ISSUE THREAD

**Issue by elreplicante** [huridocs/uwazidocs#4882]
**Is your feature request related to a problem? Please describe.**
Our current disk based infrastructure for hosting files can expensive for partners coming with huge amount of data.  S3 storage can be cheaper than the current glusterfs solution

**Describe the solution you'd like**
Upload files on an S3 server instead, with the current disk strategy still available for backwards compatibility and self-hosted solutions.

**Additional context**
This issue is related to the whole feature, but is going to be tackled in small releasable steps:

- [x] Encapsulate current access to the filesystem into abstraction.
- [x] When a file is accessed, try to reach it from S3, if the file is not there, read it from the filesystem but also upload it to S3 (migration on read time).
- [x] Create api for write and delete (or any other needed) in the new storage so that we can eslint disable the deprecated ones.
- [x] When a file is deleted, remove it from the filesystem and S3.
- [x] When a file is uploaded, save it on the filesystem and S3.

**Comment by txau** [comment]
Migrate on read may not migrate all files? some files may never be accessed.

**Comment by daneryl** [comment]
> Migrate on read may not migrate all files? some files may never be accessed.

This is true, the plan is to migrate everything that is missing as the final step, when we are sure the functionality is working.
