### ISSUE TITLE
Deleting obsolete mongodb indexes

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#4908]
In #4276, the solution was to extend a mongodb entity index into a composite (template -> template_language_published). We do this through mongoose, and mongoose automatically adds the new index on database access. However, mongoose does not automatically remove obsolete indices. One possible justification is that one might have indices set up outside mongoose, and the existing sync function removes those (i.e. it syncs the indices to be exactly the same as they are on the schema).

Possible options to resolve this:
- if we do not (or do not want to) entirely handle indices through mongoose, write explicit migrations to remove indices, when we know we do not need them any more - in this case, in this issue the task is to complete #4276 by removing the old index
- if we are okay to handle things in mongoose, ensure that the sync function is called for each schema on startup (server.js) and for tests. This might be somewhat tricky to do.
- we can also decide to leave this to the back end rewrite, where we are planning to drop mongoose anyway, and live with an obsolete index for now - in this case, close this issue with a comment

**Comment by fnocetti** [comment]
There are a couple of things to consider:
- We got used to the convenience of mongoose creating indexes for us, but technically both creation and deletion of indexes, given that indexes are part of the db structure definition, are migration concerns (of course there are some exceptions). So I think we should create a migration when we need to delete an index. If at some point we remove mongoose from the dependencies, we will have to use migrations to create indexes as well.
- I don't think elasticsearch and mongo indexes are mutually exclusive, and I think it would be a mistake to use elastic to avoid indexing in mongo and can bring a lot of trouble in the future.

**Comment by txau** [comment]
We don't have many of these situations at the moment.
- Let's keep creating indexes with mongoose
- Deleting indexes need to be removed from mongoose + create a migration

@fnocetti I think we should create a separate issue for the migration for deleting the index that has been giving problems, can you take care of writing that issue?
