### ISSUE TITLE
Simplify date field type

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4921]
**Is your feature request related to a problem? Please describe.**
Our template creator has too many field types, particularly date fields. 

**Describe the solution you'd like**
Date fields could be simplified into a single field "Date/range" that includes some configuration options to:
- Enable multiple options
- Single date / range

**Comment by juanmnl** [comment]
Pretty straight forward. We are removing all of the different blocks for date fields, keeping a single "Date" block. Once added to the template we are adding a dropdown input to provide the user with the options for property types.

<img width="707" alt="Screen Shot 2022-08-22 at 16 21 41" src="https://user-images.githubusercontent.com/699945/185944520-a8799db4-c3c0-44b4-9b92-fc45892677c8.png">

[Designs](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=270%3A948)
[Prototype](https://www.figma.com/proto/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?page-id=270%3A948&node-id=273%3A2424&viewport=273%2C428%2C0.51&scaling=min-zoom&starting-point-node-id=273%3A2424)

**Comment by RafaPolit** [comment]
It is important to modify the e2e that adds all the properties on the right by iterating over the elements to now actually add this property several types and select the different types.  It is important that the logic of the e2e is changed.
