### ISSUE TITLE
Simplify select field type

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4922]
**Is your feature request related to a problem? Please describe.**
In order the reduce the amount of available field types in templates we could simplify select and multi-select fields into a single field type.

**Describe the solution you'd like**
The new field could be called "Thesaurus" since this field type works with thesaurus alone (relationship fields are different) and have a configuration option to indicate whether a single option or multiple options are allowed. 

Generally speaking, the behavior should that of a multi-select. TBD how the field will behave when it needs to act as a single option select (ie. selecting a new option deselects the previous one, it has some UI hint, etc) (cc @juanmnl )

**Comment by juanmnl** [comment]
Pretty straight forward. We are removing all of the different blocks for select fields, keeping a single "select" block. Once added to the template we are adding a dropdown input to provide the user with the options to select the property type.

<img width="802" alt="Screen Shot 2022-08-22 at 14 31 08" src="https://user-images.githubusercontent.com/699945/185921601-607fb522-c04e-4763-b27f-1cc40e4ecde5.png">

[Designs](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=270%3A948)
[Prototype](https://www.figma.com/proto/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?page-id=270%3A948&node-id=295%3A952&viewport=273%2C428%2C0.51&scaling=min-zoom&starting-point-node-id=270%3A1964&show-proto-sidebar=1)

**Comment by RafaPolit** [comment]
It is important to modify the e2e that adds all the properties on the right by iterating over the elements to now actually add this property twice and select the different types.  It is important that the logic of the e2e is changed.
