### ISSUE TITLE
Potential unneeded code

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#4956]
There is code that deletes Language specific files when deleting a whole language: 

https://github.com/huridocs/uwazi/blob/d5de1476ccd0a103a646b47c73e0cc91048c210e/app/api/entities/entities.js#L744-L760

this does nothing, entity.file is always undefined i believe, this is legacy code that may not be relevant after all the changes we made to main files and attachments, needs double check.

**Comment by RafaPolit** [comment]
There is no longer the concept of "file per entity-language".  Entities now can have any number of files and not bound to the languages.  Also, attachments that were added "per language" are now appended to all versions of the entity by shared ID, so I agree that the concept is complete deprecated.
