### ISSUE TITLE
api/translations/import always fails validation.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#4976]
**Describe the bug**
Validation always fails because of a schema missconfiguration.

**To Reproduce**
1. upload a csv to api/translations/import
2. See error

**Additional context**
This happened on an update of the AJV library, in this update every single schema was throwing errors on tests because of a new strict mode, this specific endpoint has no tests and its not covered by e2e either.

**Comment by LaszloKecskes** [comment]
Closed through hotfix.
