### ISSUE TITLE
Filter untranslated entries in translations menu.

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#4978]
**Is your feature request related to a problem? Please describe.**
When looking at the list of terms in `Translations` it's difficult to figure out what terms I have already translated. This is especially true for `User Interface` but can also happen with long thesauri. It would be really helpful to be able to filter terms that I have already translated and only see those that might need one.

**Additional context**
An idea for the implementation is to filter keys by value. If, for a given key, there are one or more values that match the default language value, assume that it is untranslated. This way users will only see translations that are likely to be new. This should work regardless of the number of languages the user has, or the default language.

**Comment by juanmnl** [comment]
For this, we'll introduce a toggle switch at the top-right of the page, next to the title. In the case of very long titles, the text should brake before the toggle, so it stays always in the same position.

<img width="710" alt="Screen Shot 2022-09-14 at 10 40 37" src="https://user-images.githubusercontent.com/699945/190105631-27021f7a-f791-42c8-b687-1a2bfa7a191c.png">

<img width="1311" alt="Screen Shot 2022-09-14 at 10 40 14" src="https://user-images.githubusercontent.com/699945/190105509-93e3ebc6-728f-41ff-a9f7-a2e828d93bed.png">
