### ISSUE TITLE
Mobile, sidepanel cannot be closed on entity view

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#4980]
**Describe the bug**
On a mobile screen, when viewing an entity that has no main document, the side panel cannot be closed.

**To Reproduce**
1. Open UWAZI on a mobile screen.
2. Create an entity with just a title.
3. View the entity.

**Expected behavior**
The side panel should be closed by default on mobile, and always have a close button.

**Screenshots**
![image](https://user-images.githubusercontent.com/71732018/183494861-574ebed6-5a87-401c-8848-8ddafe42b63e.png)

**Device (please select all that apply)**
Mobile

**Browser**
Firefox

**Additional context**
Is the screenshot there's also an issue with map controls.  :rotating_light:

**Comment by nwyu** [comment]
I think @RafaPolit is providing a temporary solution for this in PR #4941.

**Comment by RafaPolit** [comment]
Yes, temporary fix until a more UX-oriented design is defined.
