### ISSUE TITLE
Various problematic UI strings need correction to facilitate localization

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazidocs#4983]
**Describe the bug**
There are dozens of strings in the Uwazi UI that need modification in order to facilitate translation. They can be summarized as belonging to four main buckets: 

- messages that are split into two or more strings in a way that takes for granted all languages follow the same word order as English (but they don't)
- messages that are split into two or more strings, and their keys are not descriptive to indicate that each string is part of a larger message (really difficult for a translator then to correctly render a translation)
- untranslatable strings (not part of `Settings --> Translations --> User Interface`)
- misspellings and other grammar errors

The attached spreadsheet lists them out with the following columns: 

- key (when available)
- string
- context (to the best of my ability that I could see as a user in Uwazi hunting down individual instances of terms)
- an explanation of what is problematic
- a suggestion for a fix

[problematic UI strings.xlsx](https://github.com/huridocs/uwazi/files/9292716/problematic.UI.strings.xlsx)

**Comment by RafaPolit** [comment]
We should probably split this into separate issues.  Some points are really bugs like bullet points 3 and 4, bullet points 1 and 2 are more complex and not necessarily  bugs but tech-debts or features (in order to prioritize them and point them to the right team and pipeline).

**Comment by mfacar** [comment]
There were fixed most of the reported strings however a subset split into #5352 in order to decide an appropriate solution for them.
