### ISSUE TITLE
Endless scroll in Table View is not the right approach

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#4996]
After several discussions, we mostly agree that Endless Scroll for the Table View was the wrong approach:
- Does not play well with "select all" features where you have little control over what is loaded
- Sharing links to a particular status could change things "here's a link, go to the previous to last item...", well, good luck!
- Detecting user nearing place where you want to load more is erratic, sometimes it loads more, sometimes you are stuck with your current results
- etc.

We are now mostly in agreement that we want a paginated view of Tables.

(Split from #3732 to work on the pagination first, and then tackle the "select all")

**Comment by RafaPolit** [comment]
First iteration is to not go for pagination.

- [ ] Remove endless scroll
- [ ] Add "load more" exactly as in the library

**Comment by juanmnl** [comment]
As Rafa mentioned, we'll bring the load more component of the card view to the table view, same behavior and interaction.

<img width="1440" alt="Screen Shot 2022-09-05 at 09 23 22" src="https://user-images.githubusercontent.com/699945/188392787-f7bfc069-0cd2-407f-92bf-ff60ae274dc2.png">



[Designs](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=341%3A952) for load more, entity selection and multiple selection on table view.

[Prototype](https://www.figma.com/proto/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?page-id=341%3A952&node-id=342%3A1910&viewport=803%2C336%2C0.82&scaling=min-zoom&starting-point-node-id=342%3A1910)

I'm not sure if we'll add selection and multiple selection to the scope of this issue, if not, @nancy or @RafaPolit lmk where to put those :)
