### ISSUE TITLE
Update Sass

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#5001]
Node-sass is deprecated, we need to update to the new Dart Sass in order to be able to update other packages which depend on this new version, like React Widgets. 
We have to update also sass-loader as a dependency for Sass and fix the possible errors during the migration.

**Comment by RafaPolit** [comment]
Let's delay this change as much as possible.  It could happen that we are already doing V2, or that we can keep using the old versions longer as long as there are no security issues involved.
