### ISSUE TITLE
Table View - click row, and click checkbox need to be fixed

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#5039]
**Is your feature request related to a problem? Please describe.**
Current row / checkbox behavior in table view is not what users expect

**Describe the solution you'd like**
- Clicking on a row should show the sidepanel with the entity data, as clicking on the card view in library
- Clicking on checkbox should start a multi-selection with a single entity checked (the display should be the "stacked" view of multiselect on the sidepanel
- If there are checkboxes checked (one or more) and you click on a row, it should put the entity metadata on top of the multiselection, but keeping the checkboxes checked
- This could present a conflict if the user clicks on "edit" on a single entity in the sidepanel while having multiple checkboxes checked, this may need some thought over the process

**Comment by juanmnl** [comment]
[Designs](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=341%3A952) for load more, entity selection and multiple selection on table view.

[Prototype](https://www.figma.com/proto/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?page-id=341%3A952&node-id=342%3A1910&viewport=803%2C336%2C0.82&scaling=min-zoom&starting-point-node-id=342%3A1910)

**Comment by RafaPolit** [comment]
It is important to take into account the text selection process.

There are apparently ways to check if a click-process ended up with a text selection.  In that case, stop the bubble up or propagation of the click event to avoid showing that entity in the sidepanel.

**Comment by RafaPolit** [comment]
The MVP for this will mimic exactly the library behavior for now.

IMPORTANT: make the entire ceckbox cell the "clickable" area so users failing to hit "exactly" the right location are not penalized by loosing all their selections.
