### ISSUE TITLE
Change default state to private on Uwazi instance creation

### ISSUE THREAD

**Issue by nwyu** [huridocs/uwazidocs#5066]
When we spin off a new instance, our current default is public. In order to make the instance private, we must log in and navigate to Collection Settings to toggle on and save the instance explicitly as private.

The new default starting point will be as private.

**Comment by txau** [comment]
This should be as easy as changing the blank state db dump to contain that configuration instead of the public flag.

**Comment by RafaPolit** [comment]
Please create this as a HOTFIX so it gets deployed to production directly.
