### ISSUE TITLE
Contact form has no validation

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#5084]
**Describe the bug**
When submiting a contact form it has no validation before submiting. If the user entered a wrongly formatted email it will return a `validation error` from the API.

**Expected behavior**
Should not submit with invalid email.

**Additional context**
Comes from https://github.com/huridocs/uwazi/issues/4901

**Comment by txau** [comment]
Contact form has server side validation. We could improve the overall user experience with front-end validation.

**Comment by Zasa-san** [comment]
Fixed
