### ISSUE TITLE
Sync can cause the target host to have 2 Default templates.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5096]
**Describe the bug**
Sync can cause the target  to have 2 Default templates when the target has already a default template that is not the same as the host.

**To Reproduce**
1. Create 2 tenants
2. Each tenant with a different Default template. Ensure that the default template is not the `Document` template that comes with the blank state, but a brand new one for each tenant.
3. Sync the default template from tenant host to target
4. You should see 2 default templates on the target tenant

**Expected behavior**
Only the already default template on the Target should remain as default.

**Screenshots**
![Screenshot 2022-09-12 at 13 05 41](https://user-images.githubusercontent.com/1386423/189638424-c77b0175-ba80-48c2-89f3-02768decbf63.jpg)

**Comment by RafaPolit** [comment]
We have discussed an option to zero-out the relevant collections upon first sync or resync.
