### ISSUE TITLE
Multi-tenant storage on S3 should be folder based instead of bucket based

### ISSUE THREAD

**Issue by elreplicante** [huridocs/uwazidocs#5098]
S3 providers usually have a uniqueness limitation on bucket names, so buckets hosted on the same region/cluster cannot share names.  This can cause conflicts with our current implementation, which assumes you have a bucket created with the same name as the tenant name.

Moving to a folder-per-tenant strategy should avoid this problem.

**Comment by txau** [comment]
@elreplicante from the S3 documentation https://docs.ceph.com/en/quincy/radosgw/multitenancy/#rgw-multi-tenancy I think there are other options to manage this scenario?
