### ISSUE TITLE
PDF to text is being executed on non-pdf files

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#5125]
**Describe the bug**
We are seeing a few messages about attempts to extract text from non-PDF files:
```
pdftotext /tmp/1663821835115nhezigjjt9m.jpeg - failed with code 1
stderr output:
Syntax Warning: May not be a PDF file (continuing anyway)
```

**To Reproduce**
It is unclear how to reproduce. Likely via CSV import with attached files?

**Expected behavior**
Non-PDF files should not be allowed as main file for the moment.

**Comment by RafaPolit** [comment]
PDF filter on the file selector is just a "suggestion", users can actually remove the filter and select "all files", and simply upload anything.

We need to be able to limit the extension (currently to PDF, in immediate development of `any document` it should have more extensions supported).

We need to introduce a filetype validation, but someone could also upload a non-pdf file with a PDF extension, and for that we just need to handle the errors.

**Comment by txau** [comment]
This is irrelevant at this stage. Users can force the upload of a non-PDF file, but it is not affecting in any negative way.
