### ISSUE TITLE
Fix settings navigation on mobile

### ISSUE THREAD

**Issue by nwyu** [huridocs/uwazidocs#5129]
**Is your feature request related to a problem? Please describe.**
When clicking the items within the settings navigation on mobile, the form displays below all the items. It is misleading to a user who expects to see something after their click selection, but instead must scroll down to find the content that they are expecting to see.

**Describe the solution you'd like**
This could be solved with a caret right icon. Link to the [Figma design](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=791%3A7875).

**Comment by juanmnl** [comment]
Very standard mobile navigation pattern. The idea is that you can navigate to settings, which will only show you the menu itself, and from which the user can access every section as a "nested page". This means we'll need the implementation of a back button that allows users to go back to the menu from each settings page.

![2022-10-21 13 17 50](https://user-images.githubusercontent.com/699945/197184977-313c7e0b-9f4c-44b9-8d97-148867fe9f56.gif)

You can find a very simple design [here](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=791%3A7688)

[Prototype](https://www.figma.com/proto/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?page-id=791%3A7688&node-id=911%3A8305&viewport=1566%2C-69%2C0.46&scaling=scale-down&starting-point-node-id=911%3A8305)
