### ISSUE TITLE
Request for appropriate error message when a user tries to save geolocation data with only latitude information

### ISSUE THREAD

**Issue by pddocs** [huridocs/uwazidocs#5130]
**Describe the bug**
At present, Uwazi allows users to create an entity with a geolocation field by adding just one of the two coordinates in the field. After saving, when one views the entity, it does not render any geolocation, as expected. However, there is no notification from Uwazi mandating the user fill both the latitude and longitudes before/to be able to save the entity. 

**To Reproduce**
1. Go to ‘Create entity’ in a template with geolocation property
2. Add information in the latitude field only
3. Save the entity
4. Click view to open the recently created entity 

**Expected behavior**

Uwazi ensures users add both the Latitude and Longitude fields to be able to save the entity.Both latitude and longitude fields are visible at 100% zoom level of the browser.

**Screenshots**

https://user-images.githubusercontent.com/88421793/191933038-122c106b-e24e-4d93-ab25-af346320cff0.mov

**Device (please select all that apply)**
 - [x] Desktop
 - [x] Mobile

**Browser**
Chrome

**Comment by RafaPolit** [comment]
Thanks for this report.  Indeed, there are a couple of things wrong here.  One is the complete lack of error reporting, the values entered when no LONG is filled are simply lost.  The other issue is the input resizing upon keystrokes, it has been reported in a separate issue.

We will try to provide a quick fix to both problems.
