### ISSUE TITLE
Wild first screen upon new instance creation

### ISSUE THREAD

**Issue by nwyu** [huridocs/uwazidocs#5132]
**Describe the bug**
Upon creation of a new Uwazi screen, the first screen (on Chrome) displays like this:
![chrome_WeEtF3bxUf](https://user-images.githubusercontent.com/56067374/191962695-9bf91ed7-41ae-4a34-9cc5-10f70e3cab77.png)

Only on refresh does the correct screen show: 
![chrome_OUN7QXv0EW](https://user-images.githubusercontent.com/56067374/191963371-ca45108c-162f-4af6-82bd-2f17b4e138bb.png)

This does not appear to occur on Firefox, Edge or Brave.

**To Reproduce**
1. Create a new Uwazi instance.
2. Open the URL in Chrome.

If you login with default credentials and then logout again, the same wild screen is still present.

**Device (please select all that apply)**
 - [x] Desktop
 - [x] Mobile

**Comment by txau** [comment]
@nwyu is that happening wit the same browser you use for creating the instance? have you tried to load the instance in Chrome in another computer after creating it? This may be only affecting your chrome, in your computer, when you are using that same chrome for creating instances?

**Comment by elreplicante** [comment]
It's happening on Firefox too, tested on the local virtual infrastructure.

**Comment by daneryl** [comment]
Testing a sync config i have noticed that this happens only on redirection to login, that is why on reload it goes away.

To replicate, go to any blank-stated that is NOT set as private, when there is no public entities, uwazi automatically redirects to login, causing the styles to break, its strange that on the apparently same redirection to login when the instance is private this does not happen.

**Comment by mfacar** [comment]
For some reason the RedirectFunction `replace` from `library` to `login` was replacing only the main content of the screen, after trying some alternatives, the chosen solution in #5151 was to use a `window.location.assign` instead of `replace` in order to ensure the reload of the page, this applies only when entering to login from a redirection.
