### ISSUE TITLE
Export to CSV files issue

### ISSUE THREAD

**Issue by AhmadQadi1** [huridocs/uwazidocs#5140]
**Describe the bug**
When I export data to CSV file, the English text works well while the Arabic texts appear in symbols. The system seemingly doesn't support Arabic language. Check below a screenshot of an exported CSV file.

**To Reproduce**
1. Go to 'UWAZI'
2. Click on 'Export'
3. Open the CSV file

**Expected behavior**
The sheet should reflect exactly the raw data in Arabic or English as stored in UWAZI.

![Untitled](https://user-images.githubusercontent.com/95572565/192292555-f914e303-78c5-41cb-9ebb-7ce9d90582b6.png)

**Comment by nwyu** [comment]
@AhmadQadi1 [Uwazi exports CSV files in UTF-8 format](https://uwazi.readthedocs.io/en/latest/admin-docs/working-with-entities-in-your-collection.html?highlight=utf-8#how-to-export-entities), expressly to maintain characters like Arabic. This means that in a new Excel workbook, you need to navigate to the Data tab > click Get Data > click From File > click From Text/CSV > add your file > you get a preview of your data and at the top there is a File Origin dropdown where you an select 65001: Unicode (UTF-8). Unlike Excel, if you use Libre Office or Google Sheets, both applications detect UTF-8 format automatically.

**Comment by AhmadQadi1** [comment]
Dear Nancy, I did exactly as you advised, it worked for the Arabic, but check the attachments below how the columns are in total mess, the data didn't reflect the same scheme on UWAZI. In the preview there is an ability to divide the columns, I tried it to solve this issue but also it didn't work.
![2](https://user-images.githubusercontent.com/95572565/192693553-4a27e25d-da6a-4f80-85a7-04bac84c4134.png)
![Untitled](https://user-images.githubusercontent.com/95572565/192693556-7f5ec3e7-d159-4745-8ee7-70963deaaa31.png)
