### ISSUE TITLE
Files won't upload using Tella app

### ISSUE THREAD

**Issue by dohko01** [huridocs/uwazidocs#5150]
**Describe the bug**
In the creation of a new entity from an Uwazi template, any file attached to any part of the template isn't uploaded to the server. The form info is uploaded correctly.

**To Reproduce**
1. Install Tella from Playstore
2. Add an Uwazi server
3. Create new entity and attach files to it.
4. Save the entity

**Expected behavior**
Files attached to a new entity should be uploaded to the server and showed in the web admin.

**Screenshots**
I don't know if this has something to do with it but I think it does.
![image](https://user-images.githubusercontent.com/5553331/193137877-72b54d79-5ed2-463f-b1d6-1ec674942f61.png)

I tested it with Uwazi releases 1.84.0 and 1.85.0

**Comment by elreplicante** [comment]
As discussed with Tella developers, they are going to fix this on their side.  Is a backwards compatibility problem but they want to adhere to the new implementation.
