### ISSUE TITLE
Timestamps are not functional on public instance when synced 

### ISSUE THREAD

**Issue by mennaelmassry** [huridocs/uwazidocs#5163]
**Is your feature request related to a problem? Please describe.**
Yes, it is related to a problem: 
When media fields with timestamps are synced from a private instance to a public one, those media fields on the public instance do not play, and the timestamps are not functional... 

**Describe the solution you'd like**
Be able to play synced media fields and use their timestamps on the public instance...

**Have you considered an alternative?**
Yes, there are no alternatives in this case

@nwyu @MatelSow @RafaPolit

**Comment by nwyu** [comment]
Related to #5170.
