### ISSUE TITLE
Sync use case, attachments used as self URLs.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5170]
A use case just came up, Audio attachments need to be set as direct URL to the host instance in order to be able to set the playable chapters (@konzz can you confirm this ?), the full URL will  sync to the target instance, this causes a number of problems.

- Big files are synced but really not used since the one used is potentially the original hosted in the host instance
- Exposes the host instance URL
- Links  do not work since the host instance is usually private

### To replicate

1. Set a blank state
2. Create a template with a media property
3. Add some entities with audio attachments
4. Add the attachments to the media field using the URL instead of selecting the file
5. Configure a sync with this Template and property
6. See the target instance pointing to the host instance on the audio links

### Potential Solutions i can think of:

1. Allow to add audio chapters when adding a file on a media field.
2. Treat as special case on sync and change the original url to the target url (this one will make sync more complicated and less generic, not sure its a good idea)

In any case, nothing prevents the user of doing this (even with the solutions proposed above) and it will probably work in case the host instance is not private, should we prevent it somehow ?

**Comment by RafaPolit** [comment]
We could treat the URL of attachments, when it is pointing to the local domain, as a relative URL.  So, if the resource URL was `mydomain.com/file/akldsjfaldskj` we can make it `/file/akldsjfaldskj` and, when this syncs, it will still be a "relative" URL pointing to the synced file on the child instance.

**Comment by RafaPolit** [comment]
Another approach is: we do nothing with the URLs, this could happen also to private Facebook photos, or links to YouTube videos on private channels.  What we need to fix is the support for chapter creation on Supporting Files and using Media pointing to THOSE supporting files instead of absolute paths.

**Comment by daneryl** [comment]
> We could treat the URL of attachments, when it is pointing to the local domain, as a relative URL. So, if the resource URL was `mydomain.com/file/akldsjfaldskj` we can make it `/file/akldsjfaldskj` and, when this syncs, it will still be a "relative" URL pointing to the synced file on the child instance.

I think this one might make more sense now that there is a different case, a partner used csv import to add media files (images) to entities by linking to the absolute url of the attachment, as far as i know there is no option to add images in any other way using csv import, this results in the same scenario after a sync, images pointing to the original host.

**Comment by elreplicante** [comment]
Closing in favour of #4747
