### ISSUE TITLE
Specific configuration on a remote form in settings causes an infinite loop ?

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5171]
**Describe the bug**
A page with a remote public form causes a local infinite loop when the instance has no public endpoints configured.

**To Reproduce**
1. Set up a blank state instance
2. Create a page with a public form using the default blank state template ```<PublicForm template="5bfbb1a0471dd0fc16ada146" remote />```
3. Navigate to the page
4. See infinite loop throwing errors

**Expected behavior**
Not sure about this, should maybe the public form catch somehow the error and not render itself showing a nice message informing the user that this needs extra config in Settings -> Collection -> Public endpoints ?

**Comment by txau** [comment]
In this case the instances was duplicated, to it had the previous configuration but with a new instance name. So:
"Instance A" had the same configuration as "Instance B", meaning that at the moment of duplication "Instance B" was pointing as the URL for the public form end-point to "Instance A". In case this helps.

**Comment by daneryl** [comment]
> In this case the instances was duplicated, to it had the previous configuration but with a new instance name. So: "Instance A" had the same configuration as "Instance B", meaning that at the moment of duplication "Instance B" was pointing as the URL for the public form end-point to "Instance A". In case this helps.

This is true but i have not been able to replicate based on this, maybe our cloning script does not copy the settings ?
Only happening when public endpoints is not configured and a public *remote* form is created in a page.
