### ISSUE TITLE
Error when deleting an empty thesauri value

### ISSUE THREAD

**Issue by grafitto** [huridocs/uwazidocs#5172]
**Describe the bug**
An error is thrown when you delete the last (empty) thesauri value in settings.

**To Reproduce**
1. Go to Settings
2. Create a new thesauri
3. Add a group and values value
4. Delete the last empty value field that appears outside the group
5. See error in developer tools control

**Expected behavior**
Idealy nothing should happen. Should the delete button even the there?

**Screenshots**
![image](https://user-images.githubusercontent.com/8601175/194248728-bfee2172-126a-4387-8ab8-8b40b6e69cd2.png)

![image](https://user-images.githubusercontent.com/8601175/194248319-9503dd78-dd16-48d4-b2bb-bb0c4c7aaf26.png)

**Device (please select all that apply)**
 - [x] Desktop
 - [x] Mobile

**Browser**
All

**Comment by RafaPolit** [comment]
Good report! The key here is to be "the last non-group item".

**Comment by enigmatic-bacon** [comment]
Could I be assigned to this bug? I've submitted a PR. Thanks!
