### ISSUE TITLE
Missing/broken TOC breaks client app

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#5177]
**Describe the bug**
A JS error leaves the screen blank when there is a problem with the table of contents.

EDIT: Same/related? #5142 

**To Reproduce**
1. Go to https://summa.cejil.org/en/library/?q=(_types:!(%2758b2f3a35d59f31e1345b4ac%27,%2758b2f3a35d59f31e1345b471%27,%2758b2f3a35d59f31e1345b482%27,%2758b2f3a35d59f31e1345b479%27,%275a4d294c79f3f44b101e2816%27,%2759ee427f40f4a54920bd9b67%27,%2759ee461f40f4a54920bd9b87%27),filters:(),order:desc,sort:metadata.fecha,types:!(%2758b2f3a35d59f31e1345b4ac%27,%2758b2f3a35d59f31e1345b471%27,%2758b2f3a35d59f31e1345b482%27,%2758b2f3a35d59f31e1345b479%27,%275a4d294c79f3f44b101e2816%27,%2759ee427f40f4a54920bd9b67%27,%2759ee461f40f4a54920bd9b87%27))
2. Locate the document with the title "Profesores de chañaral y otras municipalidades. Sentencia de 27 de Julio de 2022"
3. When opened in the side panel the application hangs

More over, trying to navigate to that entity tosses a server 500.

![image](https://user-images.githubusercontent.com/489831/194379142-28f24694-f438-4b05-8785-60fda276194b.png)

**Expected behavior**
The component should be resilient to problems with the TOC structure. This is not about fixing the content with a data migration but about making code that doesn't break when there is a wrong data structure.

**Comment by konzz** [comment]
Fixed by #5142
