### ISSUE TITLE
SEO/Accessibility tweaks

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#5180]
**Is your feature request related to a problem? Please describe.**
Navigating Uwazi with a text only browser (such as CLI links2 browser) reveals a serie of accessibility problems that also have a great impact on SEO, particularly when it comes to content discoverability.

**Describe the solution you'd like**
The server side rendering of some of  our components need to be tweaked so it tosses valid, semantic html.

1. Language navigation
![image](https://user-images.githubusercontent.com/489831/194386399-ed1aada2-da66-4a6d-9fe0-7d0b9dc93157.png)

problem: The language selector is rendered as a text input that doesn't allow proper language selection.
solution: A proper list with links to the languages should be rendered instead, with spacing between the elements. Ideally we also have some title along the lines of "Select your language". It should be enclosed in a <nav> tag.

2. Sorting
![image](https://user-images.githubusercontent.com/489831/194386891-4cef43d8-f58f-4504-8178-000ab541fefc.png)

Same problem/solution as language navigation.

3. Filters
![image](https://user-images.githubusercontent.com/489831/194387479-5362fd02-f71a-4888-984f-d5d9efb94180.png)

problem: filters are rendered with the number of hits glued to the item.
solution: the number of hits needs to be rendered with spacing from the item title. Desirable to have them enclosed in parentheses. It should be enclosed in a <nav> tag.

problem: the options are not a clickable link, hindering content discoverability
solution: regardless of the full fledged web app rendering and interaction, the options should be rendered as a link

problem: "X more" link is not unfoldable. Many options are not reachable
solution: a good enough solution, at least for discoverability, would be not collapsing the options and always printing the whole list

4. Broken view link
![image](https://user-images.githubusercontent.com/489831/194391854-ef4c9fb2-a2de-43a7-8ca2-37bc36e2282a.png)

problem: there is a permanent "View" button at the bottom of the filters that points to /undefined target.
solution: this button probably should be rendered on server side or it should be a button instead of a link since its target depends on what users select in the card list, which is not doable in text mode

5. Relationships link:
![image](https://user-images.githubusercontent.com/489831/194392755-0af97b54-6ab2-4788-b185-1c08bc9584c3.png)

problem: relationships section is not accessible via URL. it is rendered with the amount glued to the title and it is not a link (in the image 17Relationships
solution: convert it into a clickable link. This has the added difficulty of needing a way to navigate directly to the relationships section via the URL, which is not doable at the moment

6. Relationships filter menu
![image](https://user-images.githubusercontent.com/489831/194393331-2595fc77-0625-4cd8-966e-a7b07175f628.png)

Same problem/solution as filters

7. Table view
![image](https://user-images.githubusercontent.com/489831/194393495-f7bdbef6-abe6-4af9-8471-31236002ae29.png)

problem: table view section doesn't render anything. 
solution: making sure table view has a server side rendering option for text mode

8. Improve card semantics
![image](https://user-images.githubusercontent.com/489831/194394964-76dbc4c2-8b05-49ef-a269-9356f88a262d.png)

The whole card should be enclosed within an <article> tag. 
Item name should be a h2 or h3 tag.
Definition lists (<dl>) are ok but we are not printing the <dt> when "Hide label" is configured. This is wrong, it should be printed with some html class that hides it via CSS or even JS but it always gets rendered in text mode. Also we are declaring multiple <dl>, one per metadata item, when all the metadata should be enclosed in the same dl:
<dl>
  <dt> property name 1</dt>
  <dd> metadata value 1</dd>
  <dt> property name 2</dt>
  <dd> metadata value 2</dd>
  ...
</dl>

**Comment by RafaPolit** [comment]
Each "group" of items is a MEDIUM sized issue.  So items 1 & 2 are MEDIUM, items 3 & 6 are MEDIUM, etc.

**Comment by konzz** [comment]
Extracted to issues:
-  #5196
-  #5197 
-  #5198 
-  #5199 
-  #5200 
-  #5201
