### ISSUE TITLE
Admin dashboard

### ISSUE THREAD

**Issue by elreplicante** [huridocs/uwazidocs#5194]
**Is your feature request related to a problem? Please describe.**
Provide some visibility about tenant statistics to admin users.

**Describe the solution you'd like**
A dashboard section containing basic information:
- Users
- Entities
- Storage (DB + file size + ES index size)
- Files (count of files)

No information related to subscriptions or activated external services will be added at the moment.

**Additional context**
[Figma design](https://www.figma.com/file/kpGAA005yHdL6Ch1rncaB2/SaaS-Improvements?node-id=1%3A987)

**Comment by Zasa-san** [comment]
Since there's a few problems correctly calculating the total available storage in some cases, the dashboard will just display the sum of used storage from files, elastic and mongo, for the time being.
