### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by enrroquez** [huridocs/uwazidocs#5216]
Hi dear Uwazi dev community. I don't know where is the right place to ask the following question.
What are the hardware requirements for an Uwazi production server?
Sorry if I missed this information, in case it is already published.
Thanks in advance.
Enrique

**Comment by txau** [comment]
Hi @enrroquez this is the right place to ask. The hardware requirements may depend on the volume and nature of information you plan to host:
- For big files with a small database footprint (such as video, audio and images) you'll need more HD space than CPU or RAM
- For text documents you should consider some decent RAM as ElasticSearch is pretty greedy on memory for full text search

The bare minimum you need to be able to run Uwazi without bottlenecks is:
- 4 GB of RAM (reserve 2 for Elastic and 2 for everything else)
- 2 CPU cores
- 20 GB of disk space

I hope this helps!

**Comment by RafaPolit** [comment]
Closing in favor of #5305
