### ISSUE TITLE
7or platform is not loading

### ISSUE THREAD

**Issue by AhmadQadi1** [huridocs/uwazidocs#5243]
**Describe the bug**
7or.7amleh.org website is not working and the screen is frozen the page doesn't load.

**To Reproduce**
1. Go to '7or.7amleh.org'
2. Click on 'Submit a report'

**Expected behavior**
When I click submit a report it should work and when I scroll down I should see charts.

**Screenshots**

**Device (please select all that apply)**
 - [ ] Desktop
 - [ ] Mobile

**Browser**
What browser where you using (Firefox, Chrome, Safari, etc...).

**Additional context**
![Untitled](https://user-images.githubusercontent.com/95572565/197395764-c8f06afc-b820-4946-8658-710ce6fc6a8b.png)

**Comment by mennaelmassry** [comment]
@nwyu @RafaPolit @MatelSow 

![image](https://user-images.githubusercontent.com/75305030/197403294-3fa0236d-445a-4400-9986-2b5c60c88cb6.png)

**Comment by nwyu** [comment]
@AhmadQadi1 @mennaelmassry Thanks for your report. I saw it, as well, on both English and Arabic, however queries and all forms appear to load now from my side. Please check and confirm it from your end.

**Comment by AhmadQadi1** [comment]
Hello Nancy, it still does not work!

**Comment by elreplicante** [comment]
@AhmadQadi1 @nwyu The root cause was a disruption in our systems.  It should be working now.

**Comment by mennaelmassry** [comment]
@nwyu it is working on my side (screenshot below) 
@AhmadQadi1 Would you close your browser and re-open it again or restart your computer and let us know... 

![image](https://user-images.githubusercontent.com/75305030/197515863-eff8dfb8-57c7-47f3-be58-46696d85be10.png)

**Comment by AhmadQadi1** [comment]
Thank you, it's up again!
