### ISSUE TITLE
Supporting files and main document icons are completely wrong

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#5267]
**Describe the bug**
- The button next to the attachment is a "pencil" (which is EDIT), it should be an "ellipsis" (...), because it opens a secondary modal
- On the modal, the "download" button should, actually, be a download icon
- The "rename" should probably NOT be a pencil, as that is edit, but that is a bit more difficult to decide.

**Comment by mfacar** [comment]
For the action rename, we are using the icon "Font" which is the same one used in TOC
cc. @juanmnl
