### ISSUE TITLE
Global Javascript as we have Global CSS (like per-page Javascript)

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#5268]
**Is your feature request related to a problem? Please describe.**
If several pages require a library, the loading of the library needs to be loaded in each page, which could be avoided.  Also, for full customization, there are places where CSS is not enough and having a global Javscript that resides on the DOM for the duration of your navigation, could prove useful (the actual implementation of how to detect navigation and stuff like that is not the responsibility of this feature).

**Describe the solution you'd like**
Have a Global Javascript section, like we have the Global CSS.  It has been discussed that, since this could create a security problem if people don't know what they are doing, this will be a toggle on-off feature that users need to EXPLICITLY enable, so that they understand the risks if they paste here external code.  

Obviously, the actual usage of this page will vary according to scenarios and there should be care to include functions that trigger only once certain conditions have met.  Also, code developers for this should be careful to prevent memory issues, multiple loads of libraries, careful DOM manipulation not to break our React app, etc.  This is a potentially great feature that used wrong could cause a lot of problems.

**Comment by juanmnl** [comment]
We are going to add a toggle to the collection settings that will allow admins to enable global javascript to be added to an instance.

![Image](https://user-images.githubusercontent.com/699945/200588640-8f20b9c2-43d1-4a3a-b839-0b02beee5909.png)

The (i) icon should display the same warning message we use in "pages javascript" but in a tooltip.

"With great power comes great responsibility!

This area allows you to append custom Javascript to the entire application. This opens up a new universe of possibilities.
It could also very easily break the app. Only write code here if you know exactly what you are doing."

---

When the toggle gets activated by the admin on the collection settings, the nav menu and section title will change names, from "Global CSS" to "Global CSS & JS", while at the same time showing a second tab on that view to allow the input of JS code.

Custom JS disabled:
- "Global CSS"
- Hidden js input tab


![Image](https://user-images.githubusercontent.com/699945/200590087-d22f6034-0746-480f-bc33-9146b85a1fc0.png)
![Image](https://user-images.githubusercontent.com/699945/200590132-0fcf66bf-974b-41ec-9a14-e32ef347edd8.png)


Custom JS enabled:
- "Global CSS & JS"
- Display js input tab


![Image](https://user-images.githubusercontent.com/699945/200589925-d471df08-11db-4588-b450-18779f933bab.png)
![Image](https://user-images.githubusercontent.com/699945/200590006-3aae9bde-af63-4eaf-940d-db19ba099520.png)
