### ISSUE TITLE
Entities bulk delete can cause inconsistent elastic index

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5272]
**Describe the bug**
When deleting entities in bulk, any error will stop the process, deleting only the entities previous to the error but removing all entities that were supposed to be deleted from elastic index, we fixed one of this errors here https://github.com/huridocs/uwazi/issues/5270 but this can still happen on any other error.

**To Reproduce**
1. Prepare a blank state uwazi
2. Create 3 entities
3. force an error on the entity 2 modifying the code manually
4. bulk delete the 3 entities
5. See error notification, looks like entities have been deleted
6. Run a reindex
7. See entities reapear !

**Expected behavior**
Not sure, options
- when an error occurs, reindex all remaining entities back.
- make the bulk deletion somehow transactional and reindex all back when the error happens.

**Comment by iJustErikk** [comment]
I will take this up :)

**Comment by txau** [comment]
@daneryl @iJustErikk do we know what kind of errors can prevent the deletion? 

Ie. If the connection with the database is lost, reindexing the entities back could work since users can re-try the deletion which will pass when the connection to the DB is available again.

Whereas if there is a persistent problem, the users will face the same problem when they try to delete again.

**Comment by iJustErikk** [comment]
Hi all, sorry about the delay.

@txau I think the reindexing is error-prone. Perhaps we could wrap the mongodb deletes in a transaction and only commitTransaction when we know the elasticsearch delete went through. This would be less error prone. There might be a small chance that the elasticsearch bulk delete goes through, but for some reason mongodb fails to commit the transaction it started. I am new to this project, so I am not sure how reasonable this is (or how one could go about repairing it). I am not sure how meaningful rolling back or showing this to the user at this point would be. I think the most reasonable thing would be is add a retry mechanism for either request and report on the error to the user.

@daneryl Could you elaborate on what you mean by "force an error on the entity 2 modifying the code manually"?

**Comment by txau** [comment]
@iJustErikk to be honest I think @fnocetti is already working on this from another perspective.

**Comment by fnocetti** [comment]
Hi @iJustErikk , thank you for taking the time to contribute and share your thoughts!
As @txau said, we are thinking on fixing this kind of issues from the bigger picture and, same as you, we have thought of transactions (together with other techniques) as the tool to use on several problems such as this one. The reality is that we have tried to implement transactions a couple times in the past and it both gets really complicated and pollutes the code to an extreme level. Particularly for entity operations, the transaction scope involves, at least, relationships and files operations as well.
So while we want transactions, other efforts are in process to support them better in the architecture. Until that's finished I would suggest not trying to use them.

Nonetheless, after checking the code I see a different possible approach.
From this snippet https://github.com/huridocs/uwazi/blob/77db5a5add351ccf0015e772b6614847d6764937/app/api/entities/entities.js#L669-L676 we can see that the current flow for this bulk operation is:
- Delete the entities from elastic in batches
- Delete the entities one-by-one

We could, and probably should, change the approach so we
- Delete the entities one by one, keeping in memory the ids of the entities that were deleted.
- Delete from elasticsearch based on the ids we kept.

This implies that the entity deletion of the first step is guarded by a try-catch-finally so upon error, we can first remove from elastic the entities we know were successfully deleted from mongo, and then re-throw/forward the error that we caught from the last entity we tried to delete.

In pseudo-code, something like:
```
let deleted = [];
try {
  deleteSeriallyWhilePushingIdsToDeleted();
} catch (e) {
  log(e); // this is necessary because if the finally block throws then e won't be forwarded.
  throw e;
} finally {
  deleteFromElastic(deleted);
}
```

@txau @daneryl @LaszloKecskes what do you think? Do you think it's worth it?

**Comment by LaszloKecskes** [comment]
After the discussion in a call with @fnocetti, I agree. This is the most simple solution for now, and we will add transactions when we get to the entity structure revamps in v2.
