### ISSUE TITLE
CSV file is messed

### ISSUE THREAD

**Issue by AhmadQadi1** [huridocs/uwazidocs#5280]
**Describe the bug**
The exported CSV files don't reflect the real structure and data. The values overlap, for example, some dates values in the CSV files appear in other fields though in the database they are in the right fields.

**To Reproduce**
1. Go to 'UWAZI'
2. Click on 'export'
3. Scroll down to 'CSV'
4. See error (check attachment)

**Expected behavior**
Each column should contain values as they are in the database. But they overlap 
![2](https://user-images.githubusercontent.com/95572565/199464641-bfe9fd57-692c-425a-9c3b-1af1bf023751.png)
![Untitled](https://user-images.githubusercontent.com/95572565/199464644-35e2e2e5-c4c9-4cf2-926f-abc1afc7ef19.png)

**Screenshots**

**Device (please select all that apply)**
 - [ ] Desktop
 - [ ] Mobile

**Browser**
What browser where you using (Firefox, Chrome, Safari, etc...).

**Additional context**

**Comment by RafaPolit** [comment]
Without looking at the actual CSV, it looks like this may be a "parsing" or conversion error when importing into excel.  Have you tried in excel "ticking" some different checkboxes in the import dialog?  There should be options on how to treat empty values, escape characters, things like that.  Also, it's important to set the charset to UTF-8.

If this doesn't yield the expected results, can you please share the exported CSV (not the imported excel sheet) with your PM please?  

Thanks.

**Comment by RafaPolit** [comment]
If you have further information, please feel free to reopen the issue.
