### ISSUE TITLE
Modify the email address where uwazi alerts are sent from to no-reply@uwazi.io [Estimated]

### ISSUE THREAD

**Issue by vostorga** [huridocs/uwazidocs#5311]
Currently Uwazi alerts are being sent from [uwazi@production-backends-1.huridata.org](mailto:uwazi@production-backends-1.huridata.org)  as can be appreciated in the below picture:<br>
![image](https://user-images.githubusercontent.com/56080527/180440420-ed4abcc8-effb-4c3e-a44e-7438a45d3f49.png)

Emails from this address are usually sent to "Junk email". <br>

In a short discussion with @nwyu , she mentioned emails were sent in the past from [no-reply@uwazi.io](mailto:no-reply@uwazi.io) which matches the project name Uwaz" and would help emails to be delivered to inbox.

**Comment by txau** [comment]
This address should be configured as a server configuration. Self-hosted Uwazis don't want to send the email from that address.

**Comment by vostorga** [comment]
After investigating, Uwazi  depends completely on the operative system to send emails. <br>
I've changed the sending domain from huridata.org to uwazi.io . <br><br>
Now the sending address is uwazi@uwazi.io . <br>
It cannot be changed to no-reply@uwazi.io as the operative system relies on the OS process Uwazi is running under , which is named "uwazi".  It is always possible to override the uwazi part to no-reply from the programming language itself.
