### ISSUE TITLE
UWAZI from 2 instances got some error

### ISSUE THREAD

**Issue by bankmrc054** [huridocs/uwazidocs#5323]
I have migrated UWAZI from 2 instances = Frontend port: 3001 and  Backend port: 3000  

The issue is: I can see the UWAZI login page ( Backend port: 3000  ) but I can not see the front-end page (Backend port: 3000  )  Please see the error attached.

If anyone can help to find the trick. I have to very please thank you !!!

[error.txt](https://github.com/huridocs/uwazi/files/10019206/error.txt)
![uwazi01](https://user-images.githubusercontent.com/66657432/202118434-d6f10b06-f0a5-4cc3-968d-b18fe898fe80.jpg)
![uwazi02](https://user-images.githubusercontent.com/66657432/202118447-4126cd9b-0acd-4bc6-985c-def48735e4b5.jpg)

**Comment by txau** [comment]
@bankmrc054 fixed?
