### ISSUE TITLE
Relationship tree rendering wrongly for document view

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#5336]
**Describe the bug**
As seen in the image, the search box, sorting etc appears aligned to the left instead of to the center along with the rest of the information. This only happens for the relationship tree for the document viewer, for entity viewer it renders in the right place.

![image](https://user-images.githubusercontent.com/489831/202562355-447d0a3d-5c8e-4d8d-895c-a8a18a0fdf0c.png)

**Comment by daneryl** [comment]
Can we add a visual regression testing for this section when we fix this ?

**Comment by Zasa-san** [comment]
Check when/how is this happening, what browser and OS, since it cannot be reproduced right now. Check with @juanmnl

**Comment by txau** [comment]
@Zasa-san so far I have been only able to reproduce on SUMMA (https://summa.cejil.org/en/entity/4raiibpab07wrk9/relationships) , while logged in with Firefox on linux.

**Comment by nwyu** [comment]
Not reproducible
