### ISSUE TITLE
Support simple inheritance in relationships v2

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#5342]
This issue is part of the effort to make the new relationships v2 support the same use cases as current relationships. This issue targets supporting simple (one-property) inheritance, based on the resulting leaf entities from a graph query.

- [x]  perform query on 'get' (update entityMapper in entityDS)
- [x] update the optimized denormalization script
- [ ] handle the elastic search mapping in order to support filters
- [ ] manual testing

**Comment by LaszloKecskes** [comment]
@fnocetti Just a heads up, I've edited your placeholder description.
