### ISSUE TITLE
Add support to Google Analytics 4 and Google Tag Manager

### ISSUE THREAD

**Issue by roirobo** [huridocs/uwazidocs#5356]
**Is your feature request related to a problem? Please describe.**
Currently, Uwazi only supports standard Google Universal Analytics properties, which is being deprecated and will no longer process data by July 1, 2023 (October 1, 2023 for Analytics 360 properties). This property will be replaced with Google Analytics 4 (GA4), introduced in October 2020.

As a partner, I would like to be able to track the end-user journeys and collect event-based data from all the apps and websites I offer, including my Uwazi instance.

**Describe the solution you'd like**
Adding support for Google Analytics 4 and other SEO tools like Google Tag Manager, will ease partners to track how people use their instances, as well as marketing channels funnels where they promote it.

**Have you considered an alternative?**
Matomo also offers a Tag Management System, which could be an alternative for partners that want to protect their data and users' privacy.

**Additional context**
his issue is related -but not exclusive- to a specific request from a partner that is using Google Analytics 4 and Google Tag Manager for their digital marketing strategy.

**Comment by konzz** [comment]
After some testing, Uwazi currently supports GA4 already
