### ISSUE TITLE
CSV date import succeeds, but displays null

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#5366]
A specific instance has two languages, English and Korean. A date is imported from a csv. In English, the imported date displays correctly, in Korean it displays "invalid date", both in the side panel and full entity view. The data arriving from the backend is also wrong, having a null value in Korean, therefore this is most likely a backend issue.

The tasks for this issue are:
1. Debug the specific example to figure out the exact point of failure (is it the csv import? or the entity get endpoint?, etc.). Connect hyebin.bina for the full details.
2. Reproduce the issue outside of context.
3. Smoke test.
4. Implement solution.
5. Write a short retrospective about what the error was and how did we miss it, if applicable.

**Comment by hyebin-bina** [comment]
cc: @natasha-todi 

Hello, I have tried to solve this issue from my end and witnessed an interesting behavior. 

I was able to import the date property in both languages (Korean and English) when I changed the date format from MM-DD-YYYY **to YYYY-MM-DD**, even though the collection's default date format remained as MM-DD-YYYY. 

To replicate the issue: 
1. Keep the collection's default date format as MM-DD-YYYY and import the date property following the default format. 

<img width="275" alt="Screen Shot 2022-12-08 at 9 55 09 PM" src="https://user-images.githubusercontent.com/85096417/206452930-a7209c30-3239-45c8-a6bf-0ee17c9ddc01.png">
<img width="455" alt="Screen Shot 2022-12-08 at 9 55 42 PM" src="https://user-images.githubusercontent.com/85096417/206452945-f6a86e8f-abf2-4c11-90b3-9c8e3e7cb042.png">

2. Go to the library and check the imported entity in two languages. In English setting, the entity was imported with the correct date. However, in Korean, the date property is imported as "Invalid value."

<img width="356" alt="Screen Shot 2022-12-08 at 9 55 50 PM" src="https://user-images.githubusercontent.com/85096417/206453322-d87176eb-387c-47c3-b769-ee54e21ee006.png">
<img width="353" alt="Screen Shot 2022-12-08 at 9 56 00 PM" src="https://user-images.githubusercontent.com/85096417/206453327-21e0d713-f6bf-4c12-81c2-56746c0ecd15.png">

3. Further, when changing the date format to YYYY-MM-DD from the original CSV file, while the collection default date format being remained as MM-DD-YYYY, the date property gets imported correctly in both languages.

**Comment by hyebin-bina** [comment]
cc: @RafaPolit 

Following our discussion, I am attaching the original CSV file so that you can recreate the issue when needed. 
The first file (Test_MM-DD-YYYY) is the one that threw error, and the second file (Test_YYYY-MM-DD) is the one that somehow worked. 

Let me know if you need any clarification!

[Error_MM-DD-YYYY.csv](https://github.com/huridocs/uwazi/files/10225031/Error_MM-DD-YYYY.csv)
[Workaround_YYYY-MM-DD.csv](https://github.com/huridocs/uwazi/files/10225032/Workaround_YYYY-MM-DD.csv)

**Comment by LaszloKecskes** [comment]
As per discussion within the tech team, this issue is resolved via #5644. Currently, date properties do not support importing in multiple languages. If one attempts to import a date property with the language syntax (i.e. some_date__ko), the csv import will throw an error telling the user to remove that column, and include only the language-less version. Therefore, the situation in the issue is no longer applicable.

@hyebin-bina If there are still problems with date csv imports, that is most likely different from this one, please open a separate issue.
