### ISSUE TITLE
Visual bugs in entity view and sidepanel

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#5367]
**Describe the bug**
There's some problems with the sidepanel view and entity view.

On the sidepanel text seems bunched up together, laking some vertical spacing, and geolocation properties have a red background color (this is seen on demo).
On the entity view the width for the container is restricted and not taking the whole space.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/71732018/204532849-7784e8cc-f98a-4011-8915-eeda32b13659.png)

![imagen](https://user-images.githubusercontent.com/71732018/204533078-1b61ce3d-cf4b-4bc7-baea-c8b768d3c2f9.png)

**Device (please select all that apply)**
 - [x] Desktop
 - [x] Mobile

**Browser**
Firefox

**Additional context**
Check mobile view and entity view for entities with and without primary documents.

**Comment by Zasa-san** [comment]
@juanmnl the coloring in geolocation properties is related to the color of the template. When the map is displaying related entities then it takes the color of the related template. Do we want to keep this? 

EDIT:
I've applied a fix to make them look as they where previously:
![image](https://user-images.githubusercontent.com/71732018/204613979-0a360b28-aa84-4096-8901-ec718aea6070.png)

**Comment by juanmnl** [comment]
@Zasa-san Looks good, let's keep 'em as they were previously.
