### ISSUE TITLE
Translations import is broken

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5370]
**Describe the bug**
Import translations via csv results in "unexpected field" error

**To Reproduce**
1. Go to Settings -> Translations -> any Uwazi UI
2. Import a valid csv
3. See "Unexpected field" error

**Expected behavior**
Should work

**Additional context**
https://github.com/huridocs/uwazi/pull/5121 we think the offending change is the rewrite of EditTranslationForm.js

**Comment by Zasa-san** [comment]
This error was caused by wrongly passed parameters to the function handling the csv upload. I'll also add some tests to cover this flow since there are none.
