### ISSUE TITLE
IX Selection boxes not matching [Timebox 1day]

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5376]
**Describe the bug**
When looking at a document that contains selection rectangles for suggestions, the selection rectangle is not rendered where it should.

@gabriel-piles could you add an screenshot to show the issue?

**Comment by gabriel-piles** [comment]
It seems to happen that when you label a document using the the metadata extraction UI, the next document you open in the same UI has wrong colored boxes.

![Screenshot-20221205101434-1133x692](https://user-images.githubusercontent.com/22240564/205599180-8decb602-81ae-43d6-a2c1-18b1e65132d5.png)

**Comment by grafitto** [comment]
Done a bit of investigation, it seems the selections remain the same when documents change. For example, if you view PDF A, it loads its selections, then when you close and load PDF B, the selections for PDF A render, and selections for PDF B do not. That continues even when you load PDF C and so on. Its possible that the old selections are not removed and replaced with the new ones from the currently loaded document.

**Comment by grafitto** [comment]
This was fixed in #5386
