### ISSUE TITLE
Click to fill for dates in Spanish is not working properly

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5379]
**Describe the bug**
When you try to use the "Click to fill" functionality to grab a date from a document in Spanish it throws an error with invalid value.
Ask @gabriel-piles for an example PDF. 

 - Also check other languages ? 

![fill](https://user-images.githubusercontent.com/948117/205308518-0c7f5a1a-7975-49c5-afd3-763a522829e6.png)

**Comment by gabriel-piles** [comment]
Examples:

Document in Spanish:
* "1 de septembre de 2001" gives an error
https://summa.cejil.org/es/entity/0vguj40iznrbpgb9?searchTerm=Sentencia%20de%201%20de%20septiembre%20de%202001

Document in Portuguese:
* "10 de outubro de 2001" gives an error
https://summa.cejil.org/pt/entity/1poeger9tryq4cxr?searchTerm=79%2F01
