### ISSUE TITLE
IX Pop up Improvements

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5380]
During the IX we discuss some improvements changes to the IX configuration pop up.

Designs needed: @juanmnl

**Comment by juanmnl** [comment]
We need to add and modify a few things here:

**On the main dashboard**

1. We'll move the "add property" action to the "action bar" on the bottom, as everything else on the app (rename it to "create extractor".
<img width="1091" alt="Screenshot 2022-12-19 at 10 18 17" src="https://user-images.githubusercontent.com/699945/208459135-e110ef5c-7ef1-4f7b-ad44-fe1fc1aae75a.png">

2. Add a selection checkbox to each row of the table and an "extractor name" column too.
<img width="882" alt="Screenshot 2022-12-19 at 10 17 22" src="https://user-images.githubusercontent.com/699945/208459396-969159cb-91de-4130-9e99-297475e6d0ee.png">

**On the modal**

1. Add an input that allows user to custom name the extractor they're creating.
<img width="594" alt="Screenshot 2022-12-19 at 10 22 20" src="https://user-images.githubusercontent.com/699945/208459835-50060c76-aa42-490f-880d-bf166a579355.png">

2. We remove the ability for users to select a whole template.
3. Once a template's property is selected by the user, the template's list filters down to templates that contain only that same property.
<img width="585" alt="Screenshot 2022-12-19 at 10 25 11" src="https://user-images.githubusercontent.com/699945/208460330-46bf063c-0227-4e84-941c-a5c829b6f2f5.png">

4. Add a global checkbox ("from all templates") that allow the user to select all of the available templates that have that same property on a single click.

**Comment by juanmnl** [comment]
When the user selects an extractor, the bottom action bar show edit (and potentially a delete) button.
The edit will trigger the pop up menu with the current configuration of the extractor.
<img width="794" alt="Screenshot 2023-01-03 at 09 25 05" src="https://user-images.githubusercontent.com/699945/210376391-6fe20ca8-9be9-4a4d-8189-8d5960391dd7.png">
