### ISSUE TITLE
IX Separate states and show agregations like in the library table view

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5381]
Right now the filter by state of the suggestions is a select that has some combinations of states. We want to separate the states individually and show aggregations using the same approach as in the library table view. Also fix the width of the table not using the 100%.

**Comment by konzz** [comment]
@juanmnl

**Comment by juanmnl** [comment]
We'll add a button to the top of the page (like in library table view) that will allow the users to open the side panel filters.
<img width="998" alt="Screenshot 2023-01-03 at 09 45 34" src="https://user-images.githubusercontent.com/699945/210380258-1f0e286f-e0bb-4e26-a081-40209fa6753c.png">

Then just like the library, we'll show the available filters for the users to interact with (starting with statuses and potentially adding templates whenever the extractor has multiple templates)
<img width="988" alt="Screenshot 2023-01-03 at 09 45 51" src="https://user-images.githubusercontent.com/699945/210380408-5626d19e-820d-4a9f-91cb-54ef2e8b7f20.png">

**Comment by txau** [comment]
Just a quick note on the design. Because previously we need to enforce some economy of real state on the screen the state descriptions were reduced to the minimum. With this design maybe we could change the wording to more descriptive categories? I could prepare the list @konzz @juanmnl
