### ISSUE TITLE
Client legacy uploads route still exists

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5385]
Is this route used in any way ?

**Comment by RafaPolit** [comment]
Maybe this is being removed as part of the React Router 4 migration? cc @Zasa-san @mfacar

**Comment by Zasa-san** [comment]
The route will no longer be available after the upgrade. The files that the route used will not be removed in that PR, as the amount of changes is already very large and some of the modules exported there are used in other places in the app.

**Comment by konzz** [comment]
@Zasa-san can you tell me if this is still an issue?

**Comment by Zasa-san** [comment]
> @Zasa-san can you tell me if this is still an issue?

The route no longer exists, but files in `app/react/Uploads` are not deleted since they have functionality that is still used by the library. I think it's ok to close this issue.
