### ISSUE TITLE
install.sh not present in latest release and other installation snags

### ISSUE THREAD

**Issue by katelynsills** [huridocs/uwazidocs#5388]
Hi! First, thanks so much for making Uwazi! 

I recently followed the [production installation instructions](https://github.com/huridocs/uwazi#production) and ran into a few snags. For example, in the latest release, there is no install.sh present in the root folder, so I had to steal it from the git repo. Another was that `scripts-prepend-node-path` no longer appears to be a valid setting in npm. 

What would be the best way for me to pass on information like this? I didn't want to spam your Bug Report Issues, but would it be helpful if I created an issue for each problem I ran into? Or should it be just one issue with a checklist of problems? 

Thanks again!

**Comment by RafaPolit** [comment]
Thanks very much for this report.  Indeed, some of our instructions can get obsolete with time. We try to keep them up to date, but this is an area that certainly needs attention.

Also, this is the place to report such things.  We usually tag as Bugs that which is features of the app which are not behaving as expected.  Installation and documentation issues usually fall under the tech-debt category, but there are some grey areas where a documentation error could be considered a bug, like running a script of a file that doesn't exist on the build.

It's up to you if you prefer to create a single issue where you describe all your findings (recommended if most are found on the same file or section or pertain to the same subject), or you can create separate issues for each problem as you encounter them. 
 That would make them easier to define, easier to be assessed by the team and faster to fix.

Bottomline, whatever solution is best for you, is OK with us.   We thank you very much for the time to write these issues and the support for our platform.

ps. Sorry for taking so long to reply, it's not usually the case but we are a bit overstretched with end-of-year craziness.

**Comment by katelynsills** [comment]
Thank you, @RafaPolit! I've started with [an issue here](https://github.com/huridocs/uwazi/issues/5406), and will continue to add more.

**Comment by RafaPolit** [comment]
Closing in favor of #5406
