### ISSUE TITLE
New entity side panel behaves inconsistently.

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#5389]
**Describe the bug**
Following https://github.com/huridocs/uwazi/issues/5363 there are inconsistencies with the behavior of the side panel when creating a new entity.

If an entity is selected, and the user is on the relationships tab on the side panel, creating a new entity renders an empty side panel. This is because the new entity side panel is still on the relationships tab.

This also happens when no entity is selected, there’s a tab for relationships. 

Likewise, selecting entities while the create entity side panel is open causes the relationships count to change, and if the selected entity has a different template than the new one an error is displayed on the template selector.

**To Reproduce**
1. Go to the library
2. Create a new entity
3. Select other entities and play around with the tabs on the side panel

**Expected behavior**
The new entity side-panel should not have tabs at all, what should happen when selecting an entity while creating a new one is unclear. 

**Screenshots**
![image](https://user-images.githubusercontent.com/71732018/206216845-5587c022-3999-4ecc-b2b8-2e52fee2b10f.png)
![image](https://user-images.githubusercontent.com/71732018/206217693-c7934be9-6de2-4918-a8cb-61d1cf09d3b7.png)
![image](https://user-images.githubusercontent.com/71732018/206218582-e56c504d-507e-4b9a-af99-851ae7329c87.png)
![image](https://user-images.githubusercontent.com/71732018/206217325-1a81ca4a-f717-4573-96db-2dadecf7fcfa.png)

**Device (please select all that apply)**
 - Desktop
 - Mobile

**Browser**
Firerox

**Additional context**
It’s likely that editing an entity has the same problems and should be addressed. It’s also important to check what happens when multiselecting, and on the table view.

**Comment by mfacar** [comment]
Probably #5507 also is related to this issue
