### ISSUE TITLE
Export CSV: internal codes in inherited/select properties

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#5405]
**Describe the bug**
Exported entities in CSV files which include inherited properties from a select field, get the internal code but not the value itself.

**To Reproduce**
1. Create a template T1 which includes a select property P1
2. Create a template T2 with a property P2, inherited from T1.P1
3. Add some entities from T1 and T2 templates.
4. Export a CSV file with the entered T2 entities. 
5. Check the P2 column in the CSV file.

**Expected behavior**
For instance, a inherited property named "Country" should send to the CSV file values like "Mexico" or "Corea", and not codes like "282b42cf-b09b-4d2f-b139-08bc4a5874c8".

**Screenshots**
![image](https://user-images.githubusercontent.com/73410334/207689101-bd050199-d922-4c88-974b-dc0bb0fe3186.png)

**Comment by LaszloKecskes** [comment]
According to debugging and @salvalacruz, the behavior is not present anymore.
