### ISSUE TITLE
Group name/label of group thesaurus not showing up within CSV export file

### ISSUE THREAD

**Issue by pddocs** [huridocs/uwazidocs#5423]
**Describe the bug**
Currently, on exporting entities with select type properties linked to group thesauri, the CSV file only carries the the nested value and not the name/label of the group it belongs to. This leaves out key group related information pertaining to that nested value, as well as creates confusion when a nested value appears across different groups in the same thesaurus. 

**To Reproduce**
1. Go to template with at least one property linked to group thesaurus and select all entities. 
2. Click on 'Export CSV' button
3. Scroll to column where property with group thesaurus in the exported CSV file is located
4. See that only nested value is shown without the corresponding group name/label

**Expected behavior**
The exported file carries the nested value with the group label. 

**Device (please select all that apply)**
 - [x] Desktop
 - [x] Mobile

**Browser**
Google

**Additional context**
NA

**Comment by RafaPolit** [comment]
This is not really a bug.  This indeed should be the expected behavior but this has not been introduced for CSV export.  It needs to be implemented.

**Comment by RafaPolit** [comment]
@LaszloKecskes can you please create a separate issue to allow to import nested thesaurus values as well? Thanks.
