### ISSUE TITLE
Entity deletion error (ghost entities) in different scenarios

### ISSUE THREAD

**Issue by hyebin-bina** [huridocs/uwazidocs#5428]
**Describe the bug**
Users encounter ghost entities after entity deletion in different scenarios

**To Reproduce**
Encountered ghost entities in the following two occasions:
1. After bulk-deleting a large dataset (few hundreds to few thousands) that has a relationship property
2. After making a lot of changes in the instance structure (deleting and creating templates / properties) and deleting a small dataset (few dozens) that does not have a relationship property, using the "Select all" button 

**Device (please select all that apply)**
 - Desktop

**Browser**
- Chrome

**Comment by txau** [comment]
@daneryl is this the same as https://github.com/huridocs/uwazi/issues/5272#event-8201685761 ?

**Comment by RafaPolit** [comment]
@daneryl please review if this is the same as the other issue, if yes, please close.

**Comment by daneryl** [comment]
I have no idea if its the same, this was reported more or less at the same time the issue was fixed i think, and it was deployed this past monday, if its the same issue it should not happen again, close and reopen if it happens again ?
