### ISSUE TITLE
Public forms attachments not working on firefox.

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#5433]
**Describe the bug**
On Firefox, attachments or documents dropzone doesn’t open the upload file dialog on click. The dropzone itself works and files can be attached via drag and drop, but when clicking on the zone to open the upload file dialog, it doesn’t. 
In Chrome it works fine.

**To Reproduce**
1. Open Firefox
2. Go to https://demo.uwazi.io/en/page/hevpal3191/submit-a-document or any public form
3. Try to upload a document by clicking on 'Select files on your device'.
4. Nothing happens.

**Expected behavior**
Same as in Chrome, a file dialog should open.

**Device (please select all that apply)**
- Desktop

**Browser**
- Firefox

**Additional context**
This is on a Linux OS. Maybe for Windows or Mac it's different. On mobile Android it works fine in Firefox.

**Comment by Zasa-san** [comment]
This problem is also present in `/settings/custom-uploads`

**Comment by RafaPolit** [comment]
Please fix both issues together.
