### ISSUE TITLE
IX: Rectangles appearing in PDF without labeled data

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#5434]
**Describe the bug**
Rectangles appearing in PDF without labeled data on the Information extraction UI when previously other document was "click to fill"

![Screenshot-20230112155429-884x442](https://user-images.githubusercontent.com/22240564/212099540-27836117-57e7-4b01-a41a-8d2f7d69328c.png)

**Comment by konzz** [comment]
fixed by #5454
