### ISSUE TITLE
IX: Suggestions not marked as "Obsolete" when training new model

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#5451]
**Describe the bug**
Suggestions not marked as Obsolete when training new model

**Comment by txau** [comment]
@gabriel-piles this one has been discussed in the past. The thing is that if for whatever reason the model fails to train, then the old model will remain and the suggestions are not obsolete. So @LaszloKecskes proposed that the suggestions are actually update to "obsolete" after the model has been trained, right before they are all processed. Does it make sense?

**Comment by gabriel-piles** [comment]
@txau It makes sense what @LaszloKecskes proposed. Otherwise, if we want to check the new suggestions while they are coming, there is no way to know if they are not the old ones.

**Comment by txau** [comment]
@gabriel-piles then that must be a bug, because right before they are coming, they are all marked as obsolete.

**Comment by gabriel-piles** [comment]
@txau, @LaszloKecskes  oh, I see. It works well.

One small thing is that the states are not updating to "Obsolete" without a page reload, unlike the "Find suggestions" button that updates itself without a page reload.
