### ISSUE TITLE
IX: Suggestion pink rectangle in document doesn't allow "Click to fill" in same region

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#5456]
**Describe the bug**
When a PDF have a suggestion, it shows it in the document if it is opened in the IX UI. This pink rectangle for the suggestion doesn't allow "Click to fill" in same region.

**Comment by gabriel-piles** [comment]
The pink rectangle, where the suggestion lays, is going to be removed in the issue [#5472 (https://github.com/huridocs/uwazi/issues/5450)

So it is needed to reintroduce it but solving this problem with allowing "Click to fill" behind the pink rectangle.

**Comment by grafitto** [comment]
Closing this, with relation to @gabriel-piles comment
