### ISSUE TITLE
IX: Suggestion text trimmed in a different way than the other columns

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#5477]
**Describe the bug**
The suggestion text is trimmed in a different way than the other columns. All the columns should behave the same way. Could be all trimmed but with a higher character count.

 See attached image.

![Screenshot-20230127094314-1919x83](https://user-images.githubusercontent.com/22240564/215044624-2c6a501d-f819-4285-9c1d-e2c6c4c7f958.png)

**Comment by txau** [comment]
@juanmnl @konzz @grafitto I think this is being addressed in the new UI for IX?

**Comment by konzz** [comment]
Thanks for mentioning it, will check that this is fixed.

**Comment by grafitto** [comment]
This should be fixed in the PR for new UI for IX #6056

**Comment by Zasa-san** [comment]
This should be fixed now @gabriel-piles
