### ISSUE TITLE
Timelinks of media files not working when adding a media file directly from a device

### ISSUE THREAD

**Issue by hyebin-bina** [huridocs/uwazidocs#5493]
**Describe the bug**
There are two ways of submitting a media file in a media property: adding the media file from URL or uploading the media file saved in one's device. 

When directly uploading a media file from a device and creating timelinks of the file, the timelinks created do not work. When clicking the created timelink, Uwazi plays the media file from the beginning, not from the point you just marked.

This behavior happened both when testing with a video and audio file. 
The media file used in testing is attached below:
https://user-images.githubusercontent.com/85096417/216047019-4b13ec70-8ec4-4677-b1b7-658407095b06.mov

**To Reproduce**
1. Create a media property in your template
2. Add a media file as your supporting file in an entity
3. Choose the media file you just added
4. Create timelinks to your media file and save
5. Click the timelinks

**Expected behavior**
When clicking the timelink, the video should be played from the marked time instead of the beginning

**Device (please select all that apply)**
Desktop

**Browser**
Chrome

**Additional report**
When creating timelinks, users should be able to move the round pointer on the playbar to go to specific part of the video. 
<img width="214" alt="Screen Shot 2023-02-01 at 10 01 18 PM" src="https://user-images.githubusercontent.com/85096417/216051926-d555ec0b-47bd-4ea8-b34d-670ea5743179.png">

Currently, users have to play the video and wait until it reaches to the point they want and pause the video to create a timelink. 

**Additional question**
Regarding the workflow of adding a media file (step 2 & 3 above) -
Currently, users have to add a media file as a supporting file FIRST to be able to add it in the media property.
If users upload the file directly from a device without submitting it as a supporting prior, the media file gets saved but users cannot play the file. 
Is it a limit we have to live with or is it a bug?

**Comment by RafaPolit** [comment]
This is happening with MP4s as well, so the problem may be more "generic" than expected.

**Comment by mfacar** [comment]
> **Additional question** Regarding the workflow of adding a media file (step 2 & 3 above) - Currently, users have to add a media file as a supporting file FIRST to be able to add it in the media property. If users upload the file directly from a device without submitting it as a supporting prior, the media file gets saved but users cannot play the file. Is it a limit we have to live with or is it a bug?

@hyebin-bina, There is no limit, it is possible to upload a media file both at the creation or edition of an entity, in fact, this action adds a supporting file for the added media. I saw the problem just one time when I was trying to replicate it, although I can't replicate it systematically. That time, it was caused because the upload didn't complete and the file was saved pointing to the temporary client resource (blob URL). #5582 solves the problem with timelinks. Please check and in case of seeing the error during playing again, report it in a separate issue. cc. @RafaPolit, @Zasa-san

**Comment by hyebin-bina** [comment]
I re-test all errors some of us experienced and **all of them have been fixed.** Thank you. 

The errors we experienced were below. FYI, all these errors were observed only when users uploaded files directly from their device. Media files added from URL did not show the problems. 

1. Wrong uploading workflow: supporting file -> media file
Users could not directly upload the media file from device, users had to upload the media file first as a supporting file. Otherwise, the media file looked all black and not playable.

**Now I can directly upload a media file in my device without needing to upload it as a supporting file first, and the uploaded media file is playable.**

2. Navigation error
Users could not navigate the uploaded media file to the specific time, users had to play the media file and wait until it reaches to the time users wanted to mark.

**Now I can navigate the file and quickly reach to the point I want to mark.** 

3. Timelinks error
Even when users added timelinks after playing the file until it reaches to the point users wanted, the added timelinks did not work and it would only play the media file from the beginning, not from the marked time.

**The timelinks work well.**

**Comment by hyebin-bina** [comment]
Hello, @mfacar! I thought everything was fixed as I commented above. Unfortunately, everything looked fine **before I refresh my page**. After I refreshed my page, the media file uploaded is not playable, hence the timelinks do not work either. Please follow the steps below to replicate the issue.

1. Create a media property
2. Directly upload a media file saved in your device. (please see the attached media file I used for the test.)
3. Navigate the media file and add timelinks.
4. Save. Everything looks normal in the side panel.
5. Now **refresh your page** and go back to the entity you just worked on.
6. The uploaded media file looks black as below and timelinks are not working.
<img width="401" alt="Screen Shot 2023-03-08 at 2 52 37 PM" src="https://user-images.githubusercontent.com/85096417/223630593-06658e6e-bed0-4d89-a458-ecb65f1f3f9a.png">
7. Even when the uploaded media file appears normal, if you click the timelink, the file is not playing.

*Please see the media file I used for testing below:
https://user-images.githubusercontent.com/85096417/223630619-6bc949f7-1e56-45bd-b6c1-374f6a56d359.mp4

@RafaPolit

**Comment by RafaPolit** [comment]
@hyebin-bina could this be an issue of the file not being loaded yet? Is there are loading "circle" in the middle of the black square showing the media is still loading?

**Comment by hyebin-bina** [comment]
@RafaPolit 
Please see the attached screencast I recorded for your reference.
I (and others) only experienced this with the media files uploaded directly from the device. 
The files uploaded via URL work just fine.

[Screen Recording 2023-03-08 at 11.02.56 PM.mov.zip](https://github.com/huridocs/uwazi/files/10921318/Screen.Recording.2023-03-08.at.11.02.56.PM.mov.zip)
