### ISSUE TITLE
Viewing an entity’s relationships while switching between entities for some scenarios doesn't show relationship cards.

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#5507]
**Describe the bug**
View an entity’s relationships while switching between entities.  

**To Reproduce**
1. Login into an instance with at least three entities, one of them with relationships and the other two without relationships.
2. Select one entity with the RelationShip tab opened on the side panel.
3. Switch selection between the three entities, at some point the relationships are not shown.
No error appears, Uwazi merely does not show the relationships with other entities. 
Clicking the buttons Collapse all or Expand all do not allow viewing the relationships either.

**Expected behavior**
Uwazi shows the existing relationships, and the action buttons allow a user to complete necessary actions. 

**Screenshots**
![Screenshot 2023-02-03 155245](https://user-images.githubusercontent.com/5322716/216708597-a242a611-1769-402a-bd7f-e6fdfbe7d89e.png)

Clicking View and navigating back to the page to view the relationships panel results in having the relationship count show zero. 

**Additional context**
It was reported by @serena-huridocs as part of testing for #5331

**Comment by RafaPolit** [comment]
This is the third or fourth issue we have had to do regarding the state of relationships in the store when changing entities.

This needs to be reviewed comprehensively and not just fix one small error and have other places that showcase the same problems.  Also, this has shown complex enough, we need an e2e that not only navigates to entities and their relationships but that switches between entities and things work as expected.
