### ISSUE TITLE
"Click to fill" can provide empty rectangles

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#5512]
**Describe the bug**
Using "Click to fill" in Firefox shows in most cases an alert. It happens in most cases using the mouse left button double click to select the text and pressing "Click to fill".

The alert says "Could not detect the area for the selected text, please try selecting again.

See the screenshot below.

![Screenshot-20230206112743-1949x642](https://user-images.githubusercontent.com/22240564/216948671-9127494e-871e-4a01-99b7-301fbc882f66.png)

**Comment by txau** [comment]
@gabriel-piles didnt we have also a problem that it wasn't saving the value when this happens?

**Comment by gabriel-piles** [comment]
@txau that's true. When the warning appears it saves the text as extracted metadata with no position information. The selection rectangles list is empty.

![Screenshot-20230206144037-654x248](https://user-images.githubusercontent.com/22240564/216986368-052423b2-fbe7-43ff-94b5-423c59ea0067.png)

**Comment by txau** [comment]
@Zasa-san I think this issues is related to the development you are currently working on?

**Comment by Zasa-san** [comment]
I will link this to the PR we are working on to keep it in mind. Selections can fail, that warning is triggered when the selection return empty array of rectangles. The idea of that warning is that users know that nothing was truly selected. K

**Comment by Zasa-san** [comment]
I will link this to the PR we are working on to keep it in mind. Selections can fail, that warning is triggered when the selection return empty array of rectangles. The idea of that warning is that users know that nothing was truly selected. Now we also have the rectangles painted when the user selects so that they can visually confirm what will be saved.

**Comment by txau** [comment]
@Zasa-san so if the warning happens when the rectangles are empty, this is not a bug but working as intended?

**Comment by Zasa-san** [comment]
> @Zasa-san so if the warning happens when the rectangles are empty, this is not a bug but working as intended?

We could consider getting empty selections as a bug in our react-text-selection-handler repo. Warning the user about empty selections is intended and should happen in my opinion.

**Comment by txau** [comment]
Ok, I updated the title
