### ISSUE TITLE
Translations new UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5514]
Implement new UI for the translation route.

@juanmnl

**Comment by juanmnl** [comment]
the new layout comes with 3 main parts for the main content.
1. Breadcrumb navigation
2. Body of content
3. Action toolbar (bottom fixed) that will show general default actions and dynamic actions when an element is selected in the body

**Translations:**
<img width="1440" alt="Translations - Main" src="https://user-images.githubusercontent.com/699945/217019586-b10a5d74-7564-4d17-84d7-ca210ee704aa.png">

**Translate value**
<img width="1440" alt="Translations - translate" src="https://user-images.githubusercontent.com/699945/217019592-d9f30582-dc16-4999-b54b-3a7148d2a10d.png">

**Translate value: show untranslated**
<img width="1440" alt="Translations - translate-1" src="https://user-images.githubusercontent.com/699945/217019660-9fd123ca-4b55-4714-987d-4643e5f77de7.png">

[Prototype](https://www.figma.com/proto/HZX8qH0Aw8WiSch3Axczrn/new-comps?page-id=14%3A10151&node-id=16%3A11467&viewport=74%2C1879%2C0.23&scaling=min-zoom&starting-point-node-id=16%3A11467)

**Comment by juanmnl** [comment]
**Button styles:**
<img width="750" alt="Screenshot 2023-02-06 at 11 02 19" src="https://user-images.githubusercontent.com/699945/217021847-33261b74-d27e-466c-91ac-fc4bc5d303c6.png">

**Badges style**
<img width="519" alt="Screenshot 2023-02-06 at 11 04 22" src="https://user-images.githubusercontent.com/699945/217022578-c116b923-09ae-4d3f-9ac6-073c79cb77ec.png">

**Comment by juanmnl** [comment]
Adding a full width search bar to help users quickly find terms they're looking for.

The input should show a "clear" action, when the user has typed something into the input.

<img width="1437" alt="Screenshot 2023-04-11 at 10 05 24" src="https://user-images.githubusercontent.com/699945/231210371-bb9a3ff1-5ba5-4d1a-b5dc-06050918bdcc.png">
