### ISSUE TITLE
Sorting + pagination bug

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#5524]
**Describe the bug**
When mixing "show 300 more" in library with changing the sorting order, instead of proper sorting it adds results to end of the list and tosses wrong numbers for the totals.

**To Reproduce**
1. Go to library
2. Hit the button "show 300 more"
3. Change the sorting order

It doesn't change the order and shows wrong totals:

![image](https://user-images.githubusercontent.com/489831/217276615-baf59be1-d28a-43eb-b5dd-ca196ac4e002.png)

**Comment by RafaPolit** [comment]
When there are from-limit values in the URL, changing the sorting order or the sorting property does not reset the URL limits to 30 (default) like the Filters or the Search bar.

As a quick fix, make it so that changing the order removes this properties from the URL and the search begins anew.

As a long term solution, it would be ideal to have pagination instead of "load more".

**Comment by salvalacruz** [comment]
Hi, I think this bug needs to be checked again.
Entities are not properly sorted in staging instances.

**Comment by RafaPolit** [comment]
The fix is working for the directional arrow, but not for the sorting property.

**Comment by serena-huridocs** [comment]
Similar behavior (when clicking **show 300 more**, Uwazi displays incorrect number of entities shown) still manifests itself in one of the instances where Russian is set as a default language. Let me know if you need any additional details. 

The text in the screenshot says **904** shown out of **767** entities. 

<img width="1439" alt="Screenshot GH" src="https://user-images.githubusercontent.com/100300126/232807076-50d28be9-656a-470a-bc1f-529300d56036.png">

**Comment by serena-huridocs** [comment]
This is just to give you a heads up that the reported problematic behavior still manifests itself in instances: 
![Screenshot 2023-10-26 at 14 39 57](https://github.com/huridocs/uwazi/assets/100300126/5dfd2644-5226-4faa-bb1a-5984d2b2f6c4)
![Screenshot 2023-10-26 at 14 40 05](https://github.com/huridocs/uwazi/assets/100300126/237789ec-2604-44f3-8eb7-f8d4aa43a4f3)
