### ISSUE TITLE
Language dropdown menu CSS color not activated 

### ISSUE THREAD

**Issue by agsabbagh** [huridocs/uwazidocs#5534]
In my instance , The Language dropdown menu text color CSS is set to black (#000) but the color always appease as white (#fff) 
as you can see in the attached photo. 
Any ideas on how to fix this?
Thank you! 

![image](https://user-images.githubusercontent.com/66379177/218113399-939f2c2d-1d72-4381-8385-ccb76e01ec74.png)

**Comment by RafaPolit** [comment]
Thanks for this report.  Can you please share your custom CSS configuration (at least the part pertaining to the menu color override)?

That could help us figure out if we can suggest a solution from your end or if we need to fix it from our side.

Best regards,
Rafa.

**Comment by agsabbagh** [comment]
Sure, attached.

[custom CSS.txt](https://github.com/huridocs/uwazi/files/10708404/custom.CSS.txt)

**Comment by RafaPolit** [comment]
I don't see that you have set the color for the Language selector.  The dropdown is being targeted, but the actual button isn't.

Try adding this class:
```
.menuNav .menuNav-I18NMenu .menuNav-language .singleItem {
  color: #000;
}
```

just before the `header .search-button,` line.

**Comment by agsabbagh** [comment]
thank you it works.
