### ISSUE TITLE
Table View - Problems sorting entities

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#5549]
**Describe the bug**
Sorting feature works fine in table view only with the first 30 entities. If you expand the list and get more entities, sorting function does not work.

**To Reproduce**
1. On FILTERS, click any template with more than 30 entities.
2. Click on 'Table view'.
3. Scroll down and click '300 more'.
4. Scroll up and select any property in the 'sorted by' option.
5. See error: the order in the list of entities does not change.

**Expected behavior**
When you select a property in the 'sorted by' option, the list of entities should be ordered by this field, even if the table shows more than 30 entities.

**Screenshots**
![image](https://user-images.githubusercontent.com/73410334/218772345-9f77e16a-29b7-4b64-be75-b9f088fe3e80.png)

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Browser**
Brave

**Additional context**
It behaves equaly with different Uwazi instances and browsers.

**Comment by txau** [comment]
Probably related to: https://github.com/huridocs/uwazi/issues/5524

**Comment by RafaPolit** [comment]
Duplicate of #5524

**Comment by salvalacruz** [comment]
So better I close it, thanks.
