### ISSUE TITLE
Inherited properties are showing as [object] in CSV export

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#5550]
**Describe the bug**
Relationship properties that are inheriting values are showing as `[object]` in CSV export

**Comment by daneryl** [comment]
@RafaPolit I am not able to replicate, can you provide replication instructions please?

**Comment by txau** [comment]
@daneryl I think this is inherit of inherit?

**Comment by daneryl** [comment]
@txau tried that, not showing '[object]' on export, but its exporting the sharedId, not sure this is what supposed to happen.

**Comment by RafaPolit** [comment]
If you use one of the larger instances from the first collections and export the library on default settings, you will see the “[object]” entry in one of the fields.  If not, I’ll debug this properly on Monday.  Sorry for the lousy description.

**Comment by daneryl** [comment]
Got one example already thanks
