### ISSUE TITLE
CSV export wipes the user provided label for geolocation properties 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazidocs#5571]
**To Reproduce**
1. Create a template with geolocation properties
2. Change the property label to your own unique label
3. Select some entities from that template and click on export. 

https://user-images.githubusercontent.com/60774708/221204071-61a7cc5a-ff4e-47f9-901e-b18b05cd0af2.mov

cc: @pddocs

**Comment by nwyu** [comment]
Closing this in favor of #5572.
