### ISSUE TITLE
Issue when exporting entities with multiple geolocation properties

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazidocs#5572]
CSV export is not able to export all geolocation properties when there is more than one geolocation property on a template. 

**To Reproduce**
1. Create entities that have more than one geolocation properties. 
2. Select those entities and click on csv export. 
 
cc: @pddocs 

https://user-images.githubusercontent.com/60774708/221205393-a9665d59-7315-4bcc-940b-348d4543f823.mov

**Comment by RafaPolit** [comment]
This is probably related to #5571
