### ISSUE TITLE
CSV export does not export parent thesauri in entities with grouped thesauri

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazidocs#5573]
Currently, Uwazi does not export the parent thesauri of an entity and only exports the sub grouped thesauri within. This is potentially confusing as the parent thesauri provides critical context on the sub categories within. 

**To Reproduce**
Steps to reproduce the behaviour: 
1. Create entities that have a single/multi select property that uses grouped thesauri
2. Select those entities and click on csv export. 

cc: @pddocs 

https://user-images.githubusercontent.com/60774708/221207053-18f7940f-9113-43c7-8412-441ef46f8c3d.mov

**Comment by natasha-todi** [comment]
This issue^ is the same as https://github.com/huridocs/uwazi/issues/5423

**Comment by RafaPolit** [comment]
Duplicate of #5423 
Closing.
