### ISSUE TITLE
Hide/show "Export CSV" button

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#5575]
**Is your feature request related to a problem? Please describe.**
In some use cases, users need to limit the access to download information in bulk, or to control who is downloading data (csv files).

**Describe the solution you'd like**
A posible solution would be to add a setting option to select if anonymous and/or collaborators are allowed to export csv files.

Something like adding these options in settings/collection:
        [on/off]  Hide 'Export CSV' for anonymous users (public instance)
        [on/off]  Hide 'Export CSV' for collaborator users

**Comment by RafaPolit** [comment]
CSV Export is just another format, the whole data can always be downloaded as JSON via the API, and, as a matter of fact, an API call to the CSV export endpoint would provide the CSV even if we "hide" the physical button on the page.

These cosmetic features that give users "fake" sense of privacy or security should be avoided.
