### ISSUE TITLE
Filters: number is overlapped

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#5576]
When filtering, if the number of entities has more than 4 digits and the filter configurations has groups, the characters are overlapped with the "display group" button.

![image](https://user-images.githubusercontent.com/73410334/221594968-99028fc8-69d7-411b-9851-1a548777273b.png)

**Comment by hyebin-bina** [comment]
This has been reported /requested from another partner as well - 

<img width="395" alt="Screen Shot 2023-06-20 at 2 03 00 PM" src="https://github.com/huridocs/uwazi/assets/85096417/443cb50c-32c6-4d4b-8da9-4f881173b1f7">
