### ISSUE TITLE
Importing entity through CSV breaks thesauri.

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#5585]
**Describe the bug**
Importing through CSV an entity that includes a thesauri values to be created on the flight breaks the thesauri in such a way that for each group in the thesauri, it creates a value witin the group that shares label and id with the parent.

**To Reproduce**
1. Create a thesauri with a group `A` that contains at least a value `A1`.
2. Create a template with a select/multiselect property that uses the thesauri from 1. as content.
3. Import through CSV an entity for the themplate created in 2. and use `B` as value for the select property. Note the value doesn't exist in the thesauri and should be created on the flight by the import process.

**Current behavior**
The entity is created but the thesauri looks like follows:
```
- A
  - A1
  - A
- B
```

where both `A`s also share the ids.

**Expected behavior**
The entity is created and the thesauri looks like follows:
```
- A
  - A1
- B
```

**Additional context**
Note that because it created those children values, you are able to use the parent thesauri as values in the import, which will end up assigned to the freshly created child values.

**Comment by fnocetti** [comment]
This needs to include a fix for the root cause and a migration to fix the data.
@RafaPolit suggested that, since the group/parent thesauri values shouldn't be assignable to metadata, it should be enough to regenerate the parents ids on the thesauri and update it on the denormalizations on the entities.
The only thing we believe this should break are possible saved/linked urls containing filters related to the thesauri.

**Comment by LaszloKecskes** [comment]
Closed through a hotfix (merge to production): #5592
