### ISSUE TITLE
Translations form in non-english instances behaves incorrectly

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#5593]
**Describe the bug**
The translations form displays untranslated terms in an incorrect way when the instance does not have the English language.

**To Reproduce**
1. Set an instance with English and at least two other languages
2. Delete English language, setting another as default.
3. Go to translate the UI and use the filter for untranslated terms.

**Expected behavior**
It should work regardless of the installed languages and default language.

**Screenshots**
![image](https://user-images.githubusercontent.com/71732018/223123942-6434a9fb-6235-4be1-809c-b15eee3d0230.png)

**Comment by konzz** [comment]
This is no longer a problem after the rewrite
