### ISSUE TITLE
CSV Import is corrupting multi-language collections

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#5594]
NOTE: More critical part of this bug described on comment below!

**Describe the bug**
If you import the following CSV:

| Title\_\_en | Title\_\_ko | Multilingual thesauri test\_\_en | Multilingual thesauri test\_\_ko |
| --- | --- | --- | --- |
| Bina | 비나 | North Chungcheong | 충북 |
| Bena | 베나 | South Chungcheong | 충남 |
| Bana | 바나 | Seoul | 서울 |

Where `Multiligual thesauri test` is a `Select` or `Multiselect` property, the system will do some unexpected processes:
- It "accepts" and understands that `Multilingual thesauri test__en` and `Multilingual thesauri test__ko` should populate the same property, even though it's not a property that is susceptible of being translated via CSV
- It will create values for both the english and korean values inside the thesauri (half-expected, though it's weird that it even understands the `__en`  and `__ko` as the same property)
- It will create the entity in EN with the value in English, and the entity in Korean with the Korean value.  This is really, really wrong as those type of properties cannot have different values on entities of different languages

As soon as you edit the entity, it will correctly "sync" all versions of the entity to a single value.

We need to decide what to do.  We can either:
- Simply reject those properties that cannot be translated if they are namespaced
- Ignore the non-default language values for those entites
- Actually allow the creation of translated thesauri via this method

**Comment by RafaPolit** [comment]
Apparently it should understand this as a translation, so there may be a small bug there.

**Comment by hyebin-bina** [comment]
@RafaPolit @natasha-todi 

Additional bug report: **Uwazi does not display Korean values even when the translations are correctly imported / entered.**

Testing steps:
Step 1. Create a CSV file as below
<img width="589" alt="Screen Shot 2023-03-15 at 4 43 25 PM" src="https://user-images.githubusercontent.com/85096417/225240510-af78276b-0fe0-4449-972a-411517f74a01.png">


Step 2. Before importing the file above, translate thesauri items first. For the testing purpose, try two options below.

2-1. Translate through Settings > Thesauri > import CSV file that has thesauri in two langauges attached below. 
[Multilingual Thesauri Test - One-level Thesauri.csv](https://github.com/huridocs/uwazi/files/10977195/Multilingual.Thesauri.Test.-.One-level.Thesauri.csv)
Go to Settings > Translations to double check the translations are correctly imported.
<img width="257" alt="Screen Shot 2023-03-15 at 4 35 14 PM" src="https://user-images.githubusercontent.com/85096417/225242634-a27c9d92-5070-4089-b3b1-dd77e34c9678.png">

2-2. Translate through Settings > Translations > manually enter the translations below.
<img width="226" alt="Screen Shot 2023-03-15 at 4 34 52 PM" src="https://user-images.githubusercontent.com/85096417/225242726-2aec5199-4de4-4cb2-9489-a6cb5a94197d.png">

3. Import the entities that have select properties (for which we provided translations as above) through CSV file.
[Multilingual Thesauri Test - Translation Test.csv](https://github.com/huridocs/uwazi/files/10977295/Multilingual.Thesauri.Test.-.Translation.Test.csv)

4. Go to Library in **the Korean interface** and see the import result.
<img width="1449" alt="Screen Shot 2023-03-15 at 4 36 10 PM" src="https://user-images.githubusercontent.com/85096417/225245402-a3d613e6-84f3-4361-992d-46ebe018e7c2.png">
In the side panel,  you can see the thesauri items are correctly translated (see translated values under two select properties named "Multilingual thesauri test" and "Translation test"). However, in entities, the values are displayed in English.

**Comment by RafaPolit** [comment]
After checking with @hyebin-bina , this is a more serious issue:  Importing a CSV into any collection with more than one language is corrupting all languages but the default one.

In the above example, both the English version and the Korean version of the entity holds the right Thesaurus value, but the denormalized label for the Korean language is actually kept in English.

Currently, the only way to re-sync the denormalization to its correct values is to either: save the Entity, or modify the translation to force a new de-normalization of those properties.

**Comment by RafaPolit** [comment]
Maybe related to #5366
