### ISSUE TITLE
Deleting a relationship type doesn't check if type is being used in relationship property

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#5595]
**Describe the bug**
When a relationship type is being used in a relationship property and the user tries to delete it, the system will check for connections using the relationship type but not for uses in properties. I won't neither delete the property.
It results in an inconsistent state where relationship properties exist that doesn't have a valid relationship type.
Note that this isn't triggered if connections for the type exist because the other check will prevent it.

**To Reproduce**
1. Create a relationship type `relType1`
2. Have 2 templates: `A` and `B`
3. Create in `A` a relationship property that points to entities of template `B` and uses `relType1`
4. Delete `relType1`

**Current behavior**
The relationship type is deleted and the property persists on the template but with no, or invalid, relationship type.

**Expected behavior**
The model is left in a consistent state. Either you're not able to delete the relationship type or the property gets deleted as well.

**Comment by salvalacruz** [comment]
I suggest to change the warning message to "Cannot delete relationship type being used in templates…".
I mean, please add the word "relationship".

**Comment by fnocetti** [comment]
@salvalacruz thank you for your input! We will handle that as a follow up implementation within the linked issue above.
