### ISSUE TITLE
Merge content repo into uwazi

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5597]
Instead of getting the translations to an external [github repository](https://github.com/huridocs/uwazi-contents)  we will ship every app with its own version of the contents.
Having this in a separate repository has its advantages (correcting types and having immediate effect without having to deploy)  but complicates things considerably, we prefer having everything together and ship it with the app, doing more frequent (hotfixes) deploys if needed.

#5444 added a routine to check inconsistencies between the database and the translation contents by language, this should be updated to check from the local contents once these have been moved.

**Comment by konzz** [comment]
Also check #5639

**Comment by konzz** [comment]
We are running into an error:
```
 GithubQuotaExceeded: Translations could not be loaded
    at ContentsClient.fetch (/home/konz/Sites/uwazi/app/api/i18n/contentsClient.ts:53:40)
```

Our e2e test languages installation, and if we have multiple PRs running, and at the same time people installing languages, we will run into this problem very often, I think this issue should be considered high
