### ISSUE TITLE
unexpected error on custom pages 

### ISSUE THREAD

**Issue by agsabbagh** [huridocs/uwazidocs#5599]
As you can see in the attached screenshot there is an error message appears every time I visit the home page. this applies to every custom page in the instance even if it's clean of code.

![image](https://user-images.githubusercontent.com/66379177/223366578-089d0a7e-5a20-475d-bd16-ab7773e36342.png)

Any ideas on how to fix this?

**Comment by nwyu** [comment]
Hi @agsabbagh! A partial fix has already been made ([PR #5586](https://github.com/huridocs/uwazi/pull/5586)), but it only removes the error from showing on the public side of Uwazi. In other words, if you log out, you will not see those errors on each page. We are still working on the fuller fix to remove those error notifications altogether.

**Comment by daneryl** [comment]
@Zasa-san @nwyu do we have an issue to the fuller fix ? can you create it please ?

**Comment by Zasa-san** [comment]
@daneryl https://github.com/huridocs/uwazi/issues/5624

**Comment by konzz** [comment]
closed in favour of #5624

**Comment by agsabbagh** [comment]
Hello, any updates regarding this issue?

**Comment by txau** [comment]
@agsabbagh plpease read @konzz 's latest comment and link to the issue
