### ISSUE TITLE
Languages new UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5603]
Apply the new designs and functionality for the languages section as seen below.

**Comment by juanmnl** [comment]
As a user navigates to the **Languages** section, they are presented with a simple table listing the currently installed languages, the selected default language of the db, and two actions: reset & uninstall. The action bar offers an "install language" action.
<img width="1440" alt="Screenshot 2023-03-13 at 16 52 58" src="https://user-images.githubusercontent.com/699945/224842359-d3e5ad49-ed2a-462f-995f-9d2c44bfec98.png">

When one or more languages from the table are selected, the action bar switches to an "edit mode" where dynamic actions are offered. In this case: reset & uninstall, and label that show the user the number of selected items. This gives the user the ability to trigger language actions in bulk.
<img width="1440" alt="Screenshot 2023-03-13 at 16 53 20" src="https://user-images.githubusercontent.com/699945/224843188-022574d3-dacf-4878-b7fb-14bccfcd36e7.png">

**Install language**

When the user triggers the "install language" button from the action bar, a modal is shown with a list of all the available languages.
<img width="1440" alt="Screenshot 2023-03-13 at 17 10 52" src="https://user-images.githubusercontent.com/699945/224844166-02dec7ef-1b84-4d01-88a0-e17f8e913e17.png">

The modal has 3 states:
1. Initial: with a list of all the languages, a clear input and a disabled main action (Install)
<img width="429" alt="Screenshot 2023-03-13 at 16 54 07" src="https://user-images.githubusercontent.com/699945/224844841-04caa886-1593-4515-b919-28ee666fbf54.png">

2. Filtered: the search acts as a filter to reduce the matching languages.
<img width="426" alt="Screenshot 2023-03-13 at 16 54 19" src="https://user-images.githubusercontent.com/699945/224845076-3520d696-49ac-4b22-b400-68d9b516fdc2.png">

3. Selected: when one or more languages are selected, the install button turns to active.
<img width="426" alt="Screenshot 2023-03-13 at 16 54 37" src="https://user-images.githubusercontent.com/699945/224845211-4970c3f4-0756-47de-aa40-607e669264b7.png">

**Uninstall Language**

When a user triggers the "uninstall action", either on a per language or bulk, a confirmation modal is triggered with a security-check (input the word "CONFIRM") to make the uninstall button active.
<img width="1440" alt="Screenshot 2023-03-14 at 09 04 18" src="https://user-images.githubusercontent.com/699945/225026115-f3444af9-b306-4ab3-83d9-b8011d4f6459.png">



[Prototype](https://www.figma.com/proto/HZX8qH0Aw8WiSch3Axczrn/new-comps?page-id=14%3A10151&node-id=17%3A12362&scaling=min-zoom&starting-point-node-id=16%3A11467)

**Comment by juanmnl** [comment]
**Fix**: Header description of the "Install language" modal.
<img width="443" alt="Screenshot 2023-03-13 at 19 13 42" src="https://user-images.githubusercontent.com/699945/224859723-d43180b2-b41a-4e43-8210-73577b01b4c8.png">

**Comment by salvalacruz** [comment]
All notifications should be consistently located - this one in the screenshot is on the bottom left side which is not consistent with the other Uwazi notification locations.
![image](https://github.com/huridocs/uwazi/assets/73410334/98adaf2c-e1ca-46a3-90e4-462e3158fb4f)

**Comment by pddocs** [comment]
As part of our yesterday's testing, we noted an issue when installing a new UI language in Uwazi: when trying to install, the instance is throwing an error. However, upon refreshing the page, we find the UI language has actually been installed. See the screencast below.

https://github.com/huridocs/uwazi/assets/88421793/1fee8ab7-2394-4488-807c-6eef0558de95

**Comment by RafaPolit** [comment]
> All notifications should be consistently located - this one in the screenshot is on the bottom left side which is not consistent with the other Uwazi notification locations. ![image](https://user-images.githubusercontent.com/73410334/240613225-98adaf2c-e1ca-46a3-90e4-462e3158fb4f.png)

Since these are, precisely, developments aimed at updating the Uwazi UI, some temprary inconsistencies between behaviors, looks and locations are expected.  Not sure if this one is intended, but while we migrate all screens to the new UI, we will have to live with some of these inconsistencies.

**Comment by konzz** [comment]
So, it was quite fast to check the error and is coming from the load balancer timeout. What wasn't that fast was testing this with the same data in a production environment to test that this already happens in production and that we already have an issue with priority high about this topic [3130](https://github.com/huridocs/uwazi/issues/3130) from 2020
