### ISSUE TITLE
Can not set up 2FA

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#5609]
There is a problem with 2FA configuration and collaborator users:
        
1. Login an instance with a collaborator user.
2. Go to Settings / Account screen.
3. Click on "Protect your account".
4. Then it jumps to the login screen and 2FA can not be set up.

**Comment by RafaPolit** [comment]
Diagnostic:

- This error was introduced in #5331 where the abstraction of allowed route permissions assumed only admins for all settings routes
