### ISSUE TITLE
Display Data Chart Sequentially Based on Year

### ISSUE THREAD

**Issue by petkong** [huridocs/uwazidocs#5617]
Dear Uwazi,

I am trying to display case data from 2010 - 2020 using single-select data. How to display Chart data sequentially based on the lowest year to the latest year (from left to right) as you can see on this page >>> 
https://kebebasanberkesenian.uwazi.io/in/page/666omhh7if/bar-chart-tahun-peristiwa-beranda

Best regard,

Andri

**Comment by nwyu** [comment]
Your site looks great, @petkong! This past Github issue #2839 should point you in the right direction. Also, you might find #1898 and #2434 useful for some of your other charts, particularly those that have long category names.

**Comment by petkong** [comment]
Thank you Nancy. It works
