### ISSUE TITLE
Can't Access to All Page

### ISSUE THREAD

**Issue by petkong** [huridocs/uwazidocs#5622]
Dear Uwazi team,

It's a bit urgent. One of our team members accidentally made a mistake by changing the data in the global js, where the data becomes a redirect, and we can't access it at all to log in, etc., because it wrong redirects code. 

Here is the code that should be removed on the Global JS Tab on the URL below :

https://kebebasanberkesenian.uwazi.io/in/settings/customisation

**Code should be removed**:

// Check if the browser language is not Indonesian
if (navigator.language.substr(0,2) !== 'id') {
  // Redirect to the Indonesian homepage
  window.location.replace('/id/');
}

I am waiting for your reply. Thank you for the help. We do apologize.

Best regard,

Andri

**Comment by daneryl** [comment]
@petkong it should be fixed now, removed the customJS code.
