### ISSUE TITLE
Handle PublicForm errors

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#5627]
**Is your feature request related to a problem? Please describe.**
Right now when a user misconfigured the template in a public form element 
```
<PublicForm template="wrongTemplateId" file />
```
Uwazi will throw an unhandled error on the page. If this page is set as the landing page, it might block users from using the instance.

**Describe the solution you'd like**
Errors on pages should not break the application and should display an error in a way that users can continue working.

**Additional context**
We should check if other components that users can implement in custom pages break the app in the same way.
Technically, pages have an error boundary component, but in this case we are not seeing our custom error component.

https://github.com/huridocs/uwazi/blob/e547cfe4583fdc318ebe3ace3b7ef79a507efd61/app/react/Pages/PageView.js#L55-L67

**Comment by RafaPolit** [comment]
Check if fixing #6250 does not solve the critical problem of having the collection rendered inaccessible.  If it does, please degrade this to medium priority.

**Comment by grafitto** [comment]
> Check if fixing #6250 does not solve the critical problem of having the collection rendered inaccessible. If it does, please degrade this to medium priority.

Checked. And this is not solved in #6250

**Comment by mfacar** [comment]
Error boundaries catch errors during rendering. In this case, the error is being thrown at the constructor and static methods on SSR. React 18 relies on Suspense to recover the app after the error. More information on [this comment](https://github.com/facebook/react/issues/23184#issuecomment-1082812565)
