### ISSUE TITLE
IX: Creating a metadata extractor with an empty name shows error behind the modal window.

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#5650]
When creating a metadata extractor with an empty name shows error behind the modal window. See image below

![Screenshot-20230329181146-1280x598](https://user-images.githubusercontent.com/22240564/228601605-63e51a3f-e51c-4dfb-8231-aefcf9c63f7b.png)

Also, after removing a metadata extractor, if the "Create Extractor" button is pressed, the removed extractor is shown in the modal window.

![Screenshot-20230329181505-1272x458](https://user-images.githubusercontent.com/22240564/228602295-d2e0689e-fab3-4d56-8f4e-82fecfe61bc5.png)

**Comment by RafaPolit** [comment]
cc @Zasa-san please check if this is still a problem, and maybe it's a quick win? (hint: don't spend 3 weeks on this :) )

**Comment by Zasa-san** [comment]
![image](https://github.com/huridocs/uwazi/assets/71732018/d4e682c6-e8f0-4e26-9f4f-8e7cb6e35d59)

This is no longer the case, now report the error on the modal itself. The modal is also reset correctly.
