### ISSUE TITLE
Infinite loop for error when "Public form submit" is empty  in an instance with a remote public form

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#5694]
**Describe the bug**
When there is an inconsistency in the configuration for a remote public form, the page is throwing consecutively server errors. 

**To Reproduce**
2. Make sure the field "Public form submit" in Settings is empty.
2. Create a page with a PublicForm tag for an existing template with remote as a property.
3. Open the created page.
4. See errors.

**Expected behavior**
Only should be an error with the reference for the missing configuration.

**Additional context**
https://user-images.githubusercontent.com/5322716/231328615-8f8b1e1e-e90a-438c-9eb1-4fdbd650d81b.mp4

**Comment by txau** [comment]
@mfacar  same as https://github.com/huridocs/uwazi/issues/5171 ?

**Comment by mfacar** [comment]
> @mfacar same as #5171 ?

Yes @txau, it's the same, thank you!, I didn't expect to find an old issue for this so I only checked with recent issues 😓. I'm closing this in favor of  #5171
