### ISSUE TITLE
How can I get an instance of Uwazi

### ISSUE THREAD

**Issue by aymohamed** [huridocs/uwazidocs#5696]
Hello Uwazi,

I am Abdijabar & I am currently working with the Commission for the Investigation of Violence, Reconciliation & Reparations of Victims in the Somali Region of Ethiopia. The commission has been officially mandated by the Somali Regional State (SRS) to conduct a thorough analysis of the decades-long human rights violations by the successive regimes in this Horn of Africa Nation.

We are seeking an instance of Uwazi so that we can hit the ground running. Thanks!
Best,
Abdi

**Comment by nwyu** [comment]
Hi @aymohamed. Thanks for reaching out to us! We received your request and will reply over email.
