### ISSUE TITLE
Timelinks edition has missing validation and doesn't work as expected  

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#5702]
**Describe the bug**
When adding or editing a timelink, the fields corresponding to the hours, minutes, and seconds admit any character, don't restrict the maximum value or the number of digits. 
Edit the values for the default timelink that appears during the edition doesn't create the timelink at saving.

**To Reproduce**
1. Create/edit an entity that has a media property.
2. Select a valid file for the media property.
3.1. Add a time link and enter letters for the hours/minutes/seconds.
3.2. Edit the inputs for the default timelink
5. Save the entity
6. The entity is saved with invalid values.

**Expected behavior**
The fields of the timeline should accept only numbers and restrict, at least for minutes and seconds, to 60. It's desirable that there be also a validation for the API.

**Screenshots**
![Screenshot 2023-04-12 191030](https://user-images.githubusercontent.com/5322716/231612828-09fe37a1-3e97-4f2c-8ea2-2d0548aaa926.png)

**Comment by LaszloKecskes** [comment]
Reopening, since the back-end part is still under development.

**Comment by LaszloKecskes** [comment]
After discussion, we're postponing and reviewing the back-end part. Closing, since the front-end validation was resolved by @konzz, and the rest will continue in #6089.
