### ISSUE TITLE
Redesign the setting of collection emails

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#5721]
Currently, our UI is allowing setting the receiving and sending addresses in Settings - Collection - Forms and email configuration - Contact Form the following way:
![Screenshot-39](https://user-images.githubusercontent.com/27060262/232829280-6355a714-c43c-48f3-8d3e-13e0b00f4c5e.png)

The issue is that the sending email affects not only the contact form, but every email sent from Uwazi, including password reset or account creation email for users. Also, during the discussions it has been noted that aside from the placement, the tool-tips are also incomplete and somewhat counter-intuitive to some.

The task is to review and rewrite the above UI elements to be more inline with their actual usage. The functionality is correct in the sense that if the emails are set, they are applied correctly.

Note: this issue was created after another issue (#5693), where confusion about this functionality actually occurred.

**Comment by RafaPolit** [comment]
Being fixed as part of #5826
