### ISSUE TITLE
New Users UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5730]
@juanmnl

**Comment by juanmnl** [comment]
This layout comes with 2 main components, one that we already have: the table, and one that's going to be widely used across the app: the drawer.

There's also 2 new behaviors added: 1) the inset tabbed-navigation, used to switch around the table of users and the one of groups, and 2) the multi-check dropdown/up to add values to a group.

There's also a first, very simple empty state for the groups table –as there's always going to be at least one user–.

**1. Users list**
<img width="1440" alt="Screenshot 2023-04-24 at 19 40 47" src="https://user-images.githubusercontent.com/699945/234149869-694e6c24-8956-4a7e-a21c-7915250151df.png">

**1.1 New user**
<img width="1440" alt="Screenshot 2023-04-24 at 19 41 34" src="https://user-images.githubusercontent.com/699945/234149944-ccaefd50-aab1-44cb-b6b7-ffa265e68171.png">

**1.2 View/Edit user**
<img width="1440" alt="Screenshot 2023-04-24 at 19 43 31" src="https://user-images.githubusercontent.com/699945/234150006-333212ab-f3bf-413b-9595-685f645d3c60.png">

**1.3 Add group(s) to user**
<img width="711" alt="Screenshot 2023-04-24 at 19 42 37" src="https://user-images.githubusercontent.com/699945/234150553-81c16d75-0f0b-4e48-9eff-95b022b6c88e.png">

**1.4 Delete User(s)**
<img width="1440" alt="Screenshot 2023-04-24 at 21 20 03" src="https://user-images.githubusercontent.com/699945/234158497-a0a766db-4142-4772-8ef2-08f5a48835a9.png">

**2. Groups list - empty**
<img width="1440" alt="Screenshot 2023-04-24 at 19 41 08" src="https://user-images.githubusercontent.com/699945/234150088-3c2c9fe3-63ef-4edf-9e15-c645476b57a2.png">

**2.2 New group**
<img width="1440" alt="Screenshot 2023-04-24 at 19 44 21" src="https://user-images.githubusercontent.com/699945/234150181-5a39ab09-96ec-491f-a71c-150e7721585f.png">

**2.3 Groups list**
<img width="1440" alt="Screenshot 2023-04-24 at 19 43 52" src="https://user-images.githubusercontent.com/699945/234150256-4cdc4e15-3681-4540-859e-e35c5753401b.png">

**2.4 Add members to group**
<img width="741" alt="Screenshot 2023-04-24 at 19 44 32" src="https://user-images.githubusercontent.com/699945/234150331-b48a4048-6367-4cee-9005-499bb8275bbd.png">


(This prototype is changing a lot as I intend to make a single one for all the settings, so if it doesn't work, please contact me : ))
[PROTOYPE](https://www.figma.com/proto/HZX8qH0Aw8WiSch3Axczrn/new-comps?page-id=14%3A10151&node-id=366-13106&viewport=144%2C5643%2C0.68&scaling=min-zoom&starting-point-node-id=16%3A11467)

**Comment by Zasa-san** [comment]
This PR has updated [5764](https://github.com/huridocs/uwazi/issues/5764)

**Comment by juanmnl** [comment]
Adding a reset 2FA to the dynamic actions bar and the drawer, and removing buttons supporting text.

<img width="1440" alt="Users - Users" src="https://github.com/huridocs/uwazi/assets/699945/216c0201-77ae-4a96-ba3a-4f1097c391d5">
<img width="618" alt="Edit User" src="https://github.com/huridocs/uwazi/assets/699945/bc84af74-db6c-40b5-9362-773151ef002a">

**Comment by konzz** [comment]
@Zasa-san hey after speaking with Txau, we agreed to add a button to "Unlock" an account when it gets locked after some password attempts

**Comment by juanmnl** [comment]
Update: Adding the helper modal for user roles.

This adds our first modal with a table inside, I know there's a bit of a redundancy with the close on the top and the close on the bottom, but let's keep'em for the moment, just as a single pattern for modals.

<img width="471" alt="Screenshot 2023-06-14 at 10 00 30" src="https://github.com/huridocs/uwazi/assets/699945/4cca14ee-6dd7-48b8-9604-2b0657328f28">

When the user clicks on the helper icon (?) besides the "User Role" label the following modal will display:

**Full content**

<img width="705" alt="users - permissions" src="https://github.com/huridocs/uwazi/assets/699945/498cee2a-79c3-4de7-8300-fdb68a80b0dc">

**Modal with scroll body and pop-up on hover**

<img width="705" alt="users - permissions scroll" src="https://github.com/huridocs/uwazi/assets/699945/82cd0eae-cd13-4adc-9b2f-732a12f27b67">
