### ISSUE TITLE
Password change for admin 

### ISSUE THREAD

**Issue by lwieneke** [huridocs/uwazidocs#5731]
**Describe the bug**
When changing the default password for admin on a new Uwazi installation an error message appears "validation failed" and the password is not changed.
Similarly when creating a new user, the password is not stored and the user does not appear in the user list. Still an error message appears when another user with the same name or mail address is created.  

**To Reproduce**
On a fresh Uwazi installation and logged in as admin
1. Go to 'Settings/Account'
2. Enter a new password in the two fields
3. Click on update

**Expected behavior**
The password should be changed for both instances

**Device (please select all that apply)**
 - [x] Desktop
 - [ ] Mobile

**Browser**
Issue on Safari and Firefox

**Additional context**

**Comment by RafaPolit** [comment]
Good morning.  Thank you for the report.

Quick question so we can start looking at the issue: are you hosting with us?  Are you self-hosting?  If you are self-hosting, what version of Uwazi are you running on?

We had a similar issue a while back, but it was addressed quite a long time ago.  If this is a new problem, we will look into it with top priority.  Thanks again.

**Comment by lwieneke** [comment]
Hi there and thanks for your reply!
I'm self-hosting and I use the latest release as of the [installation instructions on your site](https://github.com/huridocs/uwazi/blob/development/SELF_HOSTED_INSTRUCTIONS.md) so this should be V1.112.0 as I installed yesterday. 
Just checked package.json and it confirmed that it's v1.112.0

**Comment by RafaPolit** [comment]
Some of these processes may require the mailing server to be correctly configured.  Failure to send the mail could result in such an error.

Can you please post the full network POST body and reply of the call when you click on the UPDATE button?

You can achieve this by opening the DEVELOPER TOOLS and inspecting the network traffic.  We are looking for the `/api/users` POST call.  Please, post the Payload of the sent data and also the full reply from the server.  Please `xxxx` out the username and password but ensure that they are correct before blurring them out.

**Comment by lwieneke** [comment]
Thanks a lot for your response! I actually didn't configure _sendmail_ on the machine as I thought that it was optional according to this [page](https://github.com/huridocs/uwazi/wiki/Install-Uwazi-on-your-server)
Let me get sendmail going and I'll come back to you!
The instructions also mention an SMTP configuration that I can find in settinsg>collection but I didn't find this.

**Comment by lwieneke** [comment]
And the issue got resolved after I installed the latest version (v1.112.1).
