### ISSUE TITLE
Default translations: Editor role missing while setting the role of a User

### ISSUE THREAD

**Issue by Chamrid** [huridocs/uwazidocs#5745]
**Describe the bug**
After activating a language with a default translation, the **Editor** role is missing and replaced by a _blank space_ while creating or updating the role of a user. An attempt to create/update a user with the role _Blank space_ (where it is supposed to be **Editor**) leads to an error labeled **Validation failed** 

**To Reproduce**
1. Add a new language that has the default translations available to your instance
2. Go to "Settings"
3. Click on the "Users" menu
4. Select a user and click on role

**Browser**
 - Google Chrome Browser on a Mac 

![Capture d’écran 2023-04-24 à 14 55 00](https://user-images.githubusercontent.com/82155887/234042765-612512f6-6575-4609-9a59-4f50e1fa5ef7.png)

**Comment by konzz** [comment]
Hi, @Chamrid I could not replicate this locally, could you provide more information? What is the language that you installed? can you replicate this on the demo instance?

**Comment by Chamrid** [comment]
Thanks @konzz , i installed **French** and i got the same behaviour on the demo instance. 
See the attached screenshot. 

![Capture d’écran 2023-04-25 à 13 51 41](https://user-images.githubusercontent.com/82155887/234298653-d0fefcbe-2282-4c1d-a510-2f07729a9fea.png)
