### ISSUE TITLE
Trim spaces from usernames when creating users

### ISSUE THREAD

**Issue by grafitto** [huridocs/uwazidocs#5779]
**Describe the bug**
Uwazi allows you to create users with spaces as usernames

**To Reproduce**
1. Go to 'Settings/users'
2. Create a user making sure username only has spaces and a password of your choice
3. Save

**Expected behavior**
Spaces should be trimmed but are not

**Comment by RafaPolit** [comment]
We have decided NOT to trim, but validate that `username` contains NO spaces.

Any space in the username input should say: "spaces are not allowed".  This will cover leading, trailing or in-text spaces.

This should only happen for creation and edition.  Login should still allow spaces to accommodate for existing usernames that could have spaces.
