### ISSUE TITLE
Languages UI, refinement iteration 

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#5811]
Split from #5716, some of the feedback provided in [this comment](https://github.com/huridocs/uwazi/pull/5716#issuecomment-1544030392) require more in-detail definitions/designs. 

Some alternatives discussed for the pending items are summarized below:

 [ ] Feedback on how many languages are being installed -> Add a filter to visualize only the selected languages
 [ ] Feedback on the installation process, it may take several seconds to install multiple languages -> Inform the user about the progress with more verbosity information,  an option could be a sequence of toast components.
[ ]  It's not clear to a new user what the "Reset" button does. -> Add tooltips at the header of the column or make the button label more verbosity
 [ ] In translations we have the label "ACTION" on the table header, but in languages the table header is empty, should this be consistent? -> Define descriptive column names for the actions.
 [ ] Mobile view, should the buttons be smaller so they fit ? -> Make the UI adaptative for mobile, transforming the action columns into actions in the actions bar

**Comment by konzz** [comment]
After a Discussion, we are going for points 1 and 2: (ignore the others)

- Feedback on how many languages are being installed -> Add a filter to visualize only the selected languages:
<img width="1313" alt="Screenshot 2023-05-11 at 22 31 53" src="https://github.com/huridocs/uwazi/assets/948117/9be57c63-88f6-4c31-9db9-70d4c9a0c3df">

- Feedback on the installation process, it may take several seconds to install multiple languages 

We have decided to update the endpoint to respond immediately to avoid the 1-minute timeout from the load balancer
