### ISSUE TITLE
Photos are broken

### ISSUE THREAD

**Issue by AhmadQadi1** [huridocs/uwazidocs#5819]
**Describe the bug**
I can't open the photos uploaded. This message appears: {"error":"file not found","prettyMessage":"\nurl: /api/files/1683836448692qc8bl6rh4e.jpeg\nfile not found","requestId":3476}

**To Reproduce**
1. Go to 'any entity'
2. Click on 'attachment'
3. See error

**Expected behavior**
Open and download the photo.
![signal-2023-05-15-125315_002](https://github.com/huridocs/uwazi/assets/95572565/8363be9a-e3f9-4a78-b9b3-ca827dbac5df)

**Screenshots**

**Device (please select all that apply)**
 - [ ] Desktop
 - [ ] Mobile

**Browser**
What browser where you using (Firefox, Chrome, Safari, etc...).

**Additional context**

**Comment by RafaPolit** [comment]
Thanks for this report.  We are looking into it.

**Comment by daneryl** [comment]
@AhmadQadi1 files should be all there now, can you confirm please ?

**Comment by AhmadQadi1** [comment]
Dear Joan,

Yes now it works for most of the attachments, but not for cases submitted
from May 12 - 15, I don't know why.

Thank you

**Comment by daneryl** [comment]
@AhmadQadi1 Im sorry but i do not find any entities with attachments for those dates, con you provide me more information ?

**Comment by RafaPolit** [comment]
Given no reply has been provided in 3 weeks, I'm closing this issue.  Feel free to re-open it or create a new one if the problem persists.
