### ISSUE TITLE
Disable "send" or "save" button on save in public forms to prevent duplications

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#5820]
**Describe the bug**
There appears to be some process in the public form that allows the user to click, click, click while waiting feedback from the server which results in apparently "duplicated" entities (which are not, just the same data, created a few milliseconds apart).

Maybe we could use the same strategy as with the entity regular save and disable the button after the user presses "send" until there is a response from the server and then enabling the button again?

This flow needs to take into account the flow of failing the captcha test and being able to resubmit without reentering all the info.

**Comment by RafaPolit** [comment]
Apparently the component is unmounted as soon as the button is clicked, so this is probably NOT the source of the problem.  Please investigate further possibilities as to how this happened.

**Comment by Zasa-san** [comment]
related to https://github.com/huridocs/uwazi/issues/5901

**Comment by RafaPolit** [comment]
This apparently is a non-issue @Zasa-san to confirm and close.

**Comment by Zasa-san** [comment]
The rendering of the `Submit` button is conditioned by the `submitting` state:

https://github.com/huridocs/uwazi/blob/899ecbe7464938f68b9ac6a72d138d46d2dce5f6/app/react/Markdown/components/PublicForm.js#L204-L226

The `handleSubmit` function is setting that state to remove the form and the `submit` button from the screen until the save finishes.

https://github.com/huridocs/uwazi/blob/899ecbe7464938f68b9ac6a72d138d46d2dce5f6/app/react/Markdown/components/PublicForm.js#L73-L90

The only thing I can think of is the order of the promise and the state change. I will do a small PR to switch that up to make sure that the absolute first thing to happen is the state change.

But I can confirm by testing with media and attachments that the form gets unmounted upon submit, and a `Submitting` message appears.
