### ISSUE TITLE
Labels display original values after a user switches to different UIs, Live translate is unavailable

### ISSUE THREAD

**Issue by serena-huridocs** [huridocs/uwazidocs#5821]
**Describe the bug**

Assigning the translation for a property name through **the Translations menu** does not yield the results expected as once a user switches to UI in a different language, the value is still displayed in English. Using **Live Translate** to change the respective **Labels** is unattainable. 

**To Reproduce**
1. Go to 'Library' while using English UI
2. Click 'entity' and check Labels
3. Switch to UI in a different language 
4. Click 'entity', go through Labels, and locate the Label that is still displayed in English
5. Click **Live translate** to change the value and make sure that there is no way to click Label to change the value

**Expected behavior**
A value is displayed as it is indicated within the Translations menu. 

**Screenshots**

Translations menu: <img width="1197" alt="Screenshot 2023-05-11 at 11 28 57" src="https://github.com/huridocs/uwazi/assets/100300126/2ec903e8-e8bc-45e1-a70f-6855c8add222">

When using UI in a different language: 

<img width="394" alt="Screenshot 2023-05-11 at 11 29 57" src="https://github.com/huridocs/uwazi/assets/100300126/bc00e1d1-738b-44bf-a07f-1092fa8a0085">

Live translate is unavailable: 

<img width="400" alt="Screenshot 2023-05-11 at 11 30 18" src="https://github.com/huridocs/uwazi/assets/100300126/23fbf515-83c6-433e-a4a1-8dfa8f705f93">

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Browser**
Chrome

**Additional context**

**Comment by konzz** [comment]
After debugging for a while, this only happens after adding a new property and until you reload the page. Probably the translations are not being updated after a template change.

**Comment by serena-huridocs** [comment]
Hi @konzz! Thanks a lot for looking into this. Apologies, I have not specified it when reporting the issue (frankly, I have simply not realised it at that point), but the translation is not displayed for the inherited properties.

**Comment by grafitto** [comment]
> Hi @konzz! Thanks a lot for looking into this. Apologies, I have not specified it when reporting the issue (frankly, I have simply not realised it at that point), but the translation is not displayed for the inherited properties.

After debugging, it seems sidepanel metadata view for entities with inherited property values reference translation template context of the entity that has been inherited from instead of referencing the context of itself.

For example:

Assume we have 2 entities: `Car` that has property __color = blue__ and another entity `Subaru` with property `My color` that inherits from `Car -> color` property, the translation will try to get `My color` translations from `Car` translation context, instead of getting it from `Subaru` translation context

**Comment by serena-huridocs** [comment]
Hi everyone! Maybe, this will help: 

Let's say, we have an instance with two languages: English and Turkish. The **person** template inherits the property **Event description** (Turkish translation: **Olay Özeti**) from the template **event**. Therefore, we assign a fairly similar property name to it, specifically, **Description of event** (Turkish translation: **Olay Özeti**). The Turkish translations are provided via the Translations menu for the two property names. 

Let's imagine that a user switches to the Turkish UI and navigates to one of the **person** entities. In this case, it would be expectable to see **Olay Özeti** as a property name along the other property names in Turkish, correct? But the sidebar panel still displays **Description of event**. 

Maybe, I am wrong, but I am thinking if the sidepanel metadata view was referring to the inherited property, it would pull either **Olay Özeti** or **Event description**, right? Instead of displaying **Description of event**?
