### ISSUE TITLE
New Settings/Menu

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5828]

**Comment by juanmnl** [comment]
_**Updated**_

For **Settings > Menu** we're going to use a table component for the items-list but adding two new impactful behaviors that will propagate in other sections that require this mechanisms:

1. row Drag'n'Drop (_this will only be applied to tables that allow order as a property_)
2. Table Groups (_a clickable row –groupHeader– that collapses/expands to show/hide its nested items_)

<img width="1440" alt="Menu - Main" src="https://github.com/huridocs/uwazi/assets/699945/373696c3-7282-4b0a-98fe-ddded51837d8">
<img width="1440" alt="Menu - Main-1" src="https://github.com/huridocs/uwazi/assets/699945/f99625b9-dc20-458c-9c69-dc7a5af6c9d5">

When selecting one or multiple items, the dynamic action bar will show the "delete" action as option.
<img width="1440" alt="Menu - multi-select" src="https://github.com/huridocs/uwazi/assets/699945/97deeb2a-cc94-4964-a782-6219d7a8100b">

Adding/editing a link or adding/editing a group will open up the drawer with its options.

**Add/edit Link**
We provide the "group" selection input as a possibility to nest the "link" on creation/edition under existing groups.
<img width="1135" alt="Screenshot 2023-08-15 at 11 38 17" src="https://github.com/huridocs/uwazi/assets/699945/c61e9cfe-0e1f-45bd-b5d1-0af8485602dd">

**Add/edit Group**
<img width="1128" alt="Screenshot 2023-08-15 at 11 38 36" src="https://github.com/huridocs/uwazi/assets/699945/86a0e027-4057-4218-afd2-41d7d23abeb6">

---

**DnD**
React-table provides a very basic d'n'd behavior, without any styling for jumping positions or landing targets, let's discuss how much we want and could push that.

Example of ideal presentation (this is just an idea):
- ghost element
- landing/drop marker
![Image](https://github.com/huridocs/uwazi/assets/699945/8e13f5f9-ad92-4d21-b11c-21c5657e79c4)

**Groups**
Groups have 2 states: collapsed and expanded.
![Image](https://github.com/huridocs/uwazi/assets/699945/6e354db8-0a8e-4aa0-8664-69e4cd958696)
![Image](https://github.com/huridocs/uwazi/assets/699945/4fb60127-8cc1-40b1-87f6-1256a4d0df4c)


[Prototype](https://www.figma.com/file/HZX8qH0Aw8WiSch3Axczrn/new-comps?type=design&node-id=345-10257&mode=design&t=5BS4CU4V9hcSb1ZH-4)

**Comment by juanmnl** [comment]
**Updated** See comment on top.
