### ISSUE TITLE
Translations Edit breadcrumbs is not using context key.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5840]
The new [EditTranslations](https://github.com/huridocs/uwazi/blob/development/app/react/V2/Routes/Settings/Translations/EditTranslations.tsx) has breadcrumbs navigation, and they are translated but not using the appropriate context key.

https://github.com/huridocs/uwazi/blob/f84d5f4399f7d53c47968a881746935d003a7bf2/app/react/V2/Routes/Settings/Translations/EditTranslations.tsx#L230

**Comment by RafaPolit** [comment]
This was probably fixed by the change of breadcrums.  Just check this and close it if it is done.

**Comment by mfacar** [comment]
> This was probably fixed by the change of breadcrums. Just check this and close it if it is done.

You're right @RafaPolit, it is fixed in #5853. I'm closing this one.
