### ISSUE TITLE
Request to improve the usability of the Uwazi "text" property box 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazidocs#5858]
**Is your feature request related to a problem? Please describe.**
As an Uwazi user, the "text" property does not provide enough space to type content. Currently, the "text" property yields a small text box that does not allow me to scroll through the text I have typed within nor does it allow me to expand the text box to see my content better. 

<img width="366" alt="Screenshot 2023-05-24 at 5 28 13 PM" src="https://github.com/huridocs/uwazi/assets/60774708/4492a4e7-2e9f-446b-a5d5-b7f82600f51e">

**Describe the solution you'd like**
 The "text" property could be a bigger text box with a scroll option to see and edit the entire text content. Alternatively, similar to the "rich text" field, it could allow users to expand the text box to the size of their choice.  @pddocs 

.

**Comment by RafaPolit** [comment]
The `text` property is meant for small text fields like names, case number, addresses.  Longer more descriptive texts should use the `rich text` type property.  That said, the names are not helpful, maybe we could re-brand the property types to `short text` and `long / rich text`, something like that to make it more clear to the admin that it's not just the added markdown and HTML features of rich text that should trigger the 'upgrade' to Rich Text?  We can also look into making another type of property called "long text" that doesn't provide support for rich-text elements?  But that would be complicating things a bit.
