### ISSUE TITLE
Creating and updating entities through the API

### ISSUE THREAD

**Issue by andreasnef** [huridocs/uwazidocs#5915]
Hi

Given that [API documentation](https://uwazi.readthedocs.io/en/latest/admin-docs/analysing-and-visualising-your-collection.html#how-to-access-the-api-for-your-instance) is limited and additional work on this currently not on the roadmap for the near future (#3785 , #5448 ), I was wondering if you could provide a short introduction to how the API should/can be used to create new as well as update existing entities (and also relationships if possible)?
And maybe a couple of specific questions:

- How is an individualized data model for entities supported through the API? Could I just send JSON data reflecting the entity's model?
- How are updates handled, i.e. can I do a PUT just of the changed/new information, or do I have to submit the entire information of the entity again?

Thanks in advance,

Andreas

**Comment by RafaPolit** [comment]
Thanks for this inquiry and sorry for the lack of API documentation.  We are aware of it and hope to provide a solution in a not-so-distant future.

As for your questions:
- Not sure what do you mean about "individualized data model".  Indeed a POST call to the entity creation endpoint with a JSON defining its properties would create an entity.  The structure of the JSON though, needs to adhere to the template metadata definition or you will receive a validation error.  I'll expand this info in the following paragraphs.
- Our update procedure is, perhaps not ideally, not adhering to the PUT definition.   Updates are POST calls to the same creation endpoint with an _id provided.  This triggers the update process.

For the time being, the most up-to-date way to have a pseudo-documentation of the API is reverse engineer the API calls made by browser while using the application normally.

If you are already familiar with this procedure, you can skip the next part.  If not, and for others that may find this useful, here are some quick tips:

- You can achieve this by using the dev tools to check the network calls that have been made (1.).  A trick I use is to clear the network stack (2.) just before clicking the "definitive" save or edit button.
- Doing so in your own instance and in the expected template will show you the exact JSON structure you will need near the top of the stack (3.) It won't always be the first, be on the lookout for POST type calls.
- If you then click on the PAYLOAD area (4.), you will see the JSON structure required for your particular template (5.)
- You can also inspect Preview or Response tabs to see the structure of the API reply
- On the Headers section you will also see the required headers to be sent to the API calls, most notably: the session cookie which is indispensable for POST operations, and the `X-Requested-With: XMLHttpRequest` which needs to be included.

For example, here's a call from the online Uwazi demo on entity creation:
![image](https://github.com/huridocs/uwazi/assets/4309019/bf37c6fe-9202-4417-b4b1-58898edcf8df)

![image](https://github.com/huridocs/uwazi/assets/4309019/6cb2016d-ccf6-4792-beee-5abf4586c0ea)

I hope this helps, it's not ideal, I'm sorry for that.  Best regards,
Rafa.

**Comment by andreasnef** [comment]
Hi Rafa

Thanks for this feedback. I would certainly vote for the proper (open)API documentation if I could, but I see roughly what is possible now. Thanks again!
Andreas
