### ISSUE TITLE
Asynchronous installation of languages

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#5933]
Split from #5811
          
- Feedback on the installation process, it may take several seconds to install multiple languages 

We have decided to update the endpoint to respond immediately to avoid the 1-minute timeout from the load balancer

_Originally posted by @konzz in https://github.com/huridocs/uwazi/issues/5811#issuecomment-1569809585_

**Comment by RafaPolit** [comment]
Please work on #5961 and #5960 (and #4841) when working on this.
