### ISSUE TITLE
Access to the guide translated in different languages

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#5953]
**Is your feature request related to a problem? Please describe.**
At the moment, the available link to the documentation from the settings area points straight to the English versions ( https://uwazi.readthedocs.io/en/latest/ ).
Therefore, access to the translations is not availble from Uwazi.

**Describe the solution you'd like**
Please, change this link to https://uwazi.io/page/9852italrtk/support

**Comment by mayeulk** [comment]
Thanks @salvalacruz , your issue helped me find these translations of the guide. My pull request addresses your suggestion.
