### ISSUE TITLE
Adding a language  not working properly until page reload

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5960]
I found this during my work on Translations v2 and testing on staging, i have tested this on the previous release to confirm it was happening before my changes.

**Describe the bug**
Adding a new language updates local redux store with the new language in the wrong format and the wrong values (in case of installing a language with predefined values), if you try to translate something you get a validation error from the server, fixed reloading the page after installing a language

**To Reproduce**
1. Create a blank state uwazi
2. Go to settings -> languages and add a new language
3. Try to live translate something
4. See Validation Error

**Expected behavior**
Should properly update the local languages and work without having to perform a page reload.

**Additional context**
As a bonus: the function that adds a language treats differently languages with and without predefined translations
https://github.com/huridocs/uwazi/blob/4f9e870274f07e0c6a3d4c87e1c7bc6d3edc70ed/app/api/i18n/routes.ts#L14-L27
Not 100% sure but this probably has to return the translations after applying the import predefined for the client to work properly without having to reload

**Comment by txau** [comment]
related/same:; https://github.com/huridocs/uwazi/issues/4841

**Comment by RafaPolit** [comment]
Will be worked on #5933
