### ISSUE TITLE
Removing a language breaks live translation until page reload.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5961]
I found this during my work on Translations v2 and testing on staging, i have tested this on the previous release to confirm it was happening before my changes.

**Describe the bug**
Removing a language sets the app in a state where its not possible to Use live translate.

**To Reproduce**

1. Create a blank state uwazi
2. Go to settings -> languages and add a new language
3. Reload
4. Try to live translate something
5. See JS error in browser console

**Expected behavior**
Should properly update the local languages and work without having to perform a page reload.

**Additional context**
This is how the store looks like after a language deletion
![delete_language_bug](https://github.com/huridocs/uwazi/assets/1386423/6dd982a3-02fb-4f5a-8d82-1f655ac88530)

**Comment by txau** [comment]
related/same https://github.com/huridocs/uwazi/issues/4841

**Comment by RafaPolit** [comment]
Will be worked on #5933
