### ISSUE TITLE
How to Display DKI Jakarta Province in the Lokasi Kejadian Entity

### ISSUE THREAD

**Issue by petkong** [huridocs/uwazidocs#5965]
Dear Huridocs,

I want to ask a few things. Associated with the **Lokasi Kejadian** entity

https://kebebasanberkesenian.uwazi.io/in/library/?q=(includeUnpublished:!t,order:desc,sort:creationDate,treatAs:number,unpublished:!f)

- **Lokasi Kejadian** >>> DKI Jakarta does not appear in the filter. It only appears in Search menu, so it doesn't exist on the Chart either.

As shown in the following chart chart:

**Lokasi Kejadian**

https://kebebasanberkesenian.uwazi.io/in/page/e5ebwy36f6t/bar-chart-2

There are only 12 provinces. For **DKI Jakarta** province, none. Even if you search, there are 14 updates of **DKI Jakarta**.

Please help me regarding this issue. Thank You

ps : Thesaury: **Lokasi Kejadian1**

Best regard,

Andri

**Comment by RafaPolit** [comment]
Thanks for the report.  We are looking into this.
