### ISSUE TITLE
Export CSV: wrong file when filtering by user

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#5997]
**Describe the bug**
If we filter entities using not only entities/properties, but also by users (shared as editor), the downloaded file with "Export CSV" is not as expected; the entities obtained do not match.

**To Reproduce**
1. Login Uwazi with an admin user.
2. Filter some entities clicking on some "shared as editor" option.
3. Click "Export CSV" and download the file.
4. If you compare the obtained file with the filtered entities, it does not match.

**Expected behavior**
The downloaded file must totally match with the filter; entities must be the same.

**Comment by fnocetti** [comment]
Check if this was already fix

**Comment by salvalacruz** [comment]
Thank you @fnocetti , it looks is working fine.
