### ISSUE TITLE
Settings V2 - buttons inconsistencies

### ISSUE THREAD

**Issue by juanmnl** [huridocs/uwazidocs#6004]
This is not a bug, per-se, but a visual inconsistency across the designs and the implementation of the buttons or button component.

After reviewing and testing the new v2 settings, we can find 2 different sizes of buttons (on the action bar) between every new section and the users & groups section. (This last one, with its "Add user" action is the only correct one)

All buttons in the action bar, table actions, drawer and modals should be that same size (XS). Not sure if tailwind declares the button size directly or indirectly through its content, but if it's the second, then all the content of the buttons should be text-xs.

<img width="1342" alt="Screenshot 2023-07-04 at 16 19 01" src="https://github.com/huridocs/uwazi/assets/699945/e69bb868-ed0f-46c2-9f7a-bbd782ff2ba9">

This should make the UI a little bit more compact.
There are still some inconsistencies with the font itself, but I think we'll need to live with them until we get rid of roboto in favor of inter, at the last stage of the V2 implementation.

Current:
<img width="1440" alt="Screenshot 2023-06-27 at 20 07 44" src="https://github.com/huridocs/uwazi/assets/699945/391ef449-7b85-4493-9b14-3a7c1885702a">

After:
<img width="1440" alt="Screenshot 2023-06-21 at 22 40 17" src="https://github.com/huridocs/uwazi/assets/699945/51dcc86b-e42e-487c-be0b-9c2e1decd3b0">

**Comment by RafaPolit** [comment]
Closing in favor of #6017
