### ISSUE TITLE
Frontend styles cleanup

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6017]
- [x] All buttons in the action bar, table actions, drawer, and modals should be "small style"
- [x] Action bar does not have the correct padding.
- [x] Change Button component vertical padding from 6px to 8px for the "small style"
- [x] Tables are missing shadow, border and rounded corners, check figrma design
- [x] Change font-size of pills from 14px to 12px
- [x] Tabs in the users section (Users and Groups) do not look like the design, (missing rounded borders, and shadow)
- [x] Checkboxes that are focused and/or checked still have the Tailwind blue and not the Uwazi primary color (indigo)

**Comment by Zasa-san** [comment]
related to https://github.com/huridocs/uwazi/issues/6004

**Comment by Zasa-san** [comment]
This changes are likely to NOT trigger an error on the image snapshots for cypress e2e. Please make sure to check the differences and update those snapshots.
