### ISSUE TITLE
 Indefinite loading when clicking a private entity connected to a public entity

### ISSUE THREAD

**Issue by hyebin-bina** [huridocs/uwazidocs#6028]
**Describe the bug**
Users fall into an indefinite loading page when clicking a private entity that is connected to a public entity.

Users can see the connection between a public entity and a private entity as below - a private entity "Bina" is hyperlinked in blue, under the "Relationship test."
<img width="357" alt="Screen Shot 2023-07-11 at 1 25 38 PM" src="https://github.com/huridocs/uwazi/assets/85096417/685351ba-c856-41e2-8a4a-110de93b232a">

When clicking the connected private entity which users do not have access to, Uwazi shows the indefinite loading page as below.
<img width="1445" alt="Screen Shot 2023-07-11 at 1 26 07 PM" src="https://github.com/huridocs/uwazi/assets/85096417/7148e742-6be7-4f63-98e4-81ef9d77696b">

**To Reproduce**
1. Create two templates: A and B.
2. Publish template A while keeping template B private.
3. Create two entities in each templates: entity a in template A and entity b in template B.
4. Create a relationship property in template A and connect the two entities: a and b.
5. Make your instance public and log yourself out of the instance to test the followings.
6. Go to the library as a non log-in user (or being a Collaborator user would yield same results), and click entity a, which is public.
7. Click entity b that is linked in entity a.
8. Uwazi will show you the indefinite loading page.

**Expected behavior**
Uwazi can show a message, e.g. This entity is not publicly available, when users try to access entities they do not have access to, rather than showing an indefinite loading page which can be misleading.

**Additional context**
A partner wants to have some templates private in their public instance as those templates are not fully ready to be open to public.
They would still like to connect some public cases to private cases, for their internal research purposes.

**Comment by RafaPolit** [comment]
We may look into an option on an on-click event:
- The system pokes the backend for permissions.  If the user has permissions, navigate or follow through with the process (it may be showing the sidepanel, for example)
- If the system doesn't have permissions, show a notification of lacking permissions

What we should look into with a higher priority is why is this not showing a 403 and why is it showing the loader infinitely (create separate issue for this)

**Comment by LaszloKecskes** [comment]
@fnocetti and I tested this, and it looks like that the back-end is properly returning a 404, therefore we are tagging it as front-end.

**Comment by fnocetti** [comment]
> What we should look into with a higher priority is why is this not showing a 403 and why is it showing the loader infinitely (create separate issue for this)

Adding to what Laszlo said, keep in mind that returning 404 instead of 403 was a design choice. We agreed that the API should not disclose the existence of an entity if the user has no permissions to see it.
On 404, the client app should assume "Either the entity doesn't exist or the user has no permissions to see it".

**Comment by RafaPolit** [comment]
It will still be interesting if the backend sent a flag that the connected data is not available to the user, and avoid link data, so that the front-end can render this as plain text instead of a hyperlink.

Our error is presenting a link to an item we “could anticipate” that will render a 404 to the navigating user.
