### ISSUE TITLE
Unify DB connection strings across scripts

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#6031]
There are several scripts in the code base (blank-state, admin-user, reindex, migrate, etc) and the connection strings they use for MongoDB is not standardized. For instance, while blank-state connects to 127.0.0.1, reindex does so to localhost.
We need to make sure that all of the scripts use the same connection strings to avoid hard to debug issues in the future. Ideally they should use the config.js file.
This may also be a good opportunity to review the parameter/option passing strategy.

**Comment by RafaPolit** [comment]
Develop together with #6030
