### ISSUE TITLE
Problem when importing CSV / Date range property

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6076]
**Describe the bug**
The CSV import does not work if:
- The template contains a property as Date Range type.
- The CSV file contains a row with a value in this property, and the range has only the initial date (suitable if you enter this value from Uwazi).

**Screenshots**
![image](https://github.com/huridocs/uwazi/assets/73410334/e2d902b8-b988-4a5f-9826-7aea7bf93425)

**Additional context**
We have tryed using these options:
21/06/2023
21/06/2023:
21/06/2023:''
21/06/2023:''"
21/06/2023:null

**Comment by fnocetti** [comment]
After debugging it was found that the date range parser is missing implementation to support open-ended ranges.
Particularly when the string `21/06/2023:` is separated by `:`, the second part results in `''` which the parser outputs as `NaN`.

**Comment by fnocetti** [comment]
The fix for this problem now allows the user to import open-ended ranges with the following syntaxes:
- `:<date>` for ranges without starting date
- `<date>:` for ranges without ending date

That adds to the usual `<date>:<date>` for complete ranges
> `<date>` is any of the supported date formats for csv import.
