### ISSUE TITLE
Creating an entity leaves the relationships v2 fields in a processing state

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#6096]
**Describe the bug**
When creating an entity, the relationships v2 fields of the template are marked as obsolete in the entity but they are never processed.

**To Reproduce**
1. Have a template A with a relationship v2 field.
2. Create an entity A1 of template A.
3. Navigate to A1 in the library.
4. The relationship v2 field shows a spinner.

**Expected behavior**
Since a freshly created entity can't have any relationships by definition, the relationships v2 fields should be assumed empty.

**Comment by RafaPolit** [comment]
But selecting Relationship Properties values upon creation *could* actually create relationships on the v2 schema, right?

**Comment by fnocetti** [comment]
That's correct @RafaPolit, but that creating relationships is not a feature in the current relationships v2 property.
I think at this point the implementation should just use the fact that there aren't any relationships, and take care of it when creating throw properties gets implemented. What are your thoughts?
