### ISSUE TITLE
Render thumbnails for media fields on library cards

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#6105]
**Is your feature request related to a problem? Please describe.**
When loading the library, if the instance has media fields displayed on cards, it will request all media files to render them. In some cases we could be sending potentially gigabytes of data without any need.

**Describe the solution you'd like**
Render a thumbnail.

**Additional context**
Initially we want to render a simple generic thumbnail. This is only for internal assets, not for external URLs.

**Comment by juanmnl** [comment]
There are two paths we can go with:

1) A placeholder with the play-icon + gray as background (or entity color shade)
2) number 1 with the addition of the video title. (usually, for accessibility purposes, this will need a short gradient behind the text so it always keeps the same contrast.

We can think of it as enhancement and start with 1, and planning on 2 for the future.

ICON: heroicon: play-solid (gray-400)

<img width="1045" alt="Screenshot 2023-08-29 at 12 10 06" src="https://github.com/huridocs/uwazi/assets/699945/ab49ab53-219b-46e7-a802-07cee80ca21e">

**Comment by Zasa-san** [comment]
I see two more problems with media fields:

-  When the user opens the sidepanel for the entity the media will be re-downloaded. This means that the user might see the media loaded on the cards, and now they have to wait again for the media to download for the sidepanel. This will happen regardless of whether we have a thumbnail or not, but having thumbnails until the user decides to see the media will mitigate this.
- If we want to also render a thumbnail on the sidepanel or entity view (which we should in my opinion) the timelinks will not work. So we should take into account what behavior timelinks should have in relation to the thumbnail approach. 

We might want to create a separate issue for the first problem. It’s not ideal that the user should download the file to see the media in the card, and then again on the sidepanel, and maybe again on the entity view. Solving this could be a lengthy development. A solution could be to serve media files with our own streaming method, so that it behaves like a link to vimeo or youtube.

**Comment by Zasa-san** [comment]
Initially we will only render thumbnails on library cards. Sidepanel and entity view will intermediately request the media elements.
