### ISSUE TITLE
Library requests allAggregations every time

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#6127]
**Describe the bug**
Unless otherwise set manually in the url, clicking on a filter in the side panel will always include the `allAggregations` flag set to `true`, meaning that it will request ElasticSearch aggregations for every aggregatable property, resulting in performance problems.
It looks like there's no reasons to need more aggregations in the library than those needed for the filters.

**To Reproduce**
1. Open Uwazi
2. Click a template filter
3. The url includes `allAggregations:!t`

**Expected behavior**
Should not include `allAggregations:!t` or should be `!f`

**Comment by fnocetti** [comment]
Downgrading the priority since there is a workaround if this is causing slow requests:

1. Locate the `q` parameter in the url of the library. E.g. `?q=(includeUnpublished:!t)`
2. Add the flag set to false after the first parenthesis. E.g. `?q=(allAggregations:!f,includeUnpublished:!t)`
3. After setting it manually, navigating through filters and the search box won't change it.

**Comment by txau** [comment]
@fnocetti I think this may be affecting the overall performance of our server when they are crawled by search engine spiders etc. I really think we should give it maximum priority.

**Comment by fnocetti** [comment]
@txau sounds fair. Raising the priority.

**Comment by fnocetti** [comment]
Fixed by #6131
