### ISSUE TITLE
Analyse and improve grouped thesauri aggregations

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#6128]
At the time of first implementing support for the grouped thesauri aggregations we were only storing the final/child thesaurus value in the entities. Needing counts for parent values, and not having them indexed resulted in this kind of aggregations:
```
"select_1.value": {
          "filters": {
            "filters": {
              "parent1_id": {                <==== bucket for parent thesaurus value
                "terms": {
                  "select_1.value": [
                    "parent_1_child_1_id",
                    "parent_1_child_2_id",
                  ]
                }
              },
              "parent_1_child_1_id": {         <==== bucket for first thesaurus child
                "terms": {
                  "metadata.localidad_de_nacimiento__ca_.value": [
                    "parent_1_child_1_id"
                  ]
                }
              },
              "parent_1_child_2_id": {.     <===== bucket for second thesaurus child
                "terms": {
                  "select_1.value": [
                    "parent_1_child_2_id"
                  ]
                }
              },
```
In this query we aggregate on the select_1 values, and then manually create one bucket per thesaurus (child or parent), where the parent is defined as the union of the children.
This can quickly grow to a very big query proportional to the size of the thesaurus. It's also likely that it may introduce some performance degradation given the amount of filters used.

That changed and now we have also the parent thesauri for every value denormalized into the entity.
This should allow us to aggregate based on the parent (for parent aggregations) instead of relying in the child/final values, with the usual `terms` construction.

After a bit of research, it was found that while the denormalization for the parent thesaurus value is stored and indexed in elastic with the entity, it's being mapped as `{ value: text, label: text }` instead of the usual `{ value: keyword, label: text }`, which is the usual for this type of data. That needs to change in order to be able to aggregate the terms over `parent.value`.

**Comment by LaszloKecskes** [comment]
+1 change, as discussed with @fnocetti: 
During the development of the solution for #5965, it was noticed that the aggregation buckets are returned in no particular order. This is relevant if one field reaches the bucket limit (200, possible for a relationship field with a lot of options), because in that case the truncation will happen seemingly random. It would make sense to sort the buckets by count, so we always show the most relevant options.

**Comment by LaszloKecskes** [comment]
After further testing: we do not even have explicit mapping for parents, the simple text mapping we've found is added by elastic dynamically when an entity has a "parented" select value.
