### ISSUE TITLE
TranslationsV2 sync creates synced records with _id as strings instead of ObjectIds

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#6133]
**Describe the bug**

**To Reproduce**
1. Configure 2 synced tenants with translationsV2 activated
2. Change a translation on the host tenant
3. Check database on the target tenant on translationsV2 collection
4. see translations being created with _ids as strings

**Expected behavior**
_ids should be ObjectIds

**Comment by LaszloKecskes** [comment]
Closing after merging the hotfix to production.
