### ISSUE TITLE
Timestamps in extracted metadata

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#6151]
Right now selections for IX are saved in files as an array of objects with this format:
```
 {
      "propertyID": "{template.property._id}", //not present for title
      "name": "{template.property.name}",
      "timestamp": "Thu Sep 14 2021 15:07:22 GMT-0300 (Argentina Standard Time)",
      "selection": {
        "text": "some text",
        "selectionRectangles":[...]
      }
 }
    
```
The timestamp is a date string, not a timestamp. We should update it to be an actual timestamp, and check if this also requires to update the IX services that use that parameter.

**Comment by RafaPolit** [comment]
We need input from @gabriel-piles to prioritize this.  Thanks!

**Comment by gabriel-piles** [comment]
@RafaPolit @Zasa-san

The external service is not affected by this change. The pdf-metadata-extractor works with all the PDFs Uwazi sends, no matter the timestamp. 

The timestamps is, indeed, used to decide which PDFs should be sent to the service.
