### ISSUE TITLE
The UI terms in Russian do not display

### ISSUE THREAD

**Issue by serena-huridocs** [huridocs/uwazidocs#6157]
**Describe the bug**
Installing the Russian language in Uwazi does not lead to the results expected. Once a user installs Russian and switches to the Russian UI (while the default translation should be available in Russian), the terms are still displayed in English. 

**To Reproduce**
1. Go to 'Languages'
2. Install Russian
3. Switch to the Russian UI

**Expected behavior**
Installing the Russian language lets one use the Russian UI. 

**Screenshots**

![Screenshot 2023-09-19 at 12 58 15](https://github.com/huridocs/uwazi/assets/100300126/cbea6a91-5dea-4d28-bdec-c0bf6e5074d4)

**Device (please select all that apply)**
 - [x] Desktop
 - [ ] Mobile

**Browser**
Chrome

**Additional context**

**Comment by Zasa-san** [comment]
@daneryl This is fixed, right?
