### ISSUE TITLE
No error shown when csv of language translation is malformed

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#6170]
**Describe the bug**
When installing a language with default translations if the csv is malformed, the app will report the operation as successful, but what happens is that the language gets added but the default translations do not.

**To Reproduce**
1. Modify the header of `contents/ui-translations/ru.csv`, change the first word `Key` to `key` in lowercase
2. Run uwazi
3. Go to settings -> languages -> add Language
4. Add Russian
5. See a successfull feedback
6. Change uwazi to use Russian
7. You can now see that everything is in English

**Expected behavior**
Default Russian translations should be imported.

**Additional context**
related #6157, #6169

**Comment by RafaPolit** [comment]
- Show an error during installation
- Add tests to detect possible errors on the translation files, since the user cannot take any action if there is an error on the CSV and, also, we need a full deploy to fix the problem.
