### ISSUE TITLE
Text referencing the same text multiple times is not possible

### ISSUE THREAD

**Issue by oleksandrako** [huridocs/uwazidocs#6174]
**Describe the bug**
While text referencing, it is difficult to highlight the same word, sentence or a paragraph twice or multiple times. When clicking on “Connect to a document” or “Connect to a paragraph” and trying to highlight the already referenced text, the cursor turns into a hand sign instead of the ibeam (vertical line) sign.

This makes highlighting or creating a text reference from the middle of already-existing reference impossible.

**To Reproduce**

1. Create a text reference in a Primary document file. 
2. Create another text reference to the same highlighted text.
3. Try to create a reference of the middle part of the already-existing highlighted text.
4. See how it does not let to do that.

**Expected behavior**
Multiple references to exactly the same word, text or paragraph are user-friendly and references to the middle of already-existing reference are possible.

**Device (please select all that apply)**
- [x] **Desktop**

**Browser**
Firefox

Please let me know if you have any questions or clarifications! 

Thank you very much,
Sasha

@RafaPolit 
cc @LuGomezV  @pddocs

**Comment by RafaPolit** [comment]
Yes, this is a bug.  We need to find a way to "un-highlight" the text or somehow make the selection process available to the editing user.

**Comment by aphilop** [comment]
Closing this as duplicate to https://github.com/huridocs/Internal-Issues/issues/157
