### ISSUE TITLE
Resetting password does not unlock an account

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6179]
**Describe the bug**
It appears that resetting the password does not unlock the account being reset.  The password appears to be reset, but the account itself is kept on the locked status until you click on the "unlock account" link sent on the email when this happened.

**To Reproduce**
1. Block your user by logging in multiple times with a wrong password
2. Reset the password (it works)
3. Try to login with the new password
4. See error (account is still locked, you cannot log in)

**Expected behavior**
This is something we should discuss, but if we decide that the only way to re-activate an account is by following the link, we should at least be able to re-send that email somehow?  Maybe resetting the password (which needs to be done with an associated email account) is enough to unblock the user?

cc @juanmnl @txau

**Comment by juanmnl** [comment]
Interesting case. There are maybe better patterns to think of but to keep it simple, for now, I'd go with the soft unblocking in the background of the reset password flow.

**Comment by hyebin-bina** [comment]
This exact scenario has been reported by one of our partners:

1. Several failed attempts "locked" the user's account
2. "Reset password" in Settings by other admin users did not work (as the account is still assumed to be locked)
3. The user could not locate the notification email in which the link to unlock the account resides

In this case, is unlocking the account from the back-end the only solution?

CC: @natasha-todi
