### ISSUE TITLE
Duplicated translations unique key when saving thesauri

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#6199]
**Describe the bug**
Some combination of group values when saving a thesauri produce a duplicated error on translationsV2
(trying to update a translation key to a one that already exists)

**To Reproduce**
1. Create a thesauri with a value "value 1" and a group with a value "value 1"
2. Modify the first value to "value 2" and save
3. Modify the group value to "value 2" and save
4. See duplicated key error

**Expected behavior**
It should save the thesauri properly with the translations modifying the "value 2" key and deleting the old one.

**Comment by LaszloKecskes** [comment]
Note: it seems that the problem is on the thesaurus side, translations v2 is working well. The underlying problem probably has been happening since forever, but we've discovered it because of the new validations, so that's a good thing.
