### ISSUE TITLE
Entity pages "back" button takes you to entity data info, not the previous page 

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6211]
**Describe the bug**
If you have entered an entity page from the library, and click the "back button" on the browser, you will move to an entity page info (from the entity you were seeing the page) which is a page you were actually never "in", and not get taken back to the library.

**Comment by Zasa-san** [comment]
You can also see this happen with regular pages and the library.

-> go to demo.uwazi.io
-> in the navbar click on "Submit a Document"
-> again i nthe navbar click on the Library button
-> Try using the back button to got to the "Submit a Document" page.

You will need to click twice to return to the custom page.
