### ISSUE TITLE
Entity remains in relationship fields after being deleted

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#6217]
**Describe the bug**
When an entity related to others gets deleted the values in those other entities keep the reference to the deleted one. This value is present in the edition of the entity with the inconsistency, if the Save button is clicked the action doesn't get completed and the buttons remain disabled. Bulk edition actions like the edition of the template fix the problem.

**To Reproduce**
1. Create an entity with any template <A>
2. Create a template <T> with a Relationship field <R>
3. Create an entity with the template T with the field R pointing to A
4. Delete entity A
5. View entity B and see the value of R, A is still in field R

**Expected behavior**
All the references to A should be removed with its deletion.

**Screenshots**

_Before deleting entity_
![Screenshot 2023-10-20 095505](https://github.com/huridocs/uwazi/assets/5322716/5ffd0cc3-1220-496a-9e1c-f83e65b35f50)
_After deleting entity A_
![Screenshot 2023-10-20 095617](https://github.com/huridocs/uwazi/assets/5322716/c6e74643-2000-40d5-8342-374ddf8a74e3)

**Comment by fnocetti** [comment]
Adding to the report, I was only able to reproduce this when the relationship property is configured to "any template".

**Comment by LaszloKecskes** [comment]
After debugging as the start of the work, I can confirm @fnocetti's observation, this happens for "any template" only.

**Comment by fnocetti** [comment]
Re-opening this issue. The fix and migration seem to work properly but they're missing a case. That is when the relationship property is configured to "any template" but by setting no content instead of `content: ''`. We need to apply the corresponding corrections and re-run the migration.
