### ISSUE TITLE
Pages list display - alphabetical order

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6223]
**Is your feature request related to a problem? Please describe.**
In the Settings side where you can create/edit/delete pages ( /settings/pages ), these are displayed in the order when they were created.
If the instance has too many pages, it's nos easy to find what you need.

**Describe the solution you'd like**
I suggest to display the pages in /settings/pages , in alphabetical order.

**Comment by Zasa-san** [comment]
This PR will list pages in a table that can be sorted https://github.com/huridocs/uwazi/pull/6380
