### ISSUE TITLE
Enable React strict mode

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#6240]
As we develop the new routes we are not having the benefits of using react strict mode https://react.dev/reference/react/StrictMode

Currently we use the React strict mode wrapper in `entry.server.tsx`, but not on the `entry.client.tsx`. This is not having any useful effects.

`<StrictMode>` can wrap the whole app or even individual components. Wrapping the entire app in `entry.client.tsx` throws a series of errors that might not be feasible to solve, and prevents the app from running. We can wrap the new routes only as an alternative to this to at least cover new code.

**Comment by RafaPolit** [comment]
Can you please enable this and report the amount of errors and the effort to fix them? Thanks.

**Comment by Zasa-san** [comment]
Right now it's not possible to enable strict mode in the client since it triggers an error internally in the `connect()` function from redux. This is likely related to the fact that we use an outdated redux version not meant to work with the latest react.

This issue itself is related to an internal call within redux that only happens when rendering for the client, which explains why we can have strict mode for SSR without issue.

The error:
```
Uncaught TypeError: this.subscription is null
	componentDidMount Redux
	React 11
	workLoop scheduler.development.js:266
	flushWork scheduler.development.js:239
	performWorkUntilDeadline scheduler.development.js:533
	EventHandlerNonNull* scheduler.development.js:571
	<anonymous> scheduler.development.js:633
	js vendor.js:16522
	__webpack_require__ main.js:8391
	fn main.js:8784
	fn main.js:9176
	<anonymous> index.js:6
	js vendor.js:16533
	__webpack_require__ main.js:8391
	fn main.js:8784
	fn main.js:9176
	React 2
	js vendor.js:14226
	__webpack_require__ main.js:8391
	fn main.js:8784
	fn main.js:9176
	<anonymous> React
	js vendor.js:14248
	__webpack_require__ main.js:8391
	fn main.js:8784
	fn main.js:9176
	<anonymous> React
	js vendor.js:14237
	__webpack_require__ main.js:8391
	fn main.js:8784
	fn main.js:9176
	<anonymous> entry-client.tsx:7
	tsx main.js:7454
	__webpack_require__ main.js:8391
	__webpack_exports__ main.js:10206
	O main.js:8512
	webpackJsonpCallback main.js:10192
	<anonymous> vendor.js:9
15 connectAdvanced.js:144
```
Triggered in `webpack://uwazi/node_modules/react-redux/es/components/connectAdvanced.js?fe33`
```
Connect.prototype.componentDidMount = function componentDidMount() {
	if (!shouldHandleStateChanges) return;

	// componentWillMount fires during server side rendering, but componentDidMount and
	// componentWillUnmount do not. Because of this, trySubscribe happens during ...didMount.
	// Otherwise, unsubscription would never take place during SSR, causing a memory leak.
	// To handle the case where a child component may have triggered a state change by
	// dispatching an action in its componentWillMount, we have to re-run the select and maybe
	// re-render.
	this.subscription.trySubscribe();
	this.selector.run(this.props);
	if (this.selector.shouldComponentUpdate) this.forceUpdate();
};
```

The best solution is to get rid of redux dependant components for V2 (like `Translate`), and progressively wrap new routes in StrictMode.

@konzz
