### ISSUE TITLE
SSRed pages not properly handling API errors

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#6263]
This is a follow-up of #6163 

Accessing non existent entities or documents can fall into one of this cases:
1. If it is an in-app navigation, it will show an infinitely loading screen
2. If it is a direct url navigation, it will show a JSON message stating that the server got a 404. The request itself will return a code 500.

This is related to missing implementation in the RouteHandler components. When they get a 404 from the server, the process will just fail. That means that:
1. If it was an in-app navigation: there's no handling of the 404 received, so the UI won't show accordingly,
2. If it was a direct navigation: The SSR utility will fail with an unhandled exception, and therefore return a 500.

**Comment by fnocetti** [comment]
This will be tackled by both teams in a joined effort:
- Backend will deal with the SSRenderer
- Frontend will review the unhandled API errors

**Comment by txau** [comment]
@fnocetti just a note on this, while the error message is informing about a 404:

> ServerRenderingFetchError: get documents/page -> Fetch returned a response with status 404.

The actual direct access is returning a 500.

**Comment by fnocetti** [comment]
@txau yes, it is noted in the issue description.

> 2. If it was a direct navigation: The SSR utility will fail with an unhandled exception, and therefore return a 500.

**Comment by txau** [comment]
@fnocetti yes, what puzzles me is why is it being reported as a 404?

**Comment by fnocetti** [comment]
> @fnocetti yes, what puzzles me is why is it being reported as a 404?

@txau that's because it's not :D Only the message says 404 because that was the unhandled promise within the server side renderer. It doesn't handle it so the ssrenderer throws a 500. That's the reason it's getting logged.
The client needs to handle the fetch error (which is a 404). That will convert the ssr request to a successful one, which will end up returning a 200. After that's done, they need to make sure they can have the srr render a 404 page (which is done by properly handling the rejection), which should also be send through the wire with a 404 code instead of a 200.

**Comment by mfacar** [comment]
#6603 is going to tackle the exception handling on the client side.

**Comment by mfacar** [comment]
#6787 includes the logic to handle errors from SSR and CSR for the derived components inherited from RouteHandler, as a result of the execution of requestState. 
To cover other kinds of SSR errors, however, using React Suspense on the top level of the application wasn't possible, because it is causing the problems described in #6819.
