### ISSUE TITLE
Pdf name not recognized error during csv import

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#6276]
It has been reported that when in a pdf name "some alphabet letters and symbols are not recognised", there is an error message "pdf not found", but the entity still imports partially, without the document.

The task is:
- make sure that the entity is not imported when an error with the file happens. This can be tricky, because if we simply lift this in front of the entity import, then that fails, then we're left with an unused file on the disk. We should probably keep track of the entity id's after the entity import, and if the pdf import fails, delete them. But discuss options with the team.
- debug this specific error, preferably with specific failing examples, if possible. In my mind, any alphabet and symbol that javascript strings and the underlying unix filesystem can handle, should be fine. Especially since uwazi is supposed to be multilingual, we should handle non-english alphabets. But, again, since languages and character sets can get difficult, discuss with the team to what extent should we be committed to this.

**Comment by RafaPolit** [comment]
Is this an issue only affecting CSV import with such names? Or uploading such a named PDF as part of the regular flow would trigger the same issue?

**Comment by LaszloKecskes** [comment]
We have not managed to recreate issue, the non-english characters are working fine. One particular way we've managed to get the error is to append spaces to the filenames when importing multiple attachments, but that is a correct error. Currently, the best guess is that there were some transient errors in the filenames that were not noticed and accidentally fixed during the renaming process. We have agreed to close down the issue for now.

@RafaPolit other flows are also working properly.
