### ISSUE TITLE
server.js potentially hiding errors on startup

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#6290]
https://github.com/huridocs/uwazi/blob/adc1c74dfb4bf79eda5ce906912ed66c8c3a0695/server.js#L10-L15

If an error occurs on line 12 it will  be ignored, which will make debugging it harder.
The reason this try / catch exists is to make a production build work locally during development and also in a production environment.

**Comment by RafaPolit** [comment]
Indeed this is the wrong approach at including a file.  Not very high priority, but probably easy to fix?

**Comment by daneryl** [comment]
Yes, probably we can just change the try catch for a check on whether the first file exists or not, ill take this one.
