### ISSUE TITLE
Properties setting up: set property name + label

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6291]
Hi, just a suggestion:

**Is your feature request related to a problem? Please describe.**
When creating templates, every property has only the option to define its label, but not a property name; so the name is created from the label. 
If the label is too long (because is a form question or something like that), property names are complex and not easy to manage in CSV exrpot, data visualizations, etc.

i.e: 
Property label = "Please add any aditional comment"
Property name = "please_add_any_aditional_comment"

**Describe the solution you'd like**
In Template creation pages, when setting up properties, add the value "Property name" before the label, and then distinguish both values.
If user leaves label in blank, then label is the same than name.

**Comment by RafaPolit** [comment]
I believe we already have this with the Translations system, maybe it's just a matter of using the right terminology in the UI so people understand that the property names are more "keys" and that a specific translation is more of a Label.

**Comment by RafaPolit** [comment]
Closing in favor of #6596
