### ISSUE TITLE
Research into better handling of audios/videos in UWAZI

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#6326]
Users are able to upload videos and audios of any format into UWAZI. This has a number of problems.

_Encoding issues_
- The user might upload a video in a format that is not widely playable on different platforms.
Right now we serve that file as is. If the user imported an .avi video file then that’s what the client will be provided for playback. It’s recommended to offer media files in at least a couple of formats to ensure that all users will be able to access the resource regardless of the browser/device they use. https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content#using_multiple_source_formats_to_improve_compatibility
- Only one resolution/bitrate. 
Users cannot control the quality of media playback. They might be on a slow connection, or simply watching the video in the library cards on a small frame. It’s inefficient to always download the video in a given quality without considering the user's connection and where in the app the video is being played. For example: we might want to use low resolution videos for library cards and the sidepanel, and allow full definition and quality controls on the entity view.

_File serving issues_
- Full downloads.
We cannot request for ranges of media files. https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests. This means that users always need to download the full media resource, even if they only want to see a portion of it. Some instances have very long media files, and that combined with the issue of not being able to change the quality for the playback, creates a problem where users are forced to download large amounts of data.
- Forced downloads.
Entities on the sidepanel and the entity view immediately request the media field’s resources. This is done without any user input, and serves to meet certain workflow needs. It’s a problem when combined with the fact that the resource has to be downloaded in full, every time it’s requested.

 &nbsp;
It’s suggested to implement functionality that allows UWAZI to:
- Serve a range of a media file so that the user will only download the needed data and be able to skip to any timestamp in a media field, without having to download the whole file. 
- Serve the file in different qualities. 
- Serve the file in a cross platform friendly format (like webm https://www.webmproject.org/about/)
- Do all of this preserving the file that the user originally uploaded, untouched.

More context for solutions:
DASH - https://developer.mozilla.org/en-US/docs/Web/Media/DASH_Adaptive_Streaming_for_HTML_5_Video

**Comment by txau** [comment]
@Zasa-san thanks for taking a look into this. Did you have the time to check for existing solutions? Maybe this is a task for more than one person and we should set it up as a team effort.

**Comment by Zasa-san** [comment]
> @Zasa-san thanks for taking a look into this. Did you have the time to check for existing solutions? Maybe this is a task for more than one person and we should set it up as a team effort.

The most important element right now is handling range requests for media files to prevent the file serving problems that tax our users with large downloads and long load times, in my opinion. For that I’m currently working on testing the handling of range requests on our files endpoint to get an understanding of how much work would be needed to solve this point.

For the encoding issues I would likely suggest using [ffmpeg](https://ffmpeg.org/): https://ffmpegwasm.netlify.app/. But that seems like a problem to solve later once we find a solution to streaming media.

I’ve looked into more integral foss solutions as well, like https://jellyfin.org/. We could delegate into a service like that the handling of media files. This would mean that installing UWAZI would also require installing this other software **just** for media files. It could also be an optional thing so that users that don’t plan on hosting media files don’t have to use it, and if they add a couple of odd media files here and there they would work as they do now.

I believe that we can solve all of these file issues without going for such a complex solution like a third party software integration. We can solve them just using range requests for media files, and ffmpeg to generate appropriate media files’ manifests in different formats/resolutions.

I’m planning on discussing all of this on a tech call so we can agree how to move forward, of course.

**Comment by Zasa-san** [comment]
I would boil down my research to two solutions:


**Solution 1:** homebrew solution using ffmpeg and creating a new endpoint to handle range requests for media files. We would need:
- Create and endpoint or modify existing ones to do range requests
- Modify our filesystem service to serve the files in chunks (I did some MVP in https://github.com/huridocs/uwazi/pull/6332)
- Implement ffmpeg to create a media transcoding service to serve media in different qualities and a universal format, like webm.

**Solution 2:** delegate to a self hosted third party media CMS. There are many of these CMS systems, like 
- https://jellyfin.org/
- https://www.mediacms.io/
- https://github.com/UniversalMediaServer/UniversalMediaServer

If we go the way of integrating a third party CMS it would be like Elastic or Mongodb: a service users need to install and spool up just for media files. I failed to find a third party service that just handles media file transcoding. Most of them are full fledged libraries that we would need to learn how to use, and consume their APIs from our own client. Even If we find a great fit I think that relying on a third party CMS for media files is risky. These softwares are not as popular as Elastic or Mongo, and media files are not such a core feature of UWAZI as searching or saving information.

I looked more into the second option using ffmpeg. It's a standard solution for handling media files in apps, and it even has a WebAssembly implementation, which simplifies things. ffmpeg is not easy, and there’s a steep learning curve. But I believe it wouldn’t be more difficult than learning the API of a CMS to figure out how to use it’s media processing and serving features. Also, ffmpeg can be used on image files, which are also a type of media that would could benefit from transcoding.

**To move forward** I would consider meeting and making a decision as to how we want media files to be developed as a feature. This will help clarify if we want to use a CMS or code our own service. It could be that we want to have a media library within UWAZI, and then a CMS would be a far better choice. @txau

**Comment by txau** [comment]
@Zasa-san thanks for the research. We probably need to conduct an assessment before making a decision.
- Is the transcoding something that happens on the fly? or are the transcoded files pre-processed?
- What other useful features do these CMS provide apart from transcoding and range requests?

**Comment by Zasa-san** [comment]
> @Zasa-san thanks for the research. We probably need to conduct an assessment before making a decision.
> 
>     * Is the transcoding something that happens on the fly? or are the transcoded files pre-processed?

No, transcoding needs to be configured and executed when a user uploads a file. When the file is saved, transcoding can begin in the background. It’s a long process that needs to be carefully configured to get the adequate results. Ideally we could make the original file immediately available for users and then use the transcoded versions once they are ready.

>     * What other useful features do these CMS provide apart from transcoding and range requests?

For what I’ve gathered they offer a library and library-like features, very similar to things encountered on Youtube or Vimeo. The only salient feature for me is that they have their own media players, so you could rely on them to play media in UWAZI by embedding the player in the UI.

**Comment by txau** [comment]
@Zasa-san thanks, this makes sense.

**Comment by Zasa-san** [comment]
Closed in favor of #6520 & #6521
