### ISSUE TITLE
Multipart/form-data POSTs have missing information in activity log entries. 

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#6347]
**Describe the bug**
Requests with a multipart/form-data body are not registering the affected resource content in the activity log entries.

**To Reproduce**
1. Create an entity
2. Go to the Activity Log
3. See that type is undefined and the body is empty

**Expected behavior**
The activity log entry must contain relevant information about the request.

**Additional context**
We are using uploadMiddleware to process the form data in the route.

**Comment by RafaPolit** [comment]
The activity log is, indeed, a crucial aspect for users and devs to have important insights into a collection.  We should fix this.
