### ISSUE TITLE
Select translations do not update on metadata

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#6350]
The issue: After changing the translations for a thesaurus, the denormalized labels on the metadata do not get updated.

Steps to reproduce:
1, create a thesaurus with any values
2, create a template with any select-type property (select, multiselect, inherited select and multiselect)
3, add an entity with a value
4, go back to the thesaurus, change the translation of the select element used on the entity
5, the translation on the entity does not get updated

Re-saving the entity resolves the issue, so the denormalization process itself works properly. We also have some functionality to update the labels, since changing the main label directly in the thesaurus (not the translations) does correctly update the default language label on the entities.
What we might not have and should be implemented is the functionality to identify the thesaurus element just based on the translation-change.

Tasks:
1, Debug and resolve the issue.
2, Write a migration to update current labels.

**Comment by RafaPolit** [comment]
@Zasa-san to check if this is still the case.  It looks like not, maybe this is now happening only on inherited properties?

**Comment by Zasa-san** [comment]
I’ve tested these flows and they work:

- Translate thesaurus item used in a select.
- Translate thesaurus items inherited via relationship from one entity to another.
- Edit a thesaurus item after using it in an entity.
- Edit a thesaurus item inherited from one entity to another via relationship.

I'm not seeing a problem with these flows. Values are updated and look correct.
