### ISSUE TITLE
Mermaid JS not displaying on Uwazi anymore 

### ISSUE THREAD

**Issue by natasha-todi** [huridocs/uwazidocs#6371]
**Describe the bug**
In 2021, we had enabled the ability to use Mermaid JS - https://mermaid.js.org/intro/ in Uwazi which required dropping some standard javascript in the pages settings and then following the Markdown syntax to create flowcharts. For reference, the usecase for Mermaid JS is the ability to visualise complex relationships such as chain of command within armed forces or an organisational hierarchy to trace the line of attribution to understand who makes decisions at the very top that lead to human rights violations. Now, when following the same instructions, Uwazi does not render the component accurately and instead displays the underlying syntax instead of a chart. cc @mennaelmassry 

**To Reproduce**
1.Log into any instance and drop the mermaid syntax along with the javascript noted here - https://docs.google.com/document/d/18IRimq5hZ3NCZZwnjE1vkqcbhTR626Trt7XJYJFErS8/edit 

**Expected behavior**
This configuration should render a flowchart that has nodes connected to one another through arrows.

**Screenshots**
<img width="1117" alt="Screenshot 2024-01-17 at 1 58 04 PM" src="https://github.com/huridocs/uwazi/assets/60774708/01a99eb1-04c9-4909-99ae-2fcf7a316c67">
<img width="1437" alt="Screenshot 2024-01-17 at 1 58 53 PM" src="https://github.com/huridocs/uwazi/assets/60774708/8d85a147-8c0b-4b0c-99f5-0d01ed384d1c">
<img width="1437" alt="Screenshot 2024-01-17 at 1 58 53 PM" src="https://github.com/huridocs/uwazi/assets/60774708/b8287fca-3c0c-484d-bc02-8010cc221818">

**Comment by RafaPolit** [comment]
We are going to look into this to see if something has changed in our implementation or if this is an issue with Mermaid.

**Comment by RafaPolit** [comment]
@meegido Can you please look into this? The Mermaid documentation may have changed a bit requiring some changes:
https://mermaid.js.org/intro/#mermaid-api

**Comment by meegido** [comment]
Hi @RafaPolit and @natasha-todi! Mermaid has updated the library. I want to update the code in [the document linked](https://docs.google.com/document/d/18IRimq5hZ3NCZZwnjE1vkqcbhTR626Trt7XJYJFErS8/edit) above. I've requested access to it. 

Meanwhile, I'm copying the JS code here so @natasha-todi, you can try it in the instance affected. Please let me know if you prefer me to do it, and we coordinate it. I'm not sure why the error is shown at the top of the page. Natasha, if you change the code in the instance affected, please kindly let me know if it also appears in that instance and also any questions that could arise. 

<img width="681" alt="Screenshot 2024-01-29 at 16 44 01" src="https://github.com/huridocs/uwazi/assets/3914161/d11a81ff-1834-414d-851b-019a51c7a488">


`**The HTML needs the tag ["pre"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) with the class "mermaid"**
<pre class="mermaid">
  graph LR
      A --- B
      B-->C[fa:fa-ban forbidden]
      B-->D(fa:fa-spinner hello);
 </pre>`



**The JS**
```
const loadMermaidJs = async (callback) => {
  const scriptSrc = 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.7.0/mermaid.min.js'; // URL for the third-party library being loaded.
  const scriptId = 'mermaidJs'; // e.g., googleMaps or stripe
  const existingScript = document.getElementById(scriptId);

  if (!existingScript) {
    const script = document.createElement('script');
    script.src = scriptSrc;
    script.id = scriptId;
    script.type = "module"
    document.body.appendChild(script);


    script.onload = () => {
      mermaid.initialize({startOnLoad: false});
      if (callback) callback();
    };
  }
};

const renderMermaid =  async () => {
  const element = document.querySelector('.mermaid');

  let graphDefinition = element.innerHTML.replace(/\r?\n|\r/g, "\n").replace(/&lt;/g, "<").replace(/&gt;/g, ">");
  graphDefinition = graphDefinition.indexOf("\n") === 0 ? graphDefinition.replace("\n", "") : graphDefinition;

  const { svg, bindFunctions } = await mermaid.render('graphDiv', graphDefinition);

  element.innerHTML = svg;

  if (bindFunctions) {
    bindFunctions(element);
  }
}

loadMermaidJs( () => { renderMermaid(); });
```

**Comment by natasha-todi** [comment]
@meegido cc @RafaPolit thank you so much for looking into this. 

@meegido I have given you access to the documentation so we can drop the updated JS there. I also tried it myself in the instance and it worked great!! Mercedes, I will also create an account for you in this db so if you want, you can test a bit more too. 

![Screenshot 2024-02-08 at 8 18 53 PM](https://github.com/huridocs/uwazi/assets/60774708/5913314d-2a4d-48a8-98be-f39a26040b84)

**Comment by meegido** [comment]
Hi @natasha-todi! Glad to hear that it worked! I will update the documentation and for sure, I will test it more in the instance.

I'll proceed then to close the issue :)
