### ISSUE TITLE
Transitive denormalization not working on relationship v2 creation

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#6378]
**Describe the bug**
When having a 2 hop query in a template, and creating a relationship that matches the second hop, the algorithm won't re-calculate the relationship fields for the entities that have that query.

**To Reproduce**
1. Have templates A, B and C
2. In template A, create a relationships v2 field with the query: A-[relType1]->B-[relType1]->C
3. Create entities A1 and B1 and create a relationship between them as follows: A1-[relType1]->B1
4. Create an entity C1 and relate it to B1 as follows: B1-[relType1]->C1
5. Check the value of the relationship field in A1.

**Expected behavior**
It should include C1 in its value since it matches the query.

**Actual behavior**
C1 is not in the value of the field

**Comment by txau** [comment]
@fnocetti is this an scenario that has been failing since the beginning and we didn't know, or is it something that just started to fail now?

**Comment by fnocetti** [comment]
@txau I have no way to know that until I properly debug it. But my best guess is that it has been failing from the beginning. Looks like one of those edge case scenarios. I fixed one during the development of #5347 but I identified this one while doing some final testing, so it wasn't worth delaying the PR any longer.
