### ISSUE TITLE
Create production instance - MongoDB > 4.2?

### ISSUE THREAD

**Issue by djhmateer** [huridocs/uwazidocs#6381]
Thank you for this project!

I've successfully built a development instance of Uwazi (WSL2/Ubuntu 22.04) using Docker for the dependencies. As others have found I needed to install mongosh and monogorestore so the db can be setup.

![image](https://github.com/huridocs/uwazi/assets/111231/481fca0d-a87b-4a90-bb15-61ede6b1c6c7)
Dev version working with Docker.

I tried building without Docker for a production instance using Ubuntu18, 20 and 22. I found that the versions didn't fit:

https://github.com/huridocs/uwazi/blob/development/README.md#dependencies

Can Uwazi run on a later version of MongoDB?  ie >4.2

**Comment by RafaPolit** [comment]
Thanks for reaching out to us.  We try to keep this dependencies as up to date as possible, sometimes breaking changes prevent us from adopting newer versions, but in this case I'm happy to report that yes, we are running our own production servers with mongo 4.4.24 and everything is working as expected.

Hope this helps, let us know if you have further concerns, doubts or problems with the installation.

**Comment by RafaPolit** [comment]
We have created the following issue to ensure that the README lists all the correct versions: #6423 .
Thanks for the heads-up.
