### ISSUE TITLE
Menu configuration is failing validation on previously existing GROUPS and its internal links

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6382]
**Describe the bug**
Existing Menus (maybe new ones as well?) are failing validation on two fronts:
- It says its expecting Type for the sublinks, which can only be type: "link"
- It's complaining about "extra properties", because for sublinks it's sending the LocalID. Usually that LocalID is purged in client before making the backend call

Maybe the grouped menu was not tested? Maybe the approach changed and we are not using the LocalID, but the existing menus already have that and, therefore, we need to still sanitize the data from the backend (or do a migration, which I would hope is not needed)

**Comment by LaszloKecskes** [comment]
Addressed via hotfix to production: #6384.
