### ISSUE TITLE
Update README with correct version dependencies

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6423]
**Describe the bug**
Currently we have the README for the repo outdated and the versions for the different dependencies are not correct:
Mongo can be used with 4.4.x
Node requires a higher version or it will fail installing some modules
We need to check the other dependencies as well

**Comment by djhmateer** [comment]
Thank you @RafaPolit  I've got a working test build using

- Ubuntu 20.04
- Node 20 using nvm latest
- ElasticSearch 7.17.6 (am guessing 7.17.17 will be okay)
- ICU
- Mongo 4.4.24
- MongoSH 2.1.3 from the same repo as above
- Yarn latest

I can post build script when I'm happy with it (and iron out any issues). Haven't put on PDFToText yet.
