### ISSUE TITLE
Difficult to determine editing row on larger screens

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6431]
On large screens, our design makes it really hard to know what row your cursor is targeting (in this case, for example) for editing:

<img width="1906" alt="image" src="https://github.com/huridocs/uwazi/assets/4309019/3d7dac29-5a80-4ab9-a255-a1581a384796">

As you can see, it's hard to determine which row you are actually interacting with.  Could we introduce a hover highlight to help visually determine which row you are at? Or maybe a striped table could be enough?

cc @juanmnl @konzz

**Comment by konzz** [comment]
Yes, it makes sense, Juanma is this in any design and we missed it, what about adding the same gray background the header has on hover?
