### ISSUE TITLE
New Thesauri UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6433]
Implement the new Thesauri UI as in the design

- Can top-level thesaurus be dragged into a group? What happens to denormalization processes?

**Comment by juanmnl** [comment]
Pretty much what we've been doing in most settings pages with the new **empty state** for tables that should propagate to any table that could find itself empty (No [x]).

**Settings / Thesauri - empty**
<img width="1440" alt="Screenshot 2024-02-07 at 20 55 53" src="https://github.com/huridocs/uwazi/assets/699945/6290d565-2e98-461c-a839-e5b72108f2c0">

**Settings / Thesauri - list**
<img width="1440" alt="Screenshot 2024-02-07 at 21 00 14" src="https://github.com/huridocs/uwazi/assets/699945/a3bdf906-c16d-4d7a-9322-3efeeee0cbea">

**Settings / Thesauri - selected (+action-bar)**
<img width="1440" alt="Screenshot 2024-02-07 at 20 59 49" src="https://github.com/huridocs/uwazi/assets/699945/c0378a7a-0903-4e3c-a80f-e1b6d42ddacf">

**Settings / Thesaurus - new (empty)**
<img width="1440" alt="Screenshot 2024-02-07 at 20 56 32" src="https://github.com/huridocs/uwazi/assets/699945/0b1f63e2-b87b-482e-8769-3966e82e8beb">

**Settings / Thesaurus - add item**
<img width="1440" alt="Screenshot 2024-02-07 at 20 56 49" src="https://github.com/huridocs/uwazi/assets/699945/ec49002b-290c-40dd-8b97-7168582d9c3d">
<img width="1440" alt="Screenshot 2024-02-07 at 20 57 03" src="https://github.com/huridocs/uwazi/assets/699945/83a64191-460e-4d7c-9e10-efad234da76f">

**Settings / Thesaurus - list**
<img width="1439" alt="Screenshot 2024-02-07 at 20 57 22" src="https://github.com/huridocs/uwazi/assets/699945/b6a340f2-81ec-448f-ad4d-5c670fd11600">

**Settings / Thesaurus - edit item**
<img width="1440" alt="Screenshot 2024-02-07 at 20 58 04" src="https://github.com/huridocs/uwazi/assets/699945/4940575b-f113-4278-9b10-f6f65d4412cd">

**Settings / Thesaurus - add group**
<img width="1440" alt="Screenshot 2024-02-07 at 20 59 18" src="https://github.com/huridocs/uwazi/assets/699945/d2ddeba6-4dc0-4e32-9252-0ab8ace35548">

**Settings / Thesaurus - list - add group + item**
<img width="1440" alt="Screenshot 2024-02-07 at 20 59 28" src="https://github.com/huridocs/uwazi/assets/699945/b638e55f-171e-4ccc-9295-c0885cd171d5">

**Settings / Thesaurus - list - group expand**
<img width="1440" alt="Screenshot 2024-02-07 at 20 58 57" src="https://github.com/huridocs/uwazi/assets/699945/1200bff2-3c29-407b-aefa-e4efcbcdcbba">

**Settings / Thesaurus - list - selected (+action-bar) item & group expand**
If moving items inside and outside is possible: we could add bulk actions to group and ungroup (those buttons are not required for this iteration)
<img width="1440" alt="Screenshot 2024-02-07 at 20 58 57" src="https://github.com/huridocs/uwazi/assets/699945/0b1cbc7e-8129-4236-a369-c6492ba02f94">

---

[Prototype](https://www.figma.com/proto/HZX8qH0Aw8WiSch3Axczrn/new-comps?page-id=14%3A10151&type=design&node-id=1220-26704&viewport=-6242%2C4506%2C0.55&t=5vuWxYzgApFs1lP1-1&scaling=min-zoom&starting-point-node-id=3207%3A48780&mode=design)

---
**There's a slight change that I'm proposing **only for the table actions/buttons**, so they become less present ("in-your-face"), but only if possible. :)

<img width="868" alt="Screenshot 2024-02-07 at 21 14 31" src="https://github.com/huridocs/uwazi/assets/699945/d4315877-f72c-4990-9226-21f095f4315a">

**Comment by gabriel-piles** [comment]
The current Thesauri UI is on charge of the Topic Classification feature!

This feature automatically suggests dictionary options for entities. The suggestions are handled using two specific windows within Uwazi's Thesauri UI. To access these windows, there are some buttons in the Thesauri UI.

Topic classification is behind a feature toggle that is activated for each object in the dictionary collection, using the following field:

enable_classification: true

For each of the dictionaries that has topic classification enabled, a button appears in the UI.

![Screenshot from 2024-02-13 16-29-24](https://github.com/huridocs/uwazi/assets/22240564/396b18ab-b6ba-42b0-a2d2-093f169bb430)


And when the new button is pressed, it redirects to "/settings/dictionaries/cockpit/{id}"


![Screenshot from 2024-02-13 16-30-06](https://github.com/huridocs/uwazi/assets/22240564/ed4dd6bb-4f4f-4d44-b44c-3e518f3a2c20)

**Comment by txau** [comment]
@gabriel-piles this is unrelated to what we are developing right now. This is meant for topic classification for paragraphs that are contained in a rich text field. Before supporting this we first need to have another feature that is a paragraph extractor and another feature that is ML over the rich text field contents.

Also, I would like no to pollute the thesauri UI with anything related to ML.

So let's ignore this for now.
