### ISSUE TITLE
Settings Relationships Type new UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6434]
[Prototype](https://www.figma.com/proto/HZX8qH0Aw8WiSch3Axczrn/new-comps?page-id=14%3A10151&type=design&node-id=1220-27378&viewport=-6242%2C4506%2C0.55&t=5vuWxYzgApFs1lP1-1&scaling=min-zoom&starting-point-node-id=3207%3A48780&mode=design)

**Comment by juanmnl** [comment]
Pretty much what we've been doing in most settings pages with the new empty state for tables that should propagate to any table that could find itself empty (No [x]).

**Settings / Relationship types - empty**
<img width="1440" alt="Screenshot 2024-02-07 at 21 48 24" src="https://github.com/huridocs/uwazi/assets/699945/a31113d0-05c3-4db0-8aac-f69ef1c04c43">

**Settings / Relationship types - new**
<img width="1440" alt="Screenshot 2024-02-07 at 21 49 07" src="https://github.com/huridocs/uwazi/assets/699945/631459e7-2ea4-41e0-b882-4e1793e7ed68">
<img width="1440" alt="Screenshot 2024-02-07 at 21 49 31" src="https://github.com/huridocs/uwazi/assets/699945/8e838d5c-8abb-4eee-948a-6d6e60f899b3">

**Settings / Relationship types - list**
<img width="1440" alt="Screenshot 2024-02-07 at 21 50 47" src="https://github.com/huridocs/uwazi/assets/699945/ebb22d4d-8ad1-4f8b-ad18-8b411ac9235b">

**Settings / Relationship types - edit**
<img width="1440" alt="Screenshot 2024-02-07 at 21 51 10" src="https://github.com/huridocs/uwazi/assets/699945/e3607a5b-318c-4a06-b316-dfc9fe53a233">

**Settings / Relationship types - selected (+action-bar)**
<img width="1440" alt="Screenshot 2024-02-07 at 21 53 41" src="https://github.com/huridocs/uwazi/assets/699945/6b1c9a8a-a415-4ca9-b53f-8a00cd52bba3">

[Prototype](https://www.figma.com/proto/HZX8qH0Aw8WiSch3Axczrn/new-comps?page-id=14%3A10151&type=design&node-id=1220-27378&viewport=-6242%2C4506%2C0.55&t=5vuWxYzgApFs1lP1-1&scaling=min-zoom&starting-point-node-id=3207%3A48780&mode=design)
