### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by nininditya** [huridocs/uwazidocs#6469]
Our database experienced error and shows zero data

![Screenshot 2024-02-13 124817](https://github.com/huridocs/uwazi/assets/159873386/9abddcc9-8df8-4666-83f4-4d85ded9c4bd)
![Screenshot 2024-02-13 125442](https://github.com/huridocs/uwazi/assets/159873386/fdb6cf65-8dca-42d9-a269-ee6956662c33)

Would you please check what's the error about and retrieve the data back?

**Device (please select all that apply)**
 - [ x] Desktop
 - [ x] Mobile

**Browser**
Chrome

**Comment by RafaPolit** [comment]
Sorry for the inconvenience.

We had an issue with Elastic Search mappings and availability in certain collections, which prevented the search engine from displaying data correctly (or altogether in your case).  Rest assured that the data was never affected and its integrity remained consistent throughout the process, this was only an issue with the search engine that populates the library.

We have taken actions to remedy some immediate problems and that should have fixed your issues.   We are still running some maintenance processes which may create some intermittence on the service.  Sorry again for the troubles.

Please let us know if you are still having issues.

**Comment by RafaPolit** [comment]
If the recent updates didn't fix your issues, please create a new one.
