### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by bhasso** [huridocs/uwazidocs#6474]
**Describe the bug**
Our database experienced an error, which resulted in disappearing data.

**To Reproduce**
1- The user signed in as an Admin.
2- The system shows an exception message, as shown in the screenshot.

**Expected behavior**
The system shall not show an exception and the user can see the stored data.

**Screensh
![UWAZI Error](https://github.com/huridocs/uwazi/assets/159911264/71871d9c-9abb-405b-8d43-ccc787bd7bdf)

**Device (please select all that apply)**
 - [ X ] Desktop
 - [ ] Mobile

**Browser**
Chrome

**Additional context**

**Comment by RafaPolit** [comment]
Sorry for the inconvenience.

We had an issue with Elastic Search mappings and availability in certain collections, which prevented the search engine from displaying data correctly (or altogether in your case).  Rest assured that the data was never affected and its integrity remained consistent throughout the process, this was only an issue with the search engine that populates the library.

We have taken actions to remedy some immediate problems and that should have fixed your issues.   We are still running some maintenance processes which may create some intermittence on the service.  Sorry again for the troubles.

Please let us know if you are still having issues.

**Comment by RafaPolit** [comment]
If the recent updates didn't fix your issues, please create a new one.

**Comment by bhasso** [comment]
Thanks for your prompt response. The issue is resolved.
