### ISSUE TITLE
Preserve extension doesn't appear to be working

### ISSUE THREAD

**Issue by ChristopherSoprano1** [huridocs/uwazidocs#6492]
I've installed the Preserve extension as per the instructions, and linked it to an instance of Uwazi using the token generated inside Uwazi and by adding the suggested URL. It was working fine for a while, but not anymore.  

**To Reproduce**
When I click on the Preserve Icon in order to store a webpage, I get an error message.

**Expected behavior**
I expect the webpage to be captured and stored on the Uwazi instance. 
![Screenshot 2024-02-16 at 13 19 45](https://github.com/huridocs/uwazi/assets/160223243/f612a338-6fbd-42d6-8fbd-aadb48abf43b)

**Screenshots**

**Device (please select all that apply)**
Mac OS.

**Browser**
Chrome for Preserve, Safari for Uwazi.

**Additional context**

**Comment by RafaPolit** [comment]
Thanks for the report, we are lookin into it.

**Comment by RafaPolit** [comment]
We have conflicting reports here, some people have this working, others are reporting problems again.  Lets review this. cc @aphilop

**Comment by aphilop** [comment]
I can verify that Preserve is working as expected when configured correctly.
I've managed to have it installed and working under:
- OS: MacOS 14.5
- Browsers: Chrome 127.0.6533.73, Vivaldi 6.8.3381.48, and Firefox 128.0.3
- Preserve extension: 0.6.0

**Comment by RafaPolit** [comment]
Closing without any reply. If you have more questions, please feel free to open a new issue.  Thanks.
