### ISSUE TITLE
Default template should not be required if you are not creating entities or uploading documents

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6493]
**Describe the bug**
We asume that there is always a Default Template configured.  This is not true for synced instances if the parent default template is not included in the sync.

All "read" procedures should not mount components that require Default Templates.

We should look into which components have this problem and ensure they are not affecting read operations, only processes of creating entities or uploading documents which assume a default template.

**Comment by Zasa-san** [comment]
Components that require default templates:

- Import CSV:
https://github.com/huridocs/uwazi/blob/cbd5310c00d45d24b6ffe60212c4790058cdc199/app/react/Uploads/components/ImportPanel.js#L31

- Document sidepanel (create or edit entities and copy from) when loading the redux form:
https://github.com/huridocs/uwazi/blob/cbd5310c00d45d24b6ffe60212c4790058cdc199/app/react/Metadata/actions/actions.js#L105

- Import PDF to create entity. Fails at the API level when trying to get the default template for the tenant:
https://github.com/huridocs/uwazi/blob/cbd5310c00d45d24b6ffe60212c4790058cdc199/app/api/entities/entities.js#L411-L414

This can be fixed at the client level by:
- Minor code changes that allow the entity sidepanel and the import csv sidepanel to load properly. They both have template selectors, so the users can choose which template to use.
- Minor code changes to `app/react/Library/components/LibraryFooter.tsx` that disables the rendering of the `PDFUploadButton` when there's no default template. In this process users cannot choose which templates to use for the uploaded PDFs, so the easiest approach is not to have the button displayed.

**Comment by Zasa-san** [comment]
We well do a stabilization fix to stop the library from braking when there is no default template, and a separate development to hide edit/create entity buttons and similar flows for instances that are synced.

**Comment by Zasa-san** [comment]
With the merge of https://github.com/huridocs/uwazi/pull/6500 the critical element of this issue is now fixed. Closing in favor of https://github.com/huridocs/uwazi/issues/6506
