### ISSUE TITLE
Add View option on Pages list

### ISSUE THREAD

**Issue by roirobo** [huridocs/uwazidocs#6542]
**Is your feature request related to a problem? Please describe.**
On _Settings > Pages_, having to go to Edit a page to see it publicly by clicking on the View button creates an unnecessary step and prone to typo errors from the user into the page's source code.

**Describe the solution you'd like**
Adding the View button option in the Pages list will ease user's navigation and reduce an unnecessary step to the user to see a page.

cc @juanmnl

**Comment by juanmnl** [comment]
That's a great catch and certainly doable @roirobo. Let's do that.
