### ISSUE TITLE
Empty metadata values should always be set to empty arrays

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#6568]
We have played with this idea for some time and the team wants to start considering it.
We want to implement that in an entity, every empty value is set to an empty array. Up to now, the "empty value" concept can be represented in one of 3 ways: unset (`undefined`), `null`, or empty array (`[]`).

**Comment by LaszloKecskes** [comment]
Added to sprint and set to high priority, since it is now worked on as the direct continuation of #6510.
