### ISSUE TITLE
IX Extractor Modal Update

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6583]
Update the create extractor with the new designs and functionality.

- When editing an extractor all templates should appear expanded and the default filter option should be "Selected"

**Comment by juanmnl** [comment]
These are the new designs for the **Metadata extractor creation modal** (Add extractor action)

We are creating a new pattern with a 2-step creator:
1. Input selection (template property)
2. Source selection (common properties - there's always at least the pdf as property)

**Select template - collapsed**
<img width="653" alt="add extractor - template - collapsed" src="https://github.com/huridocs/uwazi/assets/699945/e404ce97-6e27-4acb-a135-9346209d4e2a">

**Select template - expand**
<img width="653" alt="add extractor - template - expand" src="https://github.com/huridocs/uwazi/assets/699945/0afd2761-66bf-47b6-bffb-860226d6a27f">

**Select template - selected**
<img width="653" alt="add extractor - template - select 1" src="https://github.com/huridocs/uwazi/assets/699945/e31f8450-b951-4901-b201-1d622fc0f0e3">

**Select template - select all**
<img width="653" alt="add extractor - template - select all" src="https://github.com/huridocs/uwazi/assets/699945/074e18ae-286f-4b9a-995c-13b8d43e97e9">

---

**Select source - common properties (user can select only one)*
<img width="653" alt="add extractor - template - sources" src="https://github.com/huridocs/uwazi/assets/699945/f8ba506d-488e-4ffb-b7b3-b99a5cac80f4">

**Select source - pdf only**
<img width="653" alt="add extractor - template - source - pdf" src="https://github.com/huridocs/uwazi/assets/699945/7e5f10bc-70fd-47b9-b8bb-66d7bf762a38">

**[Designs](https://www.figma.com/file/HZX8qH0Aw8WiSch3Axczrn/new-comps?type=design&node-id=4245%3A19925&mode=design&t=v60oEdfexpd6yGSU-1)**

**Comment by roirobo** [comment]
New design looks good. Although, templates don't appear expanded and the default filter option is "All". 

Also, there's a typo in the property to select when the template is expanded: _(miltiselect)_ -should be **multi-select**.

**Comment by Zasa-san** [comment]
> New design looks good. Although, templates don't appear expanded and the default filter option is "All".
> 
> Also, there's a typo in the property to select when the template is expanded: _(miltiselect)_ -should be **multi-select**.

Hi Rodrigo! Thanks for the feedback.

What's the expected behavior with the 'All' / 'Selected' filter? Selected is meant to only show what you have ticked, and 'All' is to see all available items in the list. It should not affect if list items are expanded or not.

**Comment by roirobo** [comment]
If I understand correctly [here](https://github.com/huridocs/uwazi/issues/6583#issue-2179559910), all items should appear expanded, which is not happening. Please clarify if I have misunderstood something...

**Comment by Zasa-san** [comment]
> If I understand correctly [here](https://github.com/huridocs/uwazi/issues/6583#issue-2179559910), all items should appear expanded, which is not happening. Please clarify if I have misunderstood something...

Ok! I see what you mean now. Thanks for catching that! I will make a fix for this.
