### ISSUE TITLE
IX PDF View Update

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6584]
Update the view PDF window with the designs

**Comment by juanmnl** [comment]
For the click-to-fill input, we are moving to a new pattern where the pdf lives always in the same layer and it's not affected by the input (this will allow to have many inputs in the future without changing the position of the pdf and its selections)

**Click-to-fill HUB - collapased**
![hub - click to fill - collapsed](https://github.com/huridocs/uwazi/assets/699945/3d750718-08ae-4a00-a139-c7f17dee1f41)


**Click-to-fill HUB - expanded**
![hub - click to fill](https://github.com/huridocs/uwazi/assets/699945/5e5cf8bc-dd7d-4e7c-97ae-5de128b7ecb5)


**Click-to-fill HUB - error**
![hub - click to fill - collapsed - error](https://github.com/huridocs/uwazi/assets/699945/f2c7e501-ca5e-44fa-a4eb-09196e1c65d6)
![hub - click to fill - expanded - error](https://github.com/huridocs/uwazi/assets/699945/96f55939-2bc2-43ac-b5ae-d77f0bfff0a9)

---
**[Designs](https://www.figma.com/file/HZX8qH0Aw8WiSch3Axczrn/new-comps?type=design&node-id=4029-25203&mode=design&t=0wwKrCql94kEqll2-4)**
