### ISSUE TITLE
IX Frontend Select && Multiselect support

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6633]
Add support for 2 new properties, select and multiselect

- Backend is already working in the support, coordinate with them
- Accepting a suggestions in the case of a select should work as previous properties ( replacing one value for another)
- Accepting a suggestion for a multiselect can be:
  - a. Adding a missing option that was not previously in the value and is coming in the suggestion
  - b. Removing an option that is present in the value but not in the suggestion
- Bulk actions should do every possible action for the document(s)
- There is no "Select text & fill step", and we should not try to render the rectangles when opening the PDF.
- There will be a context property coming with the sugestion.

![Screenshot 2024-03-26 123941](https://github.com/huridocs/uwazi/assets/948117/f1dff785-d681-41a2-b8b7-39510a882dcc)
![Screenshot 2024-03-26 123951](https://github.com/huridocs/uwazi/assets/948117/267f888e-7fa2-4526-a312-c14b3d8ec45c)

**Comment by LaszloKecskes** [comment]
Reminder @LaszloKecskes: the formatter errors are not handled properly, and break the suggestion selection process. Catch errors in the suggestion selection process properly, and mark them as failed and note the errors.
