### ISSUE TITLE
Check relationType existence while saving relationships

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#6635]
Currently, the relationship saving only performs a format check to make sure that the ObjectId is well formatted. However, it does not check that the relationship type exists. There is an edge case, where we might save relationships with non existing types:
1, Open the UI.
2, Edit the relationships, select the type. Do not hit save.
3, Delete the relationship type from another browser (or even just window?).
4, Hit save on the relationships. The relationships are saved with the freshly deleted type.

Additionally, direct API calls can save any well formatted ObjectId.

The task is to add a check to the relationship saving. Note for prioritization: this is probably a low hanging fruit (small issue).

**Comment by RafaPolit** [comment]
This could also happen if someone uses the API without the client.  This needs to be validated for sure.

**Comment by daneryl** [comment]
I could not replicate this, the ui does not allow to save same name relationships.
when trying to work around this i did change the relationship name on the "deleted one but open in a form" and was not saved, server returns error.

**Comment by RafaPolit** [comment]
Just to clarify:  all this process should be done in the relationships tab of the entity view.  
- Create two entities
- Go into entity 1 and into it's relationships view
- Create a relationship using an existing relationship type 
- Delete that relationship type from another tab
- Click save

Depending on the scenarios, the relationship is probably saved (to be confirmed), and both entities now are inaccessible from the UI entity view with different types of errors.

**Comment by daneryl** [comment]
After trying again i realized that the issue can only happen when the relationship type is not used anywhere on the template or free relationships between entities.
Fixed by validating the existence of the relationship type before trying to save.
