### ISSUE TITLE
New UI table column sorting does not work well with groups

### ISSUE THREAD

**Issue by grafitto** [huridocs/uwazidocs#6636]
**Describe the bug**
Table column sorting does not work well when groups are expanded

To Reproduce

1. Load fixtures
2. Go to Settings
3. Click on Thesauri
4. Click 'Categorias' thesaurus
5. Expand all groups
6. Use column sorting to sort, you may need to click a few times.

**Expected behavior**
Sorting should be predictable

**Screenshots**

https://github.com/huridocs/uwazi/assets/8601175/6feadd73-e01b-4852-85a3-ca7dc3a2c57c

**Device (please select all that apply)**
 - [x] Desktop
 - [ ] Mobile

**Browser**
Chromium Microsoft Edge

**Comment by Zasa-san** [comment]
Thanks Mercy!
