### ISSUE TITLE
Uwazi is generating wrong URLs for pages

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#6637]
**Describe the bug**
When documents have translations with different number of pages, server side rendering generates an invalid link to a non-existent page under certain conditions.

**To Reproduce**

This was reproduced using lynx (no JS, text mode browser) so we can access the actual server side rendering. It won't work on FF or Chrome.

1. Go to https://summa.cejil.org/en/entity/cqvrli7c2q08uxr (now you locale is EN and Uwazi is rendering the English translation)
2. This document contains two translations, EN (25 pages) and ES (26 pages). Navigate to the "View" for the ES version.
3. Now you URL is https://summa.cejil.org/en/entity/cqvrli7c2q08uxr?file=9183.pdf&page=1 , that is forcing the render of the ES document while still in the EN locale.
4. Go to the last page of the document (26), now your URL is https://summa.cejil.org/en/entity/cqvrli7c2q08uxr?file=9183.pdf&page=26
5. Check the link icon to the "Next" page, which is pointing to https://summa.cejil.org/en/entity/cqvrli7c2q08uxr?page=26 , that is, removing the file, and therefor it is pointing to the non-existent page of the EN translation.

**Expected behavior**
Server side rendering should keep the param for the file or some other solution to avoid generating a broken link,

**Additional context**

More over, it would be great to:
- Check under which conditions we are logging the 404s that these wrong params generate. Are we logging all 404s for Uwazi or only when they toss a server rendering error?
- Sanitize the page param of the PDF render, as it is being used a lot to attempt injections. Probably the param should be a numeric within the range of pages and nothing else. Decide how to handle when the sanitization conditions are not met.

**Comment by txau** [comment]
@konzz are we addressing in the PR also the sanitization?

**Comment by konzz** [comment]
No, it is just fixing the broken links

**Comment by txau** [comment]
@konzz ok, could we involve someone from the backend to add the sanitization to the PR?

Also @LaszloKecskes @fnocetti please note the comment on the 404s to maybe have a technical discussion

**Comment by fnocetti** [comment]
> @konzz ok, could we involve someone from the backend to add the sanitization to the PR?

We will work the sanitization in a separate issue.
