### ISSUE TITLE
CSV Import - Select type properties with several languages

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6674]
When importing entities in several languages, content mistakes could be induced if you add an entitiy with any value in the select property, and this value not properly translated in other languages.

In example:
Template for Countries, with Country Name and Region as properties:

You can add an entity "Morocco - North Africa" in English, but telling "Marruecos - Europa Central" in Spanish, with this file:

title__en, title__es, region__en, region__es
Morocco, Marruecos, North Africa, Europa Central

**Comment by RafaPolit** [comment]
Savla, can you please confirm if those values already existed in the thesaurus?  So there is an North Africa value and also a Central Europe value?  Is this assigning different values on the different languages or this creating a TRANSLATION for North Africa as Europa Central in Spanish?

The latter would be "the expected result".  If the user decides to put Europa Central as the translation of North Africa it would yield the same inconsistency, we cannot control those scenarios.

**Comment by salvalacruz** [comment]
Hi, I've tried with a more simple scenary, and it seems it's all good, apologies, I think we can close this issue.

The test I've done is creating a template with a select property, and a tesauri with colours (and every item translated in English and Spanish).
When importing the attached CSV file, the system respects the initial value (in Spanish), even when into the file, colours are intendenly "confused".

[colores.csv](https://github.com/huridocs/uwazi/files/15133071/colores.csv)

Thank you.
