### ISSUE TITLE
Thesauri settings: order items

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6676]
When adding a new item into a thesaurus, it goes to the last position.
If you need to set this new item more to the top of the list, it is not posible to drag and drop it easily.

**Comment by RafaPolit** [comment]
It appears that this is not exclusive to the last element, actually ANY attempt to sort a children sends the item to the bottom of the list.

**Comment by konzz** [comment]
The issue with dragging children is reported already in a different issue. #6681

**Comment by mfacar** [comment]
@salvalacruz, Are the difficulties while re-ordering with drag and drop perceived when there is a vertical scroll the the list? If that is the case, there is a [known bug](https://github.com/react-dnd/react-dnd/issues/3482) in React-DnD, it is missing to fire the auto-scrolling while dragging elements outside the visible section of the screen. There are a couple of alternatives proposed in the same link that we can try to improve the experience. In the meantime it is needed to scroll to the very top/bottom of the page to fire the scrolling, keeping the row dragged until the target space is visible, or moving by parts to temporal positions, not ideal but can help until a solution is implemented.

**Comment by salvalacruz** [comment]
Yes @mfacar it's about moving an intem into a thesaurus to change its order in the list.
This temporary solution could work internally for us, but any user could be confused when trying to do that.
@konzz please, can you consider assing again Priority-High? In some contexts (longs lists of terms when order is not alphabetical but it's sensitive), setting up thesauri becames really hard.
Thank you all
