### ISSUE TITLE
Issues with dnd tables

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#6681]
Tables with drag and drop functionality present two problems.

- On tables that scroll vertically, due to the number of entries they have, dragging and item makes the vertical scroll jump around. This could be because when you stop dragging an item the UI tries to show where the item would drop, moves the adjacent rows, and messes with the vertical scroll. You can see this happen in the "Roles" thesauri in the Demo instance.

- Nested items cannot be reordered by dragging, or the dragging behaves inconsistently. This is noticeable with the last item of a group, that cannot be moved up by dragging it.

(Observed in Firefox)

**Comment by Zasa-san** [comment]
Maybe is related to this:

- In tables (did not check if dnd is a factor, but for this case is enabled), when adding a new group via the UI, the following error appears in the console:

```
Uncaught TypeError: row is undefined
    TableRow TableRow.tsx:28
    React 16
    withLazy componentWrappers.tsx:13
    promise callback*withLazy/</< componentWrappers.tsx:11
    React 15
    next index.esm.mjs:2531
    next index.esm.mjs:1294
    handleSubmit index.esm.mjs:2219
    React 23
    <anonymous> entry-client.tsx:36
    tsx main.js:7482
    __webpack_require__ main.js:8419
    __webpack_exports__ main.js:10241
    O main.js:8540
    webpackJsonpCallback main.js:10227
    <anonymous> vendor.js:9
TableRow.tsx:28:21
``

**Comment by mfacar** [comment]
At the moment it's not possible to replicate the first reported behavior. 
After a complex debugging process, the second point was solved by marking the rows as droppable in the same way that the preview row.
`Uncaught TypeError: row is undefined` is another error not related to the dragging action, a simple condition was missing.

**Comment by Zasa-san** [comment]
Other issues with dnd to keep in mind: 
#6676 
#6697 (point 2)
It could be that these issues can be solved together.
