### ISSUE TITLE
Problems with V2 thesauri

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#6699]
After #6698 we detect the following critical problems:

Thesauri needs better testing in general.

```[tasklist]
### UI issues
- [x] When creating a group the sidepanel save button should say 'Add group'
- [x] When editing a group the sidepanel save button should say 'Edit group'
- [x] Same for item create and edit ('Add' / 'Edit')
- [x] On the settings -> thesauri and on each individual thesaurus, the EDIT button has a disabled look (the border is not "deep blue") and hovering over them has no action.
- [ ] https://github.com/huridocs/uwazi/issues/7043
- [ ] https://github.com/huridocs/uwazi/issues/6696
- [ ] https://github.com/huridocs/uwazi/issues/6959
- [ ] https://github.com/huridocs/uwazi/issues/6676
- [ ] https://github.com/huridocs/uwazi/issues/6906
- [x] It is not possible to translate thersaurus names or values
```

```[tasklist]
### Validation
- [x] Please see #6696
- [x] You can delete groups and items and there is no warning as to the effect that this will have on the collection. We could add a warning before saving letting users now what items where removed and that that will have an effect on entities using those items.
```

```[tasklist]
### Testing
- [x] Unit tests for helpers
- [x] Redo E2E, it must check effects of changing thesauri (or do some of this in a unit test)
- [x] Adding thesauri
- [x] Adding groups
- [x] Editing thesauri
- [x] Editing group names and group item names
- [x] Deleting items
- [x] All of the above checked with library
```

```[tasklist]
### Code quality
- [x] There are `ts-ignore`s. Those ts warning are right, and instead of ignoring we should fix them
- [x] eslint problems. Be careful about having an environment that displays eslint errors for import sorting, arrow function styles, self closing tags, etc.
```

**Comment by salvalacruz** [comment]
I add this but I guess you already know it: when creating a new theasurus and directly adding some entities, you get this:

![image](https://github.com/huridocs/uwazi/assets/73410334/a93b4a7f-0991-473c-a3df-45c4c078515a)

To carry on, you need to create the thesaurus, write the name, save it, exit the scren, enter again and then you can add items.

**Comment by salvalacruz** [comment]
I add this issue https://github.com/huridocs/uwazi/issues/6906, regarding items and groups in thesauri configuration.

**Comment by serena-huridocs** [comment]
> I add this but I guess you already know it: when creating a new theasurus and directly adding some entities, you get this:
> 
> ![image](https://private-user-images.githubusercontent.com/73410334/335688016-a93b4a7f-0991-473c-a3df-45c4c078515a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODQ4MzIsIm5iZiI6MTcyMTM4NDUzMiwicGF0aCI6Ii83MzQxMDMzNC8zMzU2ODgwMTYtYTkzYjRhN2YtMDk5MS00NzNjLWEzZGYtNDVjNGMwNzg1MTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDEwMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NmJkNTJjN2IwYmU0Zjg1YjcyZmQzODFiYjA2ODNhMWQ5MjlmOTMzYzk5ODkyNzYzOGZiZjUxNzY0YWE0MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EsU5ml7TRsRtb238mtq6sVDpShyDZQKAyXTOsAkNZAg)
> 
> To carry on, you need to create the thesaurus, write the name, save it, exit the scren, enter again and then you can add items.

Hi @salvalacruz! A quick clarifying question regarding this behavior: does this mean that whenever a user wants to make another edit to a thesaurus, they need to exit the thesaurus modification window and then enter it once again to edit the same thesaurus?

**Comment by salvalacruz** [comment]
> Hi @salvalacruz! A quick clarifying question regarding this behavior: does this mean that whenever a user wants to make another edit to a thesaurus, they need to exit the thesaurus modification window and then enter it once again to edit the same thesaurus?

Hi @serena-huridocs I do not think we are talking about the same. My issue is about this flow:

1. Go to Teshauri and Add a new one.
2. Type a name and Save.
3. Click on 'Add Item' and type a couple of values; click Add.
4. Click 'Save' then you get an error:
![image](https://github.com/user-attachments/assets/767b1319-e4af-4416-8270-134db9fa29f0)

**Comment by serena-huridocs** [comment]
> > Hi @salvalacruz! A quick clarifying question regarding this behavior: does this mean that whenever a user wants to make another edit to a thesaurus, they need to exit the thesaurus modification window and then enter it once again to edit the same thesaurus?
> 
> Hi @serena-huridocs I do not think we are talking about the same. My issue is about this flow:
> 
> 1. Go to Teshauri and Add a new one.
> 2. Type a name and Save.
> 3. Click on 'Add Item' and type a couple of values; click Add.
> 4. Click 'Save' then you get an error:
>    ![image](https://private-user-images.githubusercontent.com/73410334/350367984-767b1319-e4af-4416-8270-134db9fa29f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODc3NTksIm5iZiI6MTcyMTM4NzQ1OSwicGF0aCI6Ii83MzQxMDMzNC8zNTAzNjc5ODQtNzY3YjEzMTktZTRhZi00NDE2LTgyNzAtMTM0ZGI5ZmEyOWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDExMTA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMDhmMjFjMDAzMTdlODVmNDdhYzcxY2JkMjlkNmQ0YTY1OTY2MDQxZGRhNDZlZjgyOTM2MGFhODg2M2ExM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dfeLP68p05t5hv-7xdhv1hmQwNEMfi01klNisuvmVY)

Thanks for the clarification, @salvalacruz! Yes, I was actually referring to the same behavior, I also saw errors with the same message when trying to edit Thesauri :) I just started thinking about potential workarounds for the issue and wrote to you to see if you are describing a possible way to avoid triggering the issue in the comment above. 
Anyway, thanks for the detailed answer!
