### ISSUE TITLE
IX Metadata extractor Multiselect backend: Data transmission issue

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#6742]
The metadata extractor for multi-select  is malfunctioning in two ways:

**Incomplete labeled data:** The data extractor is not sending all labeled data for training purposes. While prediction functionality seems unaffected, some files are being skipped during the training process.

**Missing context text:** Multiselect fields are missing context on the UI. We need to display the 'segment_text' information from the service response.

**Comment by konzz** [comment]
@gabriel-piles I have a PR for the "Missing context text", regarding "Incomplete labeled data", took me a while to understand why, but apparently, the backend only sends data entities with the main file in the language you are working on, I guess this is intended, but not sure if we want to change this behaviour.

**Comment by gabriel-piles** [comment]
@konzz It feels a bit inconsistent to train only on the files in the language you're currently working on, but the IX UI shows you files from other languages, and you can make predictions for all the files regardless of language.
