### ISSUE TITLE
Sidepanel tabs loose search term and other params such as file

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#6748]
When switching between side panel tabs while in document view search term is being cleared out.

1. Go to a document view screen
2. Search something in the full text search box
3. Click in the metadata panel
4. Notice the search term is lost

This is also happening when coming from a text search from library

**Comment by txau** [comment]
Moreover, it is also clearing out the param for the user selected file, so you can't use text tools with a file other than the default.

**Comment by RafaPolit** [comment]
More issues with this behavior:
If you search a term on a PDF (loupe icon on side panel) and you CLICK on a search result, it:
- scrolls the PDF to the results page (expected)
- does not show the search snippet on the page highlighted (unexpected)
- it CLOSES the search results and changes the sidepanel with the Metadata view (unexpected)
- momentarily, it still shows your search results number next to the loupe (expected)
- if you click on the Loupe, your search query and results are RESET, you need to start all over again (unexpected)

**Comment by oleksandrako** [comment]
https://github.com/user-attachments/assets/cc149ac9-fd28-4408-bcd4-7f11607f025a



After testing: 

1) **does not show the search snippet on the page highlighted (unexpected)** it works, but still glitchy. The search term takes time to get highlighted. See the video .

2) search icon / loupe on the right panel is not responding to click. To get results, we have to click on ‘Enter’ button on our keyboard. The search icon on the library search loupe is working as expected.
