### ISSUE TITLE
Searching in library can lead to non-existing pages

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#6749]
When an entity has more than 1 main file with different number of pages, if a search in library finds a result in a page that doesn't exist in the other language, it will generate a text result snippet pointing to the entity without specifying the file. Under this condition, navigating to that link will result in a 404 since that page does not exist in the "fall back" document.

**Comment by konzz** [comment]
After discussing it, we want the backend to return the filename along with the text snippet. To do this we will need to change how we are indexing the document's fulltext to contain the filename in the id so we can have it with the results.

Probably here:
https://github.com/huridocs/uwazi/blob/eaa700bfda4223638afc3dbdab19183c3421c84d/app/api/search/entitiesIndex.js#L86-L92

**Comment by aphilop** [comment]
@txau @konzz 
Is this still a "critical bug"?
If yes, then we should deal with it somehow.

**Comment by konzz** [comment]
No it is not critical

**Comment by txau** [comment]
@aphilop I think this is priority high because on top of tossing wrong results for the users, it is also generating wrong URLs for search engines. Maybe not critical but definitely to be addressed soon.

**Comment by daneryl** [comment]
there is no way we can replicate this or we do not understand the issue ? please provide some guidance on how to replicate @txau @konzz

**Comment by txau** [comment]
@daneryl I didn't find a specific case that points to the wrong page, but the use case is still there.

1. Go to https://summa.cejil.org
2. Go to library and switch to "Portuguese" in languages
3. Search for "In the case of Núñez Naranjo et al"
4.  One result should pop from an English document (screenshot)

![image](https://github.com/user-attachments/assets/ff0a62ed-e9aa-4c5e-a277-eea75c39cba8)

5. Select the document and check the search results on the sidebar

![image](https://github.com/user-attachments/assets/37d01a63-5db6-42c4-9776-eb38469c9f77)

6. Click on the result and you'll see it opens the "Spanish" version document, while showing the result snippets for the English version:

![image](https://github.com/user-attachments/assets/ad26dc6d-245c-449f-8270-592a21fcef14)

7. In this case the results was found on page 1, and both documents have a page 1. But if the result was found on a page that does not exist on the fallback document (Spanish), it would be pointing to a non-existing page causes a 404.

Moreover,

A. It is wrong that we are providing a link to the wrong document
B. For some reason, searching for that specific string ("In the case of Núñez Naranjo et al") tosses different results depending on the UI language:
  - In English, it shows the right document
  - In Portuguese, it shows the English document
  - In Spanish it shows no results
