### ISSUE TITLE
Colorpicker Component

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6772]
Create a color picker component using new tailwind / flowbite styles. There is no colorpicker on flowbite so we need to do one similar to what we already have.
![Screenshot 2024-05-15 151639](https://github.com/huridocs/uwazi/assets/948117/604b92b3-1855-4ba7-a353-70c7f62ed277)

Probably using the popup that we already used in other areas. @juanmnl ?
![Screenshot 2024-05-15 151713](https://github.com/huridocs/uwazi/assets/948117/685ccf9f-5dc2-4025-9993-f4e8a8436a9c)

**Comment by juanmnl** [comment]
**Color picker V2:**

<img width="192" alt="color picker" src="https://github.com/huridocs/uwazi/assets/699945/cd43991e-7698-4392-9d5b-a85ef913c55c">

<img width="1440" alt="Templates - template - color picker" src="https://github.com/huridocs/uwazi/assets/699945/ef676cc5-f2c7-4bee-872b-e7d6fae23e28">

<img width="403" alt="Screenshot 2024-05-15 at 4 25 26 PM" src="https://github.com/huridocs/uwazi/assets/699945/50830c54-a1c6-4b3d-996c-3c82edc91863">
---

@konzz Does the old Uwazi have a "color strategy" for the default colors?

**Comment by konzz** [comment]
There is a list of predefined colors but you can always put a specific one. Can you give me the list of predefined colours? because I see the designs that are different from the ones we have now.
