### ISSUE TITLE
[IX] Add "Suggestion" filter to the stats and filters panel

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#6777]
Add "Suggestion" filter: Introduce a new filter named "Suggestion" within the "non-labeled" section. This filter will allow users to specifically view files with non-empty suggestions. Both for text-based metadata extractions and multiselect/select metadata extractions.

The actual panel:

![Screenshot from 2024-05-16 15-24-15](https://github.com/huridocs/uwazi/assets/22240564/7452e88f-1afc-4f4a-9bd9-15e5c0d19eb5)

**Comment by RafaPolit** [comment]
Does this needs extra backend implementation? Or are the current filters already capable of this?

**Comment by gabriel-piles** [comment]
@RafaPolit It appears to require some backend logic
