### ISSUE TITLE
[IX] Provide visual feedback when a filter is activated and the filters side panel is closed

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6794]
When a filter is activated it can be that fewer entries are shown in the table. When the filter panel is closed, there is no visual feedback that a filter is activated giving the false impression that the shown entries are all that are available.
Providing a visual feedback should mitigate this problem.

![image](https://github.com/huridocs/uwazi/assets/102693686/479446d0-a769-4326-ab1a-1db0d14782ca)

![image](https://github.com/huridocs/uwazi/assets/102693686/cb4b8679-5c1d-4d3d-a6e3-1f5671bc121f)

**Comment by juanmnl** [comment]
We have come with a temporary solution as this may need more thought.
For now we'll add a badge to the filters button, highlighting the number of filters currently active in the filters drawer.

**Filters - active**
<img width="1440" alt="table - filters - active" src="https://github.com/huridocs/uwazi/assets/699945/1ebf200c-8831-419b-9365-7538ab883c84">

**[Designs](https://www.figma.com/design/Ypgf1qGtcxgMJEgWchoqTx/temp---06.24?node-id=6602-30120&t=yoYHxIR7uFFmNbX4-4)**
