### ISSUE TITLE
[IX] Thesauri selection on side panel cannot take the entire screen: the background PDF is hidden, it also renders as a blank page until you close and open again.

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6795]
When the options list is long enough it takes all the "PDFSidepanel" height and you cannot see the PDF content, this makes it hard to select options while reading the contents of the PDF. There is also a bug when this happens that the PDF does not render even after you close the options panel.

![Screenshot 2024-05-22 141820](https://github.com/huridocs/uwazi/assets/948117/41d23f65-e860-4a3a-b4e1-04137a5b6dd7)

**Comment by juanmnl** [comment]
The HUB should open at a max-height of 50% of the drawer and make the body of the content scrollable on overflow.
It should also have a min-height of 50%  so it doesn't shift size when few or no values are present.

<img width="700" alt="hub - open 50%" src="https://github.com/huridocs/uwazi/assets/699945/02d9891b-8cfe-4321-9749-0fc9ecf50c60">

<img width="700" alt="hub - no values 50%" src="https://github.com/huridocs/uwazi/assets/699945/551f7626-ddda-418b-aee9-d72a86564da5">
