### ISSUE TITLE
[IX] Process can get stuck in "canceling"

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6796]
Sometimes when canceling the training / get suggestions process, the system gets stuck in "canceling" state that never ends.

**Comment by gabriel-piles** [comment]
When training fails, the service seems to send a message indicating failure (with success set to false), but Uwazi appears to ignore this state, preventing the training process from completing

**Comment by daneryl** [comment]
This was never Replicated, Reopen if needed.
