### ISSUE TITLE
[IX] Provide additional information in the Current Value/Suggestions column for group entries

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6802]
The currently provided information (e.g. 44 Suggestions) in the Current Value/Suggestions column for group entries does not provide accurate information about the actual content of the group status. "44 suggestions" can be misleading, as you can have empty suggestions that suggest you "zero out" a value, and it's still labeled as suggestion.  Some more detailed information would give better overview of what a user should expect within a group entry.

**Comment by aphilop** [comment]
Depending on what is possible to show, the suggestion is to provide additional textual information as illustrated in the first row:

![2024-06-18_10-36_1](https://github.com/huridocs/uwazi/assets/102693686/1ebadf6b-7d1a-439f-933b-5fc61c948c46)

cc @konzz

**Comment by konzz** [comment]
@txau  @aphilop  is this ok or without colors?

![Screenshot 2024-06-24 141028](https://github.com/huridocs/uwazi/assets/948117/25d7d8c6-0714-4e78-8b12-2d66f9a077fb)

**Comment by txau** [comment]
lgtm
