### ISSUE TITLE
[IX] Update the numbers in the Stats & Filters side panel in real time with the updates of model training/finding suggestions

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6804]
When an extractor is training/finding suggestions and the Stats & Filters panel is open, the numbers that provide information about the results do not update in real time, the user has to close the panel and reopen it to see updated numbers. 

<img width="984" alt="Uwazi_—_Settings_•_RightDocs" src="https://github.com/huridocs/uwazi/assets/102693686/95c01cd5-061b-4922-b586-b6f7cbe6ea16">

After closing and reopening the panel:

<img width="978" alt="image" src="https://github.com/huridocs/uwazi/assets/102693686/bd8a7a57-935a-41b7-b72f-d322e2329e54">

**Comment by txau** [comment]
This needs revisiting:

1. When launching the training, it should change everything to obsolete automatically.
2. While training, some indicators are off. I think we have redesign the filters.

LABELED.... AMOUNT
Accuracy X%

Match
Mismatch
No context
Obsolete
Error

NON LABELED..... AMOUNT
Pending X%

With suggestion
No suggestion
No context
Obsolete
Error

**Comment by aphilop** [comment]
Will be handled with #7085
