### ISSUE TITLE
[IX] Provide visual cue to indicate a table row hover state

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6806]
When a user interacts with table rows, it's helpful to show visual signs of their interaction.
By adding a hover state — where a row changes appearance when the cursor is over it — can help users to keep track of where they are in the table, especially when they need to interact with actionable items.

![image](https://github.com/huridocs/uwazi/assets/102693686/13e3c85e-00a6-47d4-a0d8-66c2abc1ece6)

**Comment by juanmnl** [comment]
Table row:

**Hover** add gray-50 as background (could be very mild, if so try 100)
<img width="1440" alt="Templates - row - hover" src="https://github.com/huridocs/uwazi/assets/699945/ae893f35-3ffd-49cd-bb4d-45f18f7313a7">

**Active** add indigo-50 as background (could be very mild, if so try 100)
<img width="1440" alt="Templates -  row - active" src="https://github.com/huridocs/uwazi/assets/699945/fd3e03de-8270-4efa-83a3-a39201333766">
<img width="1440" alt="Templates - row - active" src="https://github.com/huridocs/uwazi/assets/699945/05edeac1-58d0-488e-933a-8eb58a442aa4">
