### ISSUE TITLE
[IX] When a group item is expanded in one page, the group item in the same position in any other page stays open as the user turns through the pages

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6812]
Expand a group in one page and then turn through the pages. The group item in the same position stays opens in any page. Group items must be shown as expanded only if the user has perform this action.

**Page 1**
<img width="980" alt="image" src="https://github.com/huridocs/uwazi/assets/102693686/58467ece-85a7-48b6-929e-cd2fb4641d2e">

**Page 2**
<img width="980" alt="image" src="https://github.com/huridocs/uwazi/assets/102693686/25604eec-54a5-4a99-b71c-5f44182a186c">

**Comment by RafaPolit** [comment]
Being worked as part of #6780
