### ISSUE TITLE
[IX] Training is returning "no context"

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6815]
There are cases when no context information is provided and the column "Context" displays the text "no context", while in other cases there seems to be context information.

**No context**
![image](https://github.com/huridocs/uwazi/assets/102693686/f0f58bfc-6f20-43a2-a1ee-aa34011badb1)

---

**Context provided**
![image](https://github.com/huridocs/uwazi/assets/102693686/3bad36d2-d4fd-469a-87f7-f3b043e07ed9)

**Comment by txau** [comment]
Moreover, there seems to be the same context for all suggestions, ie:

![image](https://github.com/huridocs/uwazi/assets/489831/58ef1e3e-f352-4b96-923c-0218269818e4)

Same context is provided for both suggestions, while in the document it is clearly stated that "Item 2" is a correct suggestion, but that particular context is not provided:

![image](https://github.com/huridocs/uwazi/assets/489831/0444fd45-293f-4314-bd31-1fbb5991e4b2)

**Comment by txau** [comment]
This has been discussed with @gabriel-piles and also diagnosed.

The cases with "no context" seem to be errors, in the example, because the files are missing.

Returning the same context is a matter of how the models select the context. This depends on the ML model, so we can close the issue here.
