### ISSUE TITLE
[IX] The calendar component is not fully rendered

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6817]
When trying to edit a suggestion date by opening the calendar component, this is not fully rendered thus making it difficult to change the date.

<img width="743" alt="image" src="https://github.com/huridocs/uwazi/assets/102693686/21729453-4625-4a14-a776-988f247796aa">

**Comment by konzz** [comment]
@aphilop could you specify the OS and browser?
I tested this on windows
Chrome:
![Screenshot 2024-06-18 023306](https://github.com/huridocs/uwazi/assets/948117/8f821192-0bfe-40c9-bc39-b6924065281f)
![Screenshot 2024-06-18 023313](https://github.com/huridocs/uwazi/assets/948117/e814b15c-c347-467c-9c66-6f0009690740)
Firefox:
![Screenshot 2024-06-18 023326](https://github.com/huridocs/uwazi/assets/948117/3fb21286-3751-48a4-9d84-942cca156a50)
![Screenshot 2024-06-18 023318](https://github.com/huridocs/uwazi/assets/948117/e0a90699-afb7-4d4f-8e1f-b89648bbf0a0)
Edge:
![Screenshot 2024-06-18 023410](https://github.com/huridocs/uwazi/assets/948117/4f161988-0322-4e19-b148-2d49bc1e2237)
![Screenshot 2024-06-18 023358](https://github.com/huridocs/uwazi/assets/948117/3503cded-a159-4c11-b7d2-8d113f5d06a2)

**Comment by aphilop** [comment]
@konzz Sorry for not providing this information from the beginning!

I tested again and the problem persists with Safari 17.5 (19618.2.12.11.6) on macOS Sonoma 14.5 
<img width="977" alt="Screenshot 2024-06-17 at 20 04 35" src="https://github.com/huridocs/uwazi/assets/102693686/de85c8e0-c32f-4455-999c-60a8e9e6e48f">

---

With Firefox 127.0 on macOS Sonoma 14.5 looks however ok:
<img width="925" alt="Screenshot 2024-06-17 at 20 07 07" src="https://github.com/huridocs/uwazi/assets/102693686/f103149e-8ca9-46cb-9d25-cb37411b05e5">


So it seems to be a Safari specific problem. I hope this helps.

**Comment by txau** [comment]
This seems to be a bug in either safari or the calendar lib. Closing for now.
