### ISSUE TITLE
Custom landing page doesn't get results when the URL contains a valid search

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#6822]
**Describe the bug**
The home page doesn't show results when the custom landing page includes a filter with encoded chars. For example, a filter by template.

**To Reproduce**
1. Go to the Library on an instance with entities, and apply a filter by a template also with entities.
2. Verify that the search has more than one result and copy the URL in the address bar.
3. Go to Settings/Collection.
4. Paste the copied URL into the field `Custom landing page` and save the changes.
5. Go to the Uwazi link to go to the home page.
6. Check that there are no results.

**Expected behavior**
The results on the home page must match with the results of step 1.

**Comment by Zasa-san** [comment]
I did a quick test on this in the demo instance and it seems to be working when filtering by a template. Are there any specific ways in which this filter needs to be applied or copied?

**Comment by mfacar** [comment]
@Zasa-san, I just tested it on demo and it doesn't work, for example, after changing the Landing Page to `/en/library/?q=(allAggregations:!t,filters:(),from:0,includeUnpublished:!t,limit:30,order:asc,sort:title,treatAs:number,types:!(%2762e909bbf77c451df38e95da%27,%275bfbb1a0471dd0fc16ada146%27),unpublished:!f)` and go to Home through the link or directly to `https://demo.uwazi.io/` it shows the library but without results as it is in this screenshot

![image](https://github.com/huridocs/uwazi/assets/5322716/bba90415-49d1-4335-aa13-69c433091311)

The expected output was [this search](https://demo.uwazi.io/en/library/?q=(allAggregations:!t,filters:(),from:0,includeUnpublished:!t,limit:30,order:asc,sort:title,treatAs:number,types:!(%2762e909bbf77c451df38e95da%27,%275bfbb1a0471dd0fc16ada146%27),unpublished:!f))

**Comment by mfacar** [comment]
For the record, after testing with @Zasa-san, we found that the issue is observable in Chrome browsers when the search params are copied from the address bar where the URL is already encoded, a behavior that is not true for Firefox.

**Comment by salvalacruz** [comment]
Hi, I think this issue needs to be checked in staging:

Right now, using the instance https://right.staging.uwazi.io/, I'm not allowed to paste an URL in the Custom landing page at Collection settings: 

![image](https://github.com/huridocs/uwazi/assets/73410334/c23751df-97b2-4d5f-9530-6944c2b44e48)

**Comment by Zasa-san** [comment]
> Hi, I think this issue needs to be checked in staging:
> 
> Right now, using the instance https://right.staging.uwazi.io/, I'm not allowed to paste an URL in the Custom landing page at Collection settings:
> 
> ![image](https://private-user-images.githubusercontent.com/73410334/336545892-c23751df-97b2-4d5f-9530-6944c2b44e48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjIzNzksIm5iZiI6MTcxNzUyMjA3OSwicGF0aCI6Ii83MzQxMDMzNC8zMzY1NDU4OTItYzIzNzUxZGYtOTdiMi00ZDVmLTk1MzAtNjk0NGMyYjQ0ZTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDE3Mjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYzIwOGQ3MzI2ZDY1ZjczZWQ2YTJmMGRhZDJiNjc5OWM2M2I5YjE3ZDM0NzQzNzdjMzJjOGFhNjM3MjcyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UgvCFgEuMyZO2NgSVdZMczBXWr2VDchuw2-X_nV6NZY)

Thanks Salva for reporting this! I can confirm this problem on other staging instances. I think this could be a problem with an update that recently occurred in our sating instances configuration. I will reach out to the infra team to confirm.
