### ISSUE TITLE
Update MongoDB to V5.  V4.4 is EOL

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6831]
We need to upgrade MongoDB to V5 (at least), and test locally, on CI and coordinate with infra the deployment process.

**Comment by fnocetti** [comment]
The PR I just merged modifies the CI config so it uses MongoDB 5.0.27. Everything went green and I couldn't find problems during smoke testing. 
I'm closing this. Infra should work in their own issue, and if we find anything to fix we can open a new one.
