### ISSUE TITLE
[Paragraph extraction] View/manage extractors

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6840]
A UI is needed for:
- Displaying all created extractors with relevant information
- Managing (selecting > deleting) available extractors

**Comment by juanmnl** [comment]
We start on a new route in the settings panel: "Paragraph Extractor" and then just like any other extraction main table.
OnSelect the dynamic bottom bar shows the delete button for one or many extractors.

<img width="1440" alt="PX Dashboard - Main" src="https://github.com/huridocs/uwazi/assets/699945/c6febac7-3389-48fb-9652-69616e93ca12">

**Comment by josh-huridocs** [comment]
@juanmnl can share a link for the designs?
