### ISSUE TITLE
[Paragraph extraction] Create a new extractor

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6841]
A UI is needed for creating/configuring/saving a new paragraph extractor.

**Comment by juanmnl** [comment]
From the **add extractor** button we launch a modal that has two steps:
1. Select a valid target template where the values of the extraction will be extracted
2. Select the template or templates that will trigger a paragraph extraction

**Target template - empty**
<img width="548" alt="add p  extractor - target template - initial" src="https://github.com/huridocs/uwazi/assets/699945/b68ec7e4-ff49-4000-a3d3-bb42fdfb86c8">

**Target template - template(s) + select**
<img width="548" alt="add p  extractor - target template - valid templates" src="https://github.com/huridocs/uwazi/assets/699945/0c69cee6-5697-438f-abc8-287f9a827391">
<img width="548" alt="add p  extractor - target template - valid templates - select" src="https://github.com/huridocs/uwazi/assets/699945/3adeaf43-3ec4-4061-a15a-a8e8ed9f55b1">

**Extraction template - list + selected + show selected only**
<img width="548" alt="add p  extractor - template" src="https://github.com/huridocs/uwazi/assets/699945/a8407760-2117-438f-bea6-6d247f46bc4f">

<img width="548" alt="add p  extractor - template - selected" src="https://github.com/huridocs/uwazi/assets/699945/3100f287-9ed1-4079-9994-abb2b1d88f5c">

<img width="548" alt="add p  extractor - template - show selected" src="https://github.com/huridocs/uwazi/assets/699945/27db7e85-6de8-4828-8d92-3c86369d82f1">

**[Designs](https://www.figma.com/design/Ypgf1qGtcxgMJEgWchoqTx/temp---06.24?node-id=6610-48688&t=yoYHxIR7uFFmNbX4-4)**
