### ISSUE TITLE
[Paragraph extraction] View the results of an extractor

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6842]
A UI is needed for viewing the results (entities/paragraphs) of an extractor

**Comment by juanmnl** [comment]
This is a 2 level nested navigation (making it 3 in total with the main dashboard of extractors), where in the second level we show a list of the entities that have gone through the extraction process, and on the third we show the actual extracted paragraphs for each one, with an overview (drawer) of the generated entity itself.

**Entities list**
<img width="1440" alt="entities list" src="https://github.com/huridocs/uwazi/assets/699945/a69a4465-0cc4-44af-9e72-13fd8dd547f5">

**Paragraphs list + w/drawer**
<img width="1440" alt="paragraphs list" src="https://github.com/huridocs/uwazi/assets/699945/e440992d-6efe-4bb5-84eb-fb37467cb2c1">
<img width="1440" alt="paragraphs list - entity" src="https://github.com/huridocs/uwazi/assets/699945/395e504a-6c45-4e42-b6ab-0e582abef745">


**Drawer - Entity**
<img width="610" alt="drawer - entity" src="https://github.com/huridocs/uwazi/assets/699945/a934aece-f920-4449-9458-0bf4ec272b7c">


**[Designs](https://www.figma.com/design/Ypgf1qGtcxgMJEgWchoqTx/temp---06.24?node-id=4448-47002&t=yoYHxIR7uFFmNbX4-11)**

**Comment by aphilop** [comment]
@juanmnl 
Can you please provide a design solution that illustrates how the breadcrumb (eg. Paragraph extraction > cases) and the title (eg. paragraphs for cases) look like when there are more than one entity selected during the extractor creation process?
