### ISSUE TITLE
Date picker CSS problems

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6845]
**Describe the bug**
![image](https://github.com/huridocs/uwazi/assets/4309019/0aefb277-fde3-4a90-8d75-3e42a0295162)
This is the library calendar.  Maybe some of the CSS for the Settings calendars affected this?
cc @konzz @Zasa-san @mfacar

**Comment by mfacar** [comment]
@RafaPolit, there is an open related issue (3672) in Hacker0x01/react-datepicker. The only workaround I found on the internet is to extend the styles to fix it locally. 

cc. @konzz, @Zasa-san

**Comment by RafaPolit** [comment]
We wait for them to fix it then.
