### ISSUE TITLE
Menu items dissapear from the UI

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6848]
From time to time (not often), menu items dissapear from the screen in the UI.

Apologies, I can not specify the flow to get the error, it seems it happens ramdonly.

**Comment by RafaPolit** [comment]
Which menu items are these? Manually created Menus inside the top-banner? The "hamburger" menu on mobile? The Language menu?  

Does this happen in multiple collections? Only one? Do these collection(s) have custom CSS that could be overriding the colors and "matching" the background? Are these menus with long text that could overflow their area?

Please provide some more context, as there is very little to go by here.  Maybe remember to take a screen capture the next time this happens?

Thanks.

**Comment by salvalacruz** [comment]
I mean about the top menu that can be set up from '/settings/navlinks'.

It happens in desktop enviroment (I have not tried with mobiles), with Chrome and Brave navigators, and in several instances with different CSS styles. It does not seem a question of colours, it totally dissapear.

I apologize again, I am sure it happens but I can not explain better how is the flow to replicate the problem.

I could explain you better if we talk. 

Thanks!

**Comment by RafaPolit** [comment]
Found the issue:

This happens when you SAVE on settings -> collection.  Somehow, the store or atom loses the menus upon the reply of the server.  If you refresh, the system reloads normally the links.  The data is not destroyed, but it's a scare when saving the collection to lose all the menus.
