### ISSUE TITLE
Uwazi allows users to create thesauri with the same labels

### ISSUE THREAD

**Issue by serena-huridocs** [huridocs/uwazidocs#6853]
**Describe the bug**
A user can add thesauri with the same labels while doing it in the template creation menu. 

**To Reproduce**
1. Go to 'Template'
2. Click add Thesauri
3. When adding new Thesauri by clicking the button on the bottom panel, a user can add thesauri with the same names. The thesauri with the same names are not displayed on the Thesauri list on the Select property.
4. Navigate to the Thesauri and find Thesauri with the same names.

![Screenshot 2024-06-03 at 15 08 08](https://github.com/huridocs/uwazi/assets/100300126/f9dc1d32-3cdf-451e-afcc-15a62b86f0dc)

In the screenshot, you can see three Thesauri with the same names: **Şehir**.

**Expected behavior**
Uwazi does not allow users to create the Thesauri with the same names. 

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Additional context**
A user was having some issues with the internet connection while adding thesauri.

**Comment by RafaPolit** [comment]
We cannot reproduce this.  The only way this happens is if you accidentally append spaces after the name.  Can you please confirm? Thanks.

**Comment by serena-huridocs** [comment]
I confirm. The thesauri were created by a user from the partner's team, and I made the conclusion based on what was displayed on the screen. My apologies, I am closing the issue. However, from a UX perspective, it may be worth disabling the creation of thesauri which practically have the same names except for an additional space symbol put after the name.

**Comment by txau** [comment]
we definitely have several places in which trimming spaces would have prevented problems. I'll open an issue about it.

**Comment by serena-huridocs** [comment]
> we definitely have several places in which trimming spaces would have prevented problems. I'll open an issue about it.

thank you a lot @txau 🙏
