### ISSUE TITLE
[IX] Sticky footer for multis-selects appears atop of relevant information

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#6864]
As you can see in the image bellow, the footer for selecting the properties appear over the document hiding:
- The document scroll bar
- The last part of the last page of the document

![image](https://github.com/huridocs/uwazi/assets/489831/2a9a336e-2dbd-4334-b2c6-2d59201159e8)

**Comment by RafaPolit** [comment]
cc @juanmnl
