### ISSUE TITLE
Uwazi switches to English as a result of user interaction with Thesauri

### ISSUE THREAD

**Issue by serena-huridocs** [huridocs/uwazidocs#6870]
**Describe the bug**
Uwazi switches to English from the default language after a user exits the Thesauri creation menu.

**To Reproduce**
1. Navigate to the UI language dropdown menu and choose a language other than English
2. Navigate to Thesauri
3. Open any thesaurus 
4. Exit the thesaurus modification menu
5. Now you can observe that Uwazi switched back to English. Now you need to click the dropdown to switch to a language of your choice once again.

**Expected behavior**
Uwazi does not switch to English after you interact with Thesauri.

**Screenshots**

Our default language is Turkish and we mainly use Turkish while working with Uwazi.

![1st screenshot](https://github.com/huridocs/uwazi/assets/100300126/980534b3-09d9-4c1f-9f2b-057e347e3070)

Exiting the Thesauri creation menu results in switching to English, which is quite inconvenient and confusing.

![2nd screenshot](https://github.com/huridocs/uwazi/assets/100300126/49262093-9ee0-419d-9ae4-c3c39a352e0f)

**Device (please select all that apply)**
 - [x] Desktop
 - [ ] Mobile

**Browser**
Chrome

**Additional context**
This is potentially related to #6843 https://github.com/huridocs/uwazi/issues/6843. So if the fix for #6843 covers this problematic behavior, don't hesitate to close this issue.

**Comment by mfacar** [comment]
@serena-huridocs, as you have pointed, this bug is somehow related to #6843, which is already solved, however, a leftover problem, in this case, is that when navigating to the edition of a thesaurus is losing the language in the URL. I opened #6895 to work on this.
