### ISSUE TITLE
Move Sync login logic only if LastChanges has items

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6873]
Currently, Sync process logs in once per cycle, independent of finding changes or not.

Ideally, this should be more evolved and actually only log-in if the changes affect the child instance (and could even keep the cookie to avoid new login), but, for the time being, we can move this logic further down the stream to avoid logging in more than once per second.

**Comment by txau** [comment]
related: https://github.com/huridocs/Internal-Issues/issues/118 https://github.com/huridocs/uwazi/issues/6158
