### ISSUE TITLE
Split cypress e2e

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#6900]
Like we do with puppeteer legacy tests. The goal is to run cypress tests in parallel and isolate flaky tests + reduce time of runs.

**Comment by txau** [comment]
I'm  running quick test for this and seems to be working fine. I split the suites in 3 different tasks:

- BASE: for the tests in the base folder (spec: "cypress/e2e/*.cy.ts")
- PAGES: for the tests in the base folder (spec: "cypress/e2e/pages/*.cy.ts")
- SETTINGS: for the tests in the base folder (spec: "cypress/e2e/settings/*.cy.ts")

I created separate CI workflows for each one and added the param "with: spec" to each one of them.
