### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by fionahelle** [huridocs/uwazidocs#6913]
**Describe the bug**
I cannot access the website as the loading time is too long.

**Screenshots**
![image](https://github.com/huridocs/uwazi/assets/173177184/f0f6a2cb-284f-4038-b0bb-747e47f0957a)
https://prnt.sc/JM7ssJ_tTf2Q 

**Device (please select all that apply)**
 - [ ] Desktop: Asuss
 - [ ] Mobile

**Browser**
What browser where you using (Firefox, Chrome, Safari, etc...). Firefox

**Comment by vostorga** [comment]
Hello

- If you wait long enough, are you able to access the website?
- May you provide your public IP address?  This can be obtained if you enter in a web search tool 'what is my ip'
If you are concerned about your privacy, please share only your first 3 octects, for example  12.45.35

**Comment by fionahelle** [comment]
Hello
If I wait long enough, I get the same error message. No response, even from another browser. I don't have internet connection issue, as I am able to access other websites.
My public IP is: 62.167.164.21

**Comment by txau** [comment]
@fionahelle still not able to connect? We have been experiencing some connectivity issues today. You may experience it as  intermittent timeouts.

**Comment by fionahelle** [comment]
still unable to connect, yes

**Comment by txau** [comment]
@fionahelle could you please try again? I hope it is working now. Let me know if it is still failing to connect.
