### ISSUE TITLE
[IX] Visual improvements for used icons and buttons

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6915]
1. The property icons in the extractors table seem to have varying sizes. The icons should be 20px X 20px.

**As is:**
<img width="1082" alt="Screenshot 2024-06-20 at 10 42 53" src="https://github.com/huridocs/uwazi/assets/102693686/18fb03dc-41c8-4123-89ca-7e1b0d84e700">

Should be:
<img width="1040" alt="Screenshot 2024-06-20 at 10 43 05" src="https://github.com/huridocs/uwazi/assets/102693686/f254e955-fd78-48ea-8afe-844e1d037a10">

2. The "Group" and "Accept" buttons should not have shadows

As is:
<img width="1474" alt="Screenshot 2024-06-20 at 10 55 51" src="https://github.com/huridocs/uwazi/assets/102693686/4e8db9ae-afe2-4603-88c0-26b6a3597282">

Should be:
<img width="1467" alt="Screenshot 2024-06-20 at 10 56 02" src="https://github.com/huridocs/uwazi/assets/102693686/a8b2d771-956a-4623-a7e8-3fbbeca94639">

**Comment by roirobo** [comment]
Looks okay. The icons still have varying sizes and still look a bit too big. Also, the Metadata extractor icons are bigger than Metadata creator properties icons.
