### ISSUE TITLE
Upgrade PDF js

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#6920]
We are a little bit behind on this critical lib for us. New version have breaking changes but important bug fixes.

**Comment by aphilop** [comment]
@txau 
During the backlog refinement meeting we couldn't assess the priority of this. Please assign a priority.

**Comment by txau** [comment]
@Zasa-san check this old issue: https://github.com/huridocs/uwazi/issues/3761

and this advisory: https://github.com/mozilla/pdf.js/security/advisories/GHSA-wgrm-67xf-hhpq

Apparently isEvalSupported is disabled in the newer versions by default.
