### ISSUE TITLE
Bug on EntityData in custom pages for entity

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#6921]
Pages code that previously was working is not working any more.

![image](https://github.com/huridocs/uwazi/assets/489831/30b7efc1-2af7-4d70-bbf6-a9c67b129280)

**Comment by txau** [comment]
This is happening when people try to use the label for the commonProperty "title", instead of just title.

What is puzzling is why this started failing out of the blue.

A quick fix is to make sure that we support the label for the common property "title".

**Comment by aphilop** [comment]
This is fixed and deployed.
