### ISSUE TITLE
[IX] Visual improvements for the "Add Extractor" dialog

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6939]
There are some visual/textual issues with the dialog displayed when adding an extractor:

![image](https://github.com/huridocs/uwazi/assets/102693686/678ae9ac-7c9f-4d1d-a2c2-fb93a618c499)

- [x] Use consistent size for the icons (20px X 20px) as also described in https://github.com/huridocs/uwazi/issues/6915
- [ ] Typo in `miltiselect` -> `multiselect`
- [ ] Suggestion: Use the property names as we have them in other areas of the application (`Text`, `Numeric`, `Date`, `Relationship`, `Single select`, `Multiple select`

**Comment by aphilop** [comment]
Could be handled together with https://github.com/huridocs/uwazi/issues/6868

**Comment by konzz** [comment]
@juanmnl @aphilop the Icons are all the same "size" and by that I mean the same width, the problem is they are not perfect rectangles, so they cannot be 20x20

**Comment by juanmnl** [comment]
@konzz to make them all seem the same size, there should be an explicit width and height declared in the svg css (w:18px h:18px) and the span that contains them should act as a bounding box with only a padding of 2px (totaling a 20px by 20px).

<img width="1440" alt="Screenshot 2024-07-12 at 11 30 00 AM" src="https://github.com/user-attachments/assets/1013fe3b-7b99-441f-9650-f52019ab0c36">
<img width="1440" alt="Screenshot 2024-07-12 at 11 30 42 AM" src="https://github.com/user-attachments/assets/747852e6-5d43-4906-97c2-c5b40283cf00">

**Comment by konzz** [comment]
@aphilop the `miltiselect` typo must be a wrong translation in that specific instance.

**Comment by aphilop** [comment]
@konzz 

This is what I see in the translations in the instance I took the screenshot from.
<img width="485" alt="image" src="https://github.com/user-attachments/assets/42784384-4701-43e6-b0bc-24dc6306640a">

Is this the relevant key? Unfortunately I can not check the UI again, because IX is not accessible anymore in the staging instance I am using.

**Comment by konzz** [comment]
That's the same modal in my local
![Screenshot 2024-07-16 155655](https://github.com/user-attachments/assets/39258e8e-7d56-409d-8b40-6c98b7ab0d15)

No I don't think that's the translation nor you cannot find it, because the translation default is property.label and probably was not added to the CSV

**Comment by aphilop** [comment]
So I assume it should be fixed then, right?
