### ISSUE TITLE
[AT] I. Machine translation settings

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#6950]
Add the MT settings to the `settings` object in the db, and implement a read-out in the settings manager. The settings will be set manually.

The settings should:
 - be under the features 
 - have an active bool for turning off without removing the whole setup
 - have a config for templates, properties, and languages

Since properties are referred by id, templates are not strictly necessary, could be just a property-to-languages map.

The read-out should:
 - filter for existing resources (templates, props)
 - filter the property types to text and rich-text
 - filter languages to the allowed shortlist (Arabic, English, French, Russian and Spanish)
 - filter languages to ones set in the collection
 
 Should the read-out process output a warning on incorrect setup? An error is probably too much, since we don't want a typo to stop the whole process.

**Comment by daneryl** [comment]
@aphilop should the languages be configurable or should we use the  languages already configured for the tenant ?

**Comment by aphilop** [comment]
@daneryl 
In the discussions we had for the solution design, we decided:
"The available languages of the collection are set as the languages for automatic translation (provided they are available in the translations service)." So, we should use the languages configured for the tenant.

**Comment by RafaPolit** [comment]
As part of this implementation we are going to provide a DEV-exclusive script to create a config object passing semantic data and the script will extract the right ids.
