### ISSUE TITLE
Problems when importing a thesaurus from CSV file

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#6959]
**Describe the bug**
The system throws an error if you create a thesaurus and immediately try to import a CSV file.

**To Reproduce**
1. Go to '/settings/thesauri'.
2. Click on 'Add thesurus'
3. Type a thesaurus name
4. Click on 'Import', select a CSV file properly done. 
[Thesaurus Test.csv](https://github.com/user-attachments/files/16054872/Thesaurus.Test.csv)
5. Then you get the list of items:
![image](https://github.com/huridocs/uwazi/assets/73410334/9b177993-273e-4149-8cb7-359d18159560)
6. Click on 'Save'.
7. you get an error:
![image](https://github.com/huridocs/uwazi/assets/73410334/15126a80-adae-404f-a691-06e441071cf2)
8. However, if you come back to '/settings/thesauri' and edit the just created thesaurus again, the imported list is available.

**Expected behavior**
Errors should not appear, if the CSV file is properly imported.

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Browser**
Brave

**Comment by RafaPolit** [comment]
While doing this, please check if any of the issues in #6699 can be fixed or are already done.  Thanks.
