### ISSUE TITLE
Intermittent e2e: cypress/e2e/pages/public-form.cy.ts

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6969]
Apparently, the test intermittency resides upon trying to check the results:  the click on "Restricted" files is not accomplished and, therefore, the check fails as unsuccessful.

**Comment by Zasa-san** [comment]
Public form issues will be fixed as a stabilization fix in #6981 since it's blocking work for some users.
Maybe this can be part of the regular sprint planing instead? @konzz @mfacar @aphilop 
(We originally said to work this in the PR that would fix the media issues in public forms)

**Comment by mfacar** [comment]
@Zasa-san, given that some tests broke while doing the fix (fortunately they showed me some scenarios I didn't anticipate). I fixed the flaky test on the way of reviewing the different cases.
