### ISSUE TITLE
[IX] Add all the relevant statuses in the Suggestions column of the extractor table

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6977]
At the moment we display only a few statuses (eg. 54 values | 54 suggestions | 54 mismatching).
We need to add more statuses that are also displayed in the Stats & Filters panel

**Comment by txau** [comment]
I think we need clarification on what the different numbers in stats panel mean:

- LABELED: it means the conditions for being labeled are met. But these conditions depend on the type of information you are extracting:
    - text, number, date: it has a value and a text selection
    - selects/relationships: it has a value, no need for text selection
    - all of them: something marking the "empty value" as the labeled data

- Accuracy: calculation based on matches/mismatches for labeled data
- Match: there is labeled data, there is a suggestion and they match
- Mismatch: there is labeled data, there is a suggestion and they do not match

- NON-LABELED: they do not meet the criteria for labeled
  - Pending: I don't know what this represents at this moment. We should take a look to the code
  - No suggestion: not sure about this one too. I guess it means, it is not obsolete, error or no context. The model returned something but it is empty? Should we rather say that the suggestion is "empty"?
  - No context: the model could not figure out a text? the context returned by the model is empty?
  - Obsolete: the model is training and extracting suggestions. This is a transitional state that only should happen WHILE training. So this should be always CERO after training
  - Others: I do not know if there is any other possible state apart from error. Probably we could change this to just "error". Make sure that errors and obsoletes are not the same (an error should still update the suggestion to the latest model, so it is no longer obsolete). Check the code to see if there is any other possible meaning for error.

We are also still waiting for a new category in non-labeled that is "Suggestion".

After reviewing these descriptions, we should update the side panel to reflect this, then the status could be shown in the table as well.

**Comment by txau** [comment]
> Pending: I don't know what this represents at this moment. We should take a look to the code

Pending means they are non-labeled vs the labeled amount. We should clarify.

> No suggestion: not sure about this one too. I guess it means, it is not obsolete, error or no context. The model returned something but it is empty? Should we rather say that the suggestion is "empty"?

No suggestions as of today is the default value before processing the suggestions. It means that either the model didn't return anything for that particular suggestion, or it returned empty (array, string, number). This needs revision fi we introduce the concept of "empty" as a valid labeled data.

> No context: the model could not figure out a text? the context returned by the model is empty?

Rafa reported an incorrect logic in this setting in issue #7060 

> We are also still waiting for a new category in non-labeled that is "Suggestion".

This has already been implemented.

**Comment by txau** [comment]
Related to: https://github.com/huridocs/uwazi/issues/6804

We need to rationalize all these statuses.

**Comment by txau** [comment]
Also related: https://github.com/huridocs/uwazi/issues/6804

**Comment by aphilop** [comment]
Will be handed with #7085
