### ISSUE TITLE
[IX] Enable searching the values when selecting text in the PDF while viewing the document in the drawer

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6978]
The idea is to make more convenient finding the relevant values and selecting them for acceptance.

<img width="849" alt="SCR-20240705-hozi" src="https://github.com/huridocs/uwazi/assets/102693686/42c64907-a23b-4233-8c73-ef6941c90542">

Flow of interaction:
- User selects text in the PDF
- With a keystroke (tbd) can initiate the search (the text is copied in the search field)
- The list filters are updated accordingly
- We could display somewhere a hint text about searching with a keystroke

@juanmnl to add visual suggestions

**Comment by txau** [comment]
Not sure about that particular flow. Because this is happening in the context of the side panel for the select/multiselect property: what is the purpose of selecting a text in the document in this context other than searching?

Maybe just selecting could trigger the search right away. And the keystroke or other fast interaction is to assign the value in case of a single search result. So the happy path could be:
- select a text
- instantly triggers a search
- fast action to set that value

**Comment by juanmnl** [comment]
We are adding a toggle button to the HUB header with the label [Select & search]. (For now this should only be added to IXs select and multiselect options) This button should be deselected by default but when pressed/active it should:
- instantly search any value that is highlighted by the user (onMouseUp)
- disable any default keyboard shortcut for pdfs and override the CTRL + # for quick selection of values
- append the shortcut text (ctrl + #) and the number of the values in order until the 9th value. If more than 9 values are available for the user, we should consider manual selection after the 9th value.

<img width="700" alt="suggestions - edit select - toggle off" src="https://github.com/user-attachments/assets/ee608e26-eccc-4b4c-98ae-eab48100fd8c">
<img width="700" alt="suggestions - edit select - toggle on + search" src="https://github.com/user-attachments/assets/d461e084-b716-44ba-a833-7ec15c138524">
<img width="700" alt="suggestions - edit select - toggle on + search + select" src="https://github.com/user-attachments/assets/0ec9defd-3073-4daf-9051-b6bfb05fd604">

No results for the search.
<img width="700" alt="suggestions - edit select - toggle on - no results" src="https://github.com/user-attachments/assets/35792872-36ed-4e69-a863-49330110114c">

**[Designs](https://www.figma.com/design/Ypgf1qGtcxgMJEgWchoqTx/WIP?node-id=6698-4823&t=DpKb4UkBfnWaTTbV-4)**
