### ISSUE TITLE
[IX] Improve the way the side panel is used for viewing and editing suggestions

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6980]
With the current approach we have the following problems:
- There is a disconnect between the actions possible in the table view and the side panel 
- When getting in the side panel it is not very obvious and transparent what are the suggestions and where are they in the PDF

We need an approach that solves the above problems.

@juanmnl to work on some suggestions for solving the above.

**Comment by juanmnl** [comment]
As a first improvement, we are adding color coding for the suggested and accepted values on the list while viewing the PDF.
This color coding should match the values/suggestions colors from the table.

<img width="700" alt="suggestions - edit select - toggle off" src="https://github.com/user-attachments/assets/4ee4bd9a-5028-427c-a5ff-abcf2aca8abd">


We are also adding a [[Select & search] toggle for quick editing](https://github.com/huridocs/uwazi/issues/6978) of the values from the PDF selection and a [button that will label the whole document as empty](https://github.com/huridocs/uwazi/issues/6979) (if any values are checked when this action is executed it should deselect all)

**Comment by konzz** [comment]
@juanmnl can you please link the designs?

**Comment by juanmnl** [comment]
@konzz [here it is](https://www.figma.com/design/Ypgf1qGtcxgMJEgWchoqTx/WIP?node-id=6698-4823&t=t2oZBXnUrMxJMyB9-4) Sorry I missed it.
