### ISSUE TITLE
Potentially unused/unusable api endpoint: get_raw_page

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#6988]
The endpoint `/api/entities/get_raw_page` calls `entities.getRawPage`. However, there is no such function (this is still in js, hence the no typescript error). The task is:
- review the endpoint, and decide if it needs to removed
- if it is still used:
    - supply an implementation in the back-end
    - test the endpoint
    - review and test the front-end functionalities
 - if it is not:
    - remove the endpoint and related tests
    - remove the front-end references to it

**Comment by aphilop** [comment]
To-do: collect relevant issues regarding deprecated code to remove and assess them together.

**Comment by daneryl** [comment]
Unused code removed https://github.com/huridocs/uwazi/pull/7348
