### ISSUE TITLE
DateBase Issues      Caselaw.ihrda.org

### ISSUE THREAD

**Issue by 12345229** [huridocs/uwazidocs#7034]
<img width="952" alt="Screenshot 2024-07-22 131525" src="https://github.com/user-attachments/assets/46802e97-bcdf-4340-bfdf-4ddd71acd1e1">
<img width="951" alt="Screenshot 2024-07-22 125613" src="https://github.com/user-attachments/assets/743052d0-afc7-4f53-ac1b-f12fae198c42">

Hello,

This is Omar T. Jallow the ICT OFFICER of the institute for human rights and development in Africa. (IHRDA)

Regards to the above subject it’s been a while now we did not get any success to make it work best on our side.
 
The Asst.communications and publication Officer told me that she got a chat about it already with Chamrid. yes, it is working if we used a different internet connection from our office.
But yesterday I even told our internet service provider to change our public IP Address to see if it will help which they did but still no success. 
 
Can you please check from your end or server end if our IP Address has been blacklisted or so to be able to connect the database.
 
Kindly let me know if you have any questions.

**Comment by 12345229** [comment]
Hi Omar,

Hope you are doing well too.

We did some tests, and it seems like our IP block is getting blocked by the web hosting provider of https://[redacted domain name]/

Kindly contact them to whitelist our IP blocks.

It should be :

1xx.2xx.1xx.0/20 [redacted IP]

Thanks,
Ayush Khurana


this is what we received from our service provider so help us out and this problem be fix.

we have been communicating with [the director of programs] but is still not solve

**Comment by RafaPolit** [comment]
Thanks for the report.  Let us look into it. As soon as we have the data, we may edit this posts to remove your personal info from public view.

**Comment by vostorga** [comment]
Hi @12345229 
Please retest access to the instance and let us know if it works for you

**Comment by 12345229** [comment]
Hello, 

 

Thank you for your email and timely response.

 

The site is back and working normal.

 

Many thanks 

Omar T. Jallow

**Comment by 12345229** [comment]
Thank you for all your efforts.

 

Omar T. Jallow

**Comment by aphilop** [comment]
Closing this as done
