### ISSUE TITLE
Thesauri / All items are deleted when trying to remove a duplicated value

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#7043]
**Describe the bug**
When adding an item in a thesaurus, if this value already exists and then you must delete it, the whole list of values disappear.

**To Reproduce**
1. Go to 'Settings - Thesauri' and select a thesaurus.
![image](https://github.com/user-attachments/assets/64c9cab5-a78a-46a6-8f69-238e6934dca4)

2. Add an item with a duplicate value on purpose.
![image](https://github.com/user-attachments/assets/fd385058-d255-41fc-aa39-7e0149ce0f0c)

3. When trying to save it, the system send a warning.
![image](https://github.com/user-attachments/assets/3ed9d315-20d9-438d-b615-e27696c0de2d)

4. Select the duplicated item and click on Remove.
![image](https://github.com/user-attachments/assets/6f1ca0f5-0d10-47d3-85b2-c0e0b652b8bc)

5. See error: every item has de dissappeared.
![image](https://github.com/user-attachments/assets/3d5673e7-bbbe-4426-a705-951feee1de5c)

**Expected behavior**
Only the duplicated and selected item should be removed.

**Comment by RafaPolit** [comment]
Please, ensure that all the thesaurus operations are using IDs or temporary IDs and NEVER labels. This problem is not the only issue with duplicated name values, which suggests an inconsistency there.
