### ISSUE TITLE
[IX] Provide editors with permission to access the metadata extraction menu item under settings

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#7051]
**Is your feature request related to a problem? Please describe.**
Based on the current user permissions, only the `admin` role has access to the settings where the metadata extraction menu item is accessible. However, users with the role `editor` must be also able to use the metadata extraction.

**Describe the solution you'd like**
Update the user permissions so that users with role `editor` have access to Settings > Metadata Extraction

**Additional context**
This is needed for beta testing the feature with a partner.

**Comment by RafaPolit** [comment]
Check if Backend routes have the right permissions.
