### ISSUE TITLE
Migrate to new table

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#7052]
After #6826 is merged we need to use the new table for all the v2 UIs.

We should migrate all uses of `V2/Components/UI/Table` and replace it with `V2/Components/UI/TableV2`, and remove the corresponding story and test. Lastly, rename `TableV2` module, story, and test to `Table`.

This is important because `TableV2` handles groups differently and has a corrected dnd functionality. 

Keep in mind that the new table requires that all its rows and sub rows have a unique `rowId` to properly handle dnd, selection and grouping. 

Doing this migration will fix: #6431& #6432

Sections under Settings where migration to new table is needed:
- [ ] User & Groups
- [ ] Menu
- [ ] Pages
- [ ] Languages
- [ ] Translations
- [ ] Filters
- [ ] Bug in Filters: Moved here from issue #6820 
       **Describe the bug**
When a user extracts all the items from the group in the filter settings, the group becomes a filter. It seems to be a bug because we use entity types (templates) for the creation of primary filters; labels that we use for grouping should not become filters. As a result, when a former group name is displayed on the filters panel, it always shows 0 entities, because there is no template associated with it.
**To Reproduce**
     1. Go to Settings and navigate to Filters from the left menu
     2. Add group and add entity types to the group
     3. Save the change
     4. Drag all the entity types belonging to the group outside of the group
     5. See that the group is displayed as a filter item as a result
- [ ] Relationship Types
- [ ] Activity Log
- [ ] Uploads
- [ ] Migrate FileDropzone to use dnd-kit (from #7065)
       We should migrate FileDropzone to use dnd-kit, instead of react-dnd so that v2 uses one library for drag and drop functionality. There’s also a DragAndDrop.stories.tsx for an implementation of dnd that’s not used in v2 and should also be removed. If https://github.com/huridocs/uwazi/issues/7052 is done, react-dnd can be removed as a dependency.

**Comment by Zasa-san** [comment]
I was mistaken about #7065, our file dropzone component uses it's own dropzone library specifically tailored for file dropzones. There's no point in migrating it. 

We can, however, remove `react-dnd` after the tables are migrated to the new version, and remove DragAndDrop.stories.tsx and the components that it has since they are not used.

In the end V2 will have `dnd-kit` for complex drag and drop for tables (and any other use that might come up) and `react-dropzone` for the file dropzone components. 

We still have `react-dnd-old` which cannot be removed since it's used in tables and other places of V1.

@konzz @mfacar

**Comment by oleksandrako** [comment]
After testing, we found that in the specific Settings area of Users & Groups > Groups section, the look and feel of the table v2 is not consistent in terms of the i) look of the Group [see image here], 
ii) (may related to #6820), the Group name persists even when all users in the group are removed. 

![Screenshot 2024-09-10 at 17 13 52](https://github.com/user-attachments/assets/1a8d63c0-5c64-4f48-833b-f1629fbd4c65)

**Comment by Zasa-san** [comment]
> After testing, we found that in the specific Settings area of Users & Groups > Groups section, the look and feel of the table v2 is not consistent in terms of the i) look of the Group [see image here], ii) (may related to #6820), the Group name persists even when all users in the group are removed.
> 
> ![Screenshot 2024-09-10 at 17 13 52](https://private-user-images.githubusercontent.com/119293151/366102648-1a8d63c0-5c64-4f48-833b-f1629fbd4c65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwODU0NTAsIm5iZiI6MTcyNjA4NTE1MCwicGF0aCI6Ii8xMTkyOTMxNTEvMzY2MTAyNjQ4LTFhOGQ2M2MwLTVjNjQtNGY0OC04MzNiLWYxNjI5ZmJkNGM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQyMDA1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDI2OWI4Y2JkOGQ3YzhiYzM2NWRjODc2ZDg3YzVmY2VjYTM1OGExZDk4MWU2N2U5ZDMxMTM3MjNiNTA1OTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gBBjNhtZVT9hm50_sVDbGwQHox3AB1GvKl_8egxZjNk)

Hi @oleksandrako! Thanks for the feedback, but I don't quite follow what the issue is. Does the table look odd or incorrect? 
Regarding groups, what do you mean the name persists when all the users are removed? What's the expected behavior?

**Comment by pddocs** [comment]
hi @Zasa-san (I was also part of testing team with @oleksandrako ), here is what we found: 

1. Users & Groups > Groups side has Table v2 implemented, as per our understanding. If that is the case, we expected that when you group items (here users) via 'Add Group', you will also get a grouping that looks something like this: 

![Screenshot 2024-09-13 at 12 18 56](https://github.com/user-attachments/assets/a5013e79-0d1b-4a9d-9125-f277dd48a3f5)

But, it look different as shown in @oleksandrako 's comment above in the Users & Groups > Groups side. 
Correct us if this was a wrong expectation. 

2. The second point is also regarding the Users & Groups > Groups side. Steps to follow: 

- Step 1: Create a user group using Add Group , say 'Group A'
- Step 2: Add users 'Jane' and 'Jack' to it and save 
- Step 3: Click edit on the Group A and delete both 'Jane' and 'Jack'
- Step 4: Click save 
You find that the group name Group A still exists even though both users have been removed from the group. 

We tested this behaviour in light of the fix #6820 , expecting the label Group A to also get deleted. 
Is this not the expected behaviour?

**Comment by Zasa-san** [comment]
@pddocs @oleksandrako I think I understand now. This is an interesting point you bring up! I think the problem here is that the concept of groups in 'Users and groups' is very different to item grouping in other parts of the app.

In 'Users and groups' groups can be empty, and can be created with no users in them. Remember that you can give permissions to a group even if it has no users in it. Deleting a group if it's empty might disrupt how a user prefers to handle permissions. You can totally have empty groups that you use occasionally and then remove users from it.

The reason groups are handled differently in ‘Users and groups’ has to do with the fact that multiple users can belong to several groups. It would be confusing to show them all in one table. To make the UI simpler to understand we separate users and groups in different tables.

I don’t believe that our table grouping feature that is seen in things like filters or thesauri would be applicable to ‘Users and groups’.

Hope this clarifies!
