### ISSUE TITLE
The Entity Save button, once disabled for a failed save, is never re-enabled

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#7058]
**Describe the bug**
Related to #5851

After an Entity Save fails, for whatever reason: hung server, lost connection, etc., the button is now forever disabled, the only way to re-enable it is to refresh your screen.

How and when to re-enable it is probably something to be discussed / defined.

**Comment by mfacar** [comment]
There is a consistent way to reproduce it. Submitting a huge value in a text field returns a 500 error of ES indexation. Which seems to be one of the cases reported in #5851.
