### ISSUE TITLE
Migrate FileDropzone to use dnd-kit

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#7065]
We should migrate `FileDropzone` to use `dnd-kit`, instead of `react-dnd` so that v2 uses one library for drag and drop functionality.

There’s also a `DragAndDrop.stories.tsx` for an implementation of dnd that’s not used in v2 and should also be removed.

If #7052 is done, `react-dnd` can be removed as a dependency.

**Comment by RafaPolit** [comment]
@Zasa-san to rewrite the issue / title to reflect the discussed approach

**Comment by Zasa-san** [comment]
> @Zasa-san to rewrite the issue / title to reflect the discussed approach

Done

**Comment by aphilop** [comment]
Will be handled with  #7052
