### ISSUE TITLE
[IX] Move "Accuracy" and "Pending" from filters to the indicator they actually refer to

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7066]
Pending an accuracy looks like part of filters at a glance, but actually they refer to "No-labeled" and "Labeled" respectively. It would help with readability to place them next to the info the refer to.

![image](https://github.com/user-attachments/assets/18602c93-da31-45fe-a33d-aebc229dd25a)

**Comment by aphilop** [comment]
Will be handled with #7085
