### ISSUE TITLE
user property missing, what does it mean and shall we do something about it?

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7080]
Running a check on all the databases revealed that many entities have no property "user". I don't know exactly what that property means:
- The user that created the entity originally?
- The owner? But this is handled by permissions actually

Also why this information is missing and what does it mean for us:
- The user was deleted and we are also deleting that historical data?
- Shall we denormalize that value instead?

**Comment by RafaPolit** [comment]
User is the user that creates the entity.  
Public submitted entities probably shouldn't have a user and that could be the ones you are seeing, a quick check in the activity log may give some feedback.
The implications of this is probably low to none.  This is legacy structure that probably should be removed.

**Comment by txau** [comment]
Ok. Let's assume it is ok to have entities without users.
