### ISSUE TITLE
[IX] - Statuses revamp

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7085]
Putting it all together from: https://github.com/huridocs/uwazi/issues/6979 https://github.com/huridocs/uwazi/issues/6977 https://github.com/huridocs/uwazi/issues/7060 https://github.com/huridocs/uwazi/issues/7066 

Filters should look like:

LABELED (X%) ............... amount (Accuracy somewhere)
NON LABELED (X%) ............................ amount

Match ............. amount
Mismatch .............. amount

(OTHERS)
Obsolete ...............amount
Error.......................amount

- Three separate sections
- When a suggestion is Error or Obsolete it is not computed in the other two sections' stats
- We are removing the "no context" filter. This is going to be controlled by the service. (fixes #7060)

We need to give support for "labeled as empty". Uwazi needs to send these  empty markers along with the rest of the training data. If a property has no value, but it also does not have the empty marker, we do not send it to training.

Statuses are display on the table as:

- IF it is a select/rel field =>  "X values | X suggestions | X mismatching" (as it is now)
- IF it is a text/num/date => as it is now
- Labeled as empty/suggested empty becomes an explicit special case. It is not the same as an empty string. It will come like that from models and we will send it like that to models. So we can have a special icon or pill and it can say "empty" | "empty" or whatever.
- Error
- Obsolete

Models will control what comes as "segment", which can contain either the context or some other message, to be display in the column in the table. Ie. if there was an error, that row will contain the status "Error" along with the context "Couldn't read PDF file" or whatever the model decides. We don't need to run any logic on the rendering of the context, just print whatever the model is sending, if it is a blank string, so be it.

**Comment by txau** [comment]
A note on the behavior and updates of the stats panel:

- When the users clicks "Find suggestions", all suggestions become obsolete. It needs to be reflected on the panel and the table.
- Every tick of the training/getting suggestions process needs to update the panel and the table.
- When a suggestion gets accepted on the table, it needs to update the filter panel.

**Comment by juanmnl** [comment]
We are removing some styles to drive towards a cleaner/simpler "stats & filters" drawer. (these styles will propagate in the future towards all of the existing and future drawers/sidepanels, including the most important ones in library and entity v2)

As discussed with @txau we are removing the "others" title and some percentage values.

<img width="494" alt="stats   filters" src="https://github.com/user-attachments/assets/02a995ad-5fd5-4d47-8de4-a209d595b515">

[Designs](https://www.figma.com/design/HZX8qH0Aw8WiSch3Axczrn/new-comps?node-id=5031-37421&t=Ccgm8AAGxWeKPFb7-4)

**Comment by RafaPolit** [comment]
Just to keep info here:
Accuracy should be defined as:
Match / Mismatch, excluding those mismatches where the entity data is blank or empty string (not intentionally empty)

**Comment by txau** [comment]
An addition to this. After a conversation with @gabriel-piles we are going to remove the constraint of having selection rectangles to be considered labeled data for property types "text", "number" and "date". So now they can be used the same as selects, meaning that, if they have a value or they are labeled as empty, then they are considered labeled data. If they are just empty string without explicit "label as empty" then it is not labeled data.

This goes along the line of what @konzz was pointing out for the match/mismatch. If it is labeled (has a value or explicit empty) it goes into the match/mismatch stats.

**Comment by txau** [comment]
In this case obsolete and error have overlapping (two errors are also obsolete). Moreover, they are also counted as mismatch.
![image](https://github.com/user-attachments/assets/3f98199f-8000-4d53-859d-c2dbdd5b4535)

**Comment by txau** [comment]
@RafaPolit obsoletes should not be counted as match/mismatch. It is ok to leave them as labeled/non-labeled since it is independent from the current training/suggestions status.

![image](https://github.com/user-attachments/assets/44496d51-4537-419d-bdb2-26698921c548)

**Comment by txau** [comment]
@RafaPolit in this other case obsolete is not included as part of the match/mismatch

![image](https://github.com/user-attachments/assets/e09e4b3b-6a59-4731-abbd-eec6cf401c4a)

this could be cause by the type of property being processed? This screenshot is for a multiselect, the previous one is for a date property.

**Comment by txau** [comment]
@RafaPolit yet another oddity that may help figure this out, in screenshot

![Image](https://github.com/user-attachments/assets/58e51b94-0ed2-4ede-a625-9c8796752820)

 The matches are being computed despite the obsolete, but since this is a retrain in which the previous run the accuracy was close to 90%, most of them appear as matching. So apparently, when starting the training, obsolete is set, but not the match/mismatch state that should be null.

**Comment by txau** [comment]
working as intended now
