### ISSUE TITLE
Failing component test

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#7092]
DateRangePicker
    ✓ should be accessible (204ms)
    1) should execute date selected events when a date is selected
    ✓ should select the current day (199ms)
    ✓ should clear the selected date by the button (336ms)
    ✓ should clear the selected date by the action in the input (263ms)

**Comment by mfacar** [comment]
Caused by a negative margin in the calendar popup that affects Cypress component testing, adding a margin makes the popup position better calculated.
