### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by 12345229** [huridocs/uwazidocs#7115]
who can help us with our website issues at ihrda.org we cannot upload photos because the dimension of the size differs  
we have invited some developers to help us to look at it but still nothing is possible.

we want to have full acees to our domain host both the backend and frontend.

**Comment by aphilop** [comment]
Hello and thank you for your message.

Unfortunately we cannot help you here with your request as in this repository we handle issues related to Uwazi and sites made with Uwazi (as far as I know ihrd.org is not such as case). For further questions, get in contact with your corresponding HURIDOCS contact person.
