### ISSUE TITLE
[IX] Click to fill on text properties, issues with new line chars

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7122]
When using click-to-fill on a text property there are two issues that are hindering the user workflow:

1. The copied selection does not convert the new line chars to a white-space char. Maybe there is no new line char, in which case we need to figure out a way to process segments belonging to different lines. The result is a concatenation of words that needs to be manually fixed:

![image](https://github.com/user-attachments/assets/731b087f-c954-4599-ae28-c1b44153e99a)

As you can see the copied text is:

`37/42. Contribution to the implementation of the joint commitment toeffectively addressing and countering the world drug problem withregard to human rights`

Where "toeffectively" should read "to effectively" and "withregard" should read "with regard".

2. The input box is too small for big texts. This may be a wider issue and maybe replace regular input box for titles with a multiline text box?  Some title can be really big, such as:

`Report on the situation of human rights in Darfur prepared by the group of experts mandated by Human Rights Council resolution 4/8 presided by the Special Rapporteur on the situation of human rights in the Sudan and composed of the Special Representative of the Secretary-General for children and armed conflict, the Special Rapporteur on extrajudicial, summary or arbitrary executions, the Special Representative of the Secretary-General on the situation of human rights defenders, the Representative of the Secretary-General on the human rights of internally displaced persons, the Special Rapporteur on the question of torture and the Special Rapporteur on violence against women, its causes and consequences*`

**Comment by RafaPolit** [comment]
Coordinate with @gabriel-piles to check if he already solved  similar issue on the ML services.
