### ISSUE TITLE
[IX] Changes in accepted suggestions or labelling, do not affect filters

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#7137]
### Changes in accepted suggestions or labelling, do not affect filters

When I click on Accept suggestion, the system updates the suggestion and values, but the filters are not updated accordingly, if I open the side panel, the values showed are the same as before.  I need to refresh to get the updated values.

**Comment by txau** [comment]
This is reported as a front-end issue. On every event (new suggestions coming in, training started, user accepted suggestion, etc) the filter panel needs to be updated. I think @konzz is already working on this.

**Comment by konzz** [comment]
I was aware of this or you mentioned it Txau, but wasnt working on it. We could add this one to ready and I'll pick it next

**Comment by aphilop** [comment]
This is supposed to be handled with #7085, see https://github.com/huridocs/uwazi/issues/7085#issuecomment-2264112556
I would suggest to close this issue.

**Comment by txau** [comment]
@konzz as @aphilop mentioned this is defined in #7085 and needs to be done
