### ISSUE TITLE
[IX] Extracted metadata in Files persists after Extractor deletion

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#7139]
### Extracted metadata in Files persists after Extractor deletion

When I delete an extractor, all suggestions for that extractor are deleted, but each File (that was labeled or not) still has metadata values with selection rectangles for a particular text.  Upon creating news extractors, this data is reporting as already labeled.  Additionally, files extracted metadata does not hold any information regarding to which extractor it belongs.

**Comment by txau** [comment]
This is working as intended. Keep in mind that the "click-to-fill" feature is not just for machine learning but also for regular entity edition. The selection rectangle belongs to the property, not to the extractor. It is expected to keep the selection rectangles for that property and that it is recovered as already labeled data if the extractor is recreated.

**Comment by RafaPolit** [comment]
Ok, I need to confirm that the File's `extracted metadata` is bound to a particular property.  If that is the case, I think I agree that this is working as expected.
