### ISSUE TITLE
Uwazi not denormalizing translations

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7184]
Eg. In the screenshot you can see mixed labels for the same thesauri values:

![image](https://github.com/user-attachments/assets/d4d33d51-a68e-42b9-ab72-796a417369a6)

I have double checked this in the database and indeed, it is not properly denormalizing translations.

**Comment by RafaPolit** [comment]
Note: the above examples are rendered from an EN UI.

**Comment by txau** [comment]
After some testing, this is working as intended and there is no bug. But, some instances have non-denormalized thesauri labels (that gets fixed automatically when resaving the entity). A migration to denormalize all thesaurus labels would fix this, but it is non-critical.

**Comment by RafaPolit** [comment]
The script to re-denormalize the data is in production and run on one test tenant, it appears to be working as expected. This is NOT a migration, it's a script that needs to be run on all tenants, or on a tenant by tenant basis.
