### ISSUE TITLE
OCR not working?

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7192]
Sent a document for OCR and it stays in queue forever:

![image](https://github.com/user-attachments/assets/6321773a-2c09-483e-9af2-82a75eb89914)

The only traces in logs are:

![image](https://github.com/user-attachments/assets/7321b05d-d904-45a8-be2b-10071ec4a924)

**Comment by RafaPolit** [comment]
@gabriel-piles can you please confirm if the service is working?

**Comment by gabriel-piles** [comment]
@RafaPolit @txau The staging and production OCR services are working fine

**Comment by txau** [comment]
This happened on staging and the status is still in the queue:

![image](https://github.com/user-attachments/assets/bed1524f-bc9c-49e9-b626-f37fa42ff742)

https://cyrilla.staging.uwazi.io/en/entity/y8stnt826oi/

@gabriel-piles

**Comment by gabriel-piles** [comment]
@txau  the OCR staging service has proper access to the Redis queue

**Comment by gabriel-piles** [comment]
@txau @RafaPolit The feature flag in staging was incorrectly pointing to the production OCR service. Additionally, I had to redeploy the service in staging because even after changing the feature flag in the database, the service was not performing OCR.

Now, it works as expected.
