### ISSUE TITLE
Add envinronment namespace as part of redis queue name for services

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7217]
At the moment our queue names for certain services are hard coded. This is mixing the redis messages when using the same redis server and services for two different environments. We agreed with the ML team that in order to be able to use the same services from different environments we should add  the environment name as prefix or suffix to the queue name.

**Comment by vr-varad** [comment]
@txau @aphilop  I would like to work upon this issue if it open for contribution

**Comment by txau** [comment]
Hello @vr-varad , thanks for offering help with this one. To be honest this is a time sensitive issue that we added directly to the current sprint and a developer is already picking it up. But if you are interested in contributing I can definitely point you out to some issues.

best regards

**Comment by vr-varad** [comment]
Ya sure @txau I am ready.

**Comment by txau** [comment]
@vr-varad here are some issues that are less time sensitive and sort of low hanging fruit:

- https://github.com/huridocs/uwazi/issues/7109
- https://github.com/huridocs/uwazi/issues/7073
- https://github.com/huridocs/uwazi/issues/6963
- https://github.com/huridocs/uwazi/issues/6872

**Comment by aphilop** [comment]
@gabriel-piles I assume this is fixed with https://github.com/huridocs/uwazi/pull/7246 and can be closed, correct?

**Comment by gabriel-piles** [comment]
@aphilop yes, it is working well in staging, we can close it
