### ISSUE TITLE
Menu settings: problems adding an item into a group

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#7235]
**Describe the bug**
At the Menu settings, it is not possible to ad a link into a group, as the UI does not allow to save this change.

**To Reproduce**
1. Go to Settings; go to Menu: /settings/navlinks 
2. If the Menu has no groups, add a new one with a few links.
3. Click on Add link to create a new item in the menu.
4. Enter details of the new link, including a group selection.
5. Try to click on 'Save' button and see error: the button is not active.

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/d760f704-9d0a-47e9-8a4c-c775fc87c9e8)
![image](https://github.com/user-attachments/assets/4fb1695b-a0ae-48e9-9df0-f98f264f91bd)
![image](https://github.com/user-attachments/assets/e2cb0164-d0d0-4c9c-91d4-ed4e7c2d2c7b)

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Browser**
Brave

**Additional context**
There is no problem if you add a new link with no group.
As a work around, you can do that and after editing the item and selecting the group.

**Comment by RafaPolit** [comment]
I have confirmed this is happening.  If you add a link to the ROOT element, it enables the save, but adding only a child item does not.

**Comment by aphilop** [comment]
@salvalacruz @RafaPolit 

I am following the steps to reproduce and (unless I am doing something completely strange and different) I can not reproduce this consistenly. It happened to me once but tried to reproduce it with no success. I can create  a group, save it and access it afterwards.

<img width="1483" alt="image" src="https://github.com/user-attachments/assets/d1a5521b-35ae-4b49-a54e-0ad5360e26e0">


<img width="1710" alt="image" src="https://github.com/user-attachments/assets/05374cca-e6d6-447b-96e8-5771afce5385">

**Comment by Zasa-san** [comment]
I've already detected the problem and the steps to reproduce it consistently. I'm working right now on a hotfix to address this. 

The problem is when you ONLY add a child element and do nothing else. The save button doesn't become enabled in that case and the users cannot save until they do another action.
