### ISSUE TITLE
[IX] - Adding a labeled sample should update the stats

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7270]
At the moment, for a "title" property, when labeling data the stats are not updated. This is misleading for users that after labeling 20 samples still see "zero" labeled samples in the stats. Refreshing the section updates the stats, but it should happen in real time.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
