### ISSUE TITLE
"Confirm delete" message overlaped by map icons

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#7354]
**Describe the bug**
When deleting an entity, if the confirmation message appears in the same place that the map icons, images are overlaped.

**To Reproduce**
1. Go to en entity view, when the entity has a geolocation propperty.
2. Click on 'Delete', with the map of the propperty on the top of the screen.
3. See error: message and map icons are overlaped.

**Expected behavior**
Layer and Zoom icons from the map should be hidden, behid the message.

**Screenshots**
![image](https://github.com/user-attachments/assets/b8d6865d-bf9d-4eaa-a957-687dbf76480a)

![image](https://github.com/user-attachments/assets/0f5ab909-c4d6-48a0-8bda-0d5c06fae5d0)

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Browser**
Brave

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
