### ISSUE TITLE
[AT] The text to be translated (or the return) can be too long for the redis queue

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#7383]
**Describe the bug**
Redis queues apparently have a limit in size of what a message can carry.  It can happen that the text to be translated is surpassing this limit and creating problems.

- First we need to know what is the size of the limit (first review points to half a gigabyte, which would not be an issue
- We may need to upgrade the service / Uwazi integration to use the upload materials process and use the queue for just coordination and not actual data
- We may take other approaches like splitting the text, limiting the translation to first parts or simply rejecting the text (as an MVP) in this cases.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by daneryl** [comment]
#7537 Fixes this, if we see it happening again lets revisit the issue.
