### ISSUE TITLE
[IX] Send option values with request instead of in Redis message

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#7398]
The metadata extractor, which includes multi-selects, sends the possible values in a Redis message. This approach works well. However, the introduction of a relationship property type as an extraction results in too many values to be stored in a Redis message. As a consequence, RSMQ throws an exception due to exceeding the message size limit.

To address this issue, the metadata extraction service now supports retrieving possible values via an HTTP POST request.

Endpoint: 
/options

Payload: 
{"tenant": "tenant", 
"extraction_id":"extraction_id", 
"options": [{"id": "id", "label": "label"}, ....]}

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by daneryl** [comment]
After some work and help from others that worked on IX, we were not able to replicate this problem. I am sure it does exists but the feature itself is hard to use, difficult to understand or buggy. 
Without proper ways of replicating issues Im not able to continue with this.

**Comment by txau** [comment]
@daneryl we don't need to replicate the issue, just change how it works. Right now when the options of a relationship field are sent for training, they are sent with a Redis message. If these options are very long (many options, long labels), the message can be bigger than the max redis message length allowed.

We have another method of sending data, check "send materials" in document segmentation. Redis is used for coordination but the xmls for segmentation are sent in an http request directly to the service. That is what we want to replicate.

**Comment by daneryl** [comment]
I need to be able to asses if what i am doing works, that is why i think i need to replicate the issue, or at least i need to be able to replicate the way this issue is presented, like sending options of a relationship field, which i could not.

**Comment by daneryl** [comment]
@txau @gabriel-piles After being able to replicate the issue i checked what was the actual size of the "messageTooLong" error and was around 75k, this is big but not crazy, and redis accepts messages [up to 512Mb](https://stackoverflow.com/questions/5606106/what-is-the-maximum-value-size-you-can-store-in-redis), next thing, i took a look at the rsmq library we use and they have a [default limit for each queue created](https://github.com/smrchy/rsmq?tab=readme-ov-file#queue) of about 65k.

> maxsize (Number): optional (Default: 65536) The maximum message size in bytes. Allowed values: 1024-65536 and -1 (for unlimited size)

This is set on queue creation, uwazi and each of the services create these queues, i have changed the [uwazi queue creation](https://github.com/huridocs/uwazi/pull/7537) #gabriel you need to change this configuration in each service.

the current queues on prod/staging are set already to -1, but the change in the code that creates them is necessary in case they are recreated.

This also fixes the same proble on AT https://github.com/huridocs/uwazi/issues/7383

This is ready for testing.

**Comment by txau** [comment]
What about "the change in the code that creates them"? Is that code fixed before we close this ?

**Comment by daneryl** [comment]
> What about "the change in the code that creates them"? Is that code fixed before we close this ?

it is #7537 on the uwazi side, @gabriel-piles needs to change service side.

**Comment by gabriel-piles** [comment]
@joan @txau I will change this on the services side
