### ISSUE TITLE
Updates on the 2001 Huridocs microthesauri (English and translations)

### ISSUE THREAD

**Issue by mayeulk** [huridocs/uwazidocs#7431]
Hi! I found two numeric sources (ready to import in Uwazi or other databasee) of the 2001 Huridocs microthesauri.

1) The GoogleSheets listed at:
https://huridocs.org/resource-library/monitoring-and-documenting-human-rights-violations/microthesauri/

(this is used by https://github.com/huridocs/uwazi/pull/2423)

2) https://github.com/huridocs/OpenEvSys/blob/master/schema/mysql-dbpopulate-mt.sql

(in addition to the pdf files micro-thesauri in various languages, such as:
https://huridocs.org/wp-content/uploads/2020/12/mictheenfinalpdf.pdf  - not easy to import in a DB).

Are there more recent versions of these microthesauri? (For English and/or translations). I think there are issues with these, some of the issues being:

-  Inconsistencies in translations:
For instance:
"Lack of law which guarantees personal integrity" is translated as "Falta de legislación **o de políticas** que garanticen el derecho a la seguridad e integridad personal"
(with " o de políticas ", the interpretation is slightly different)

Or:  10101050000	Murder (deliberate killing which ought to be seen as a common criminal act)	
 in French "Meurtre (assassinat délibéré devant être regardé comme un acte criminel **normal**)"
 "normal" is strange here (in French, it can mean "an acceptable behouviour") and could be incorrect; possibly, it should rather be "crime de droit commun" ? (see e.g.:
https://www.linguee.com/english-french/search?source=auto&query=common+crime)  e.g. "common" = not specialized law (such as the specialized law for e.g. terrorist crimes)

In a single Russian cell, there are two languages and a note saying " (translation missing)" (actually, the translation is not missing):
"Опубликование закона или политики, снижающих гарантии свободы веру/мнения Promulgation of law or policy which reduces guarantees for freedom of belief/opinion (translation missing)" (sic)

- Lack of full, long definition for each concept
I failed to find the following reference online (Google, archive.org). Maybe it has definitions or discussion of terms ? How to get it?
Dueck, Judith, and Aída María Noval. "Supporting Document J: Type of Event." HURIDOCS
Standard Formats: Supporting Documents. Oslo: HURIDOCS, 1993. 97-112

I saw some details on how to understand some terms in mictheenfinalpdf.pdf but it is not alwasy sufficient, and it is not organised in a way that helps put it in Uwazi or other database. 

If there are not (yet) more recent versions, is there a place/process for people to contribute? (given the OpenEvSys github repo is now read only)

Thank you.
Mayeul Kauffmann

**Comment by mayeulk** [comment]
Related question: 
Are those identical? (except for the number of translations)
The GoogleSheets listed at:
    https://huridocs.org/resource-library/monitoring-and-documenting-human-rights-violations/microthesauri/
The code at:
    https://github.com/huridocs/OpenEvSys/blob/master/schema/mysql-dbpopulate-mt.sql

**Comment by mayeulk** [comment]
Another issue, seen in GoogleSheet "27-Types of Responses" https://docs.google.com/spreadsheets/d/1cETLZGG9gmdkvCfHlGQVzKBX8pFheLs8-MlzmHm5IQk/edit?gid=0#gid=0
It wrongly states "This is a short list with one level", while https://huridocs.org/wp-content/uploads/2020/12/mictheenfinalpdf.pdf correctly states "This is a hierarchical list with three levels". (The rest of the description on row 1 of the GoogleSheets seems identical to the pdf).
From what I can see, some manual conversion and editing has been used to convert the PDF into the various GoogleSheets. Eg in sheet "18-Degrees of Involvement": "THis is a hierarchical list", with a upper-case H in "THis", which indicates re-typing the word (the case in the PDF is correct: "This").
"25-Status as Victim" https://docs.google.com/spreadsheets/d/1QbJGS27Sme3DjLXvfEW0bQsBAkRCr7l7hsDioSXjhYU/edit?gid=0#gid=0  "abou the latest or present status" ("abou" without 't') (mictheenfinalpdf.pdf reads: "about")

Retyping text is inherently prone to errors (as compared to semi-automated conversion with strict quality control steps).

Sometimes, row 1 of a GoogleSheets has the full text of the PDF (description of type), sometimes only a small part of it (e.g. "4-Types of Acts" has one third of the PDF description).

**Comment by mayeulk** [comment]
In sheet "10-Occupations (ILO Categories)" https://docs.google.com/spreadsheets/d/1VgdQeQ_RtZkYvy71-9IOsnWZk74tk7RFR0CdBFErhaI/edit?gid=0#gid=0
many Spanish translations are in the wrong row:
cell D206 "Trabajadores voluntarios en cooperativas" seems to be an alternate translation for:
cell B227 "Volunteer worker in co-operative"
Then, all Spanish translations between D206 and D227 are off by one row (e.g. B213=Other , D214=Otros)

**Comment by mayeulk** [comment]
Sheet "24-Types of Perpetrators" https://docs.google.com/spreadsheets/d/1l3gxmX-T2bpFs0fV1ZjVTvZzHMyLgzsiu9ZGsmsGsu0/edit?gid=0#gid=0
English "Spouses" is incorrectly translated into French as "Epouses" (which means: "wives", that is "female spouses"; a spouse can be wife or husband).
Same in 3-Rights Typology:
Equality of spouses (Right to)	 /  Egalité des épouses (droit à l')

Wrong language in a translation field is frequent in several sheets. For instance in sheet 6, codes 080200000000, 160200000000 and 170700000000; sheet 14 code 980000000000 : the "Spanish" field is in French.

sheet 14 code 980000000000 : the "Indonesian" field is in Arabic.

**Comment by mayeulk** [comment]
Importing microthesauri could be made easier, by improving the page https://huridocs.org/resource-library/monitoring-and-documenting-human-rights-violations/microthesauri/
"Types of Perpetrators" is made of three links, attached to these strings:

- T
- y
- pes of Perpetrators

HTML source code:
`<a href="[https://docs.google.com/spreadsheets/d/1l3gxmX-T2bpFs0fV1ZjVTvZzHMyLgzsiu9ZGsmsGsu0/edit?usp=sharing](view-source:https://docs.google.com/spreadsheets/d/1l3gxmX-T2bpFs0fV1ZjVTvZzHMyLgzsiu9ZGsmsGsu0/edit?usp=sharing)">T</a><a href="[https://docs.google.com/spreadsheets/d/1l3gxmX-T2bpFs0fV1ZjVTvZzHMyLgzsiu9ZGsmsGsu0/edit?usp=sharing](view-source:https://docs.google.com/spreadsheets/d/1l3gxmX-T2bpFs0fV1ZjVTvZzHMyLgzsiu9ZGsmsGsu0/edit?usp=sharing)" target="_blank" rel="noreferrer noopener">y</a><a href="[https://docs.google.com/spreadsheets/d/1l3gxmX-T2bpFs0fV1ZjVTvZzHMyLgzsiu9ZGsmsGsu0/edit?usp=sharing](view-source:https://docs.google.com/spreadsheets/d/1l3gxmX-T2bpFs0fV1ZjVTvZzHMyLgzsiu9ZGsmsGsu0/edit?usp=sharing)">pes of Perpetrators</a>`

**Comment by mayeulk** [comment]
In the GoogleSheets, in most cases the first column is labelled "huri_code" (singular), except:
Microthesaurus 2 (2-Violations Typology). Header of first column is: huri_codes 
Microthesaurus 10 (10-Occupations (ILO Categories)). Header of first column is: huri_codes 
Microthesaurus 15 (15-Geographical Terms). Header of first column is: "huri_codes (add 0 in the beginning)"

**Comment by mayeulk** [comment]
In most microthesauri, huri_code for "other" is:
"900000000000"

For GoogleSheet 3-Rights Typology, huri_code for "other" is:
"090000000000" (with a leading zero, and 10 zeroes on the right, not 11).

while the PDF says  (page 4): "Finally, HURIDOCS has assigned the code 90 and the term "Other"..."

In GoogleSheet "19-Source Connection to Information", "Other" is missing while it could be helpful. (Note:  "Other" is missing also in 7, 26, 41, 44, 45, 48 but these seems fine to me as in theory there can't be 'other' in these cases).

**Comment by aphilop** [comment]
Hello @mayeulk 

Thank you for your valuable feedback, and apologies for the delayed response.

The microthesauri haven’t been updated since 2001, and no active edits are currently planned. However, we encourage end users to update and adapt them as needed for their projects.

Currently, there isn’t a way for the community to contribute directly to the microthesauri, but this is something we may explore in the future.

Is there anything else we can assist you with, particularly regarding Uwazi? For instance, have you tried using the microthesauri to import them into a Uwazi database? If so, how did it go? Were there any challenges you’d like to share?

Thank you again for your thoughtful suggestions!

**Comment by mayeulk** [comment]
No worries with respect to the delay. Thank you very much for the answer, and for the offer to help !
Given that the Huridocs website states OpenEvSys is no longer maintained and was somehow replaced by Uwazi, I expected to have an easy way to get in Uwazi some functionalities similar to those of OpenEvSys, including (ideally) a way to easily have the same set of categories as the microthesauri (ideally all the 48 ones, plus mine), linked between each other. With support to formats similar to the various formats used in OpenEvsys : Event, Person, Act, Involvemement, Information, Intervention, Chaine of event, Biographic, Additional details.

Unless I’m mistaken, it is not possible to have « out of the box » (say : minutes after install) a configured Uwazi database that works like OpenEvSys did.
I could not find a descriptions of the step required to do so.  Doing this search on Google: « Uwazi import microthesaurus ».
From what I could get from the Uwazi documentation, the process of building a tool similar to OpenEvsys, under Uwazi, is largely a manual process. Looking at :
https://uwazi.readthedocs.io/en/latest/admin-docs/building-info-architecture.html#how-to-import-thesauri-from-a-csv-file

What could meet my needs would be a set of scripts (that I could modify) that would import thesauri and configure the links between entities in order to have an experience similar to that of OpenEvSys to record HR violations.
Maybe it does exist, but I failed to find it. I needed such a tool for my students, first Semester (Fall/Winter 2024). I’ve built an app (based on Drupal) that meets some of these needs (not all, yet), using an RDBMS backend (PostgreSQL). To do this, I realised the first step was to tidy up the microthesauri and their translations; hence this issue. Maybe setting up a weblate project for the translations could be usefull. I’d be happy to help. I'd prefer to use Uwazi and contribute to tools used by the community than developing my own tools.

**Comment by aphilop** [comment]
> Unless I’m mistaken, it is not possible to have « out of the box » (say : minutes after install) a configured Uwazi database that works like Uwazi did.

Assuming that you mean "...that works like OpenEvsys", yes. You need to configure in Uwazi the different templates, thesauri, relationships that correspond to your data model/structure as described in the [documentation](https://uwazi.readthedocs.io/en/latest/admin-docs/building-info-architecture.html).

> What could meet my needs would be a set of scripts (that I could modify) that would import thesauri and configure the links between entities in order to have an experience similar to that of OpenEvSys to record HR violations.

I am sorry, but we currently don't have such scripts available.

**Comment by aphilop** [comment]
@mayeulk 
I am closing this issue as further possible steps regarding the microthesauri were discussed per email.
Feel free to open new issues if you have any feedback/questions for the Uwazi tool.
Again many thanks for your contributions!
