### ISSUE TITLE
User login error with correct information

### ISSUE THREAD

**Issue by evanbf** [huridocs/uwazidocs#7442]
There's 1 of our users who's having trouble logging on to his computer, despite his credentials being correct. When she tries to connect to another person's computer, the connection succeeds. But not on her own PC. We've installed a new browser for her, deleted the cookies and erased the browsing data, but the problem persists. What can cause this?

**Comment by txau** [comment]
Most likely something is failing with the credentials. When using her own computer, are you copy-pasting the credentials from somewhere (password vaults etc)? if there is an extra space at the wrong place or some other hidden char that could be the reason. Also pay attention to caps in the username.

**Comment by evanbf** [comment]
The credentials are entered manually on the user's own computer. Username and password also

**Comment by txau** [comment]
@evanbf this is an strange case, indeed. Could you help providing a little more information? Is the feedback just "Invalid login" or some other error? If she tries to use the password recovery path is she receiving an email? Have you tried resetting the password?

**Comment by evanbf** [comment]
Error message displays: “connection failed”. When she tries to use the password recovery method, she doesn't receive any e-mail. I login with the administrator account and reset her password for her. Image attached : 
![2024-11-13 à 08 54 02_17d4dcd7](https://github.com/user-attachments/assets/4913533d-518e-45df-804a-1f6e40026d03)

**Comment by txau** [comment]
“connection failed” could it be that she has some firewall? If so try deactivating it. that would explain why it doesn't work despite deleting cookies and cache and using another browser since the firewall acts on a lower level.

**Comment by evanbf** [comment]
OK, we'll check the firewalls and get back to you.

**Comment by aphilop** [comment]
@evanbf 
Are you still facing this problem or can we close this issue? Thanks.

**Comment by aphilop** [comment]
Since there hasn't been any further feedback on this, I am closing this issue.
@evanbf Feel free to reopen if you have any new updates and need further support on this. Thanks!
