### ISSUE TITLE
Provide proper feedback on file not found on media fields

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7460]
Currently we show this message:

![image](https://github.com/user-attachments/assets/66d1c6cc-2afc-4546-9a3a-1e8fd9a503be)

When actually it is a file not found. In fact in the card view it is rendered as such:

![image](https://github.com/user-attachments/assets/a964c012-f7e1-4fa6-a95f-3e8930508cd5)

But in the side panel and entity view it gives this other feedback message, misleading for the users in terms of understanding why they are not seeing their image.

**Expected behavior**
When the file is not found the error message should reflect this.

**Comment by konzz** [comment]
This is how it will look in the cards, side panel and editor.
![Image](https://github.com/user-attachments/assets/d9ed74a1-1dd9-4c40-883a-7984afae0b96)
