### ISSUE TITLE
Fail to index Documents on Elastic search

### ISSUE THREAD

**Issue by Joao-vi** [huridocs/uwazidocs#7524]
**Describe the bug**
Some Fields on metadata object can have size that exceeds that max length supported for metadata elastic mapping.

It's seems that the metadata is dynamically mapped as an object on the file "elastic_mapping.js". So Elastic search is likely inferring the subfields and creating the mappings automatically.
This auto-mapping may not handle large text values, leading to this issue.

**Error message**
```
{
  "reason": "Document contains at least one immense term in field=\"metadata.детальний_опис_події.value.sort\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[97, 114, 70, 3, 4, 97, -100, -114, 74, 98, 84, -84, 42, 114, -118, -100, -24, 3, 4, 97, -106, -118, -100, 74, 78, -100, -24, 84, -118, -16]...', original message: bytes can be at most 32766 in length; got 36503",
  "caused_by": {
    "type": "max_bytes_length_exceeded_exception",
    "reason": "max_bytes_length_exceeded_exception: bytes can be at most 32766 in length; got 36503"
  }
}

```

**Comment by aphilop** [comment]
@RafaPolit to clarify this with the backend team.

**Comment by Joao-vi** [comment]
Note: This has nothing to do with pdf Document/Files but with the elastic search document.

We need to gather more information about this looking at the logs.

This issue is going now be conducted on internal issue repository 234
