### ISSUE TITLE
[IX] Understand data flow when editing

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#7547]
When I create a text selection in a IX extractor -> document, for, for example, the title property, the value of the text label and the title of the entity are the same.  If I then go and edit the title in the entity (not the extractor) and return to the extractor, the value shown has changed, it reads the new title.  But, the text in the file and it's rectangles is still the previous one.  If I click to train, the model is receiving the original text while the UI apparently shows that you were sending the new title.

Is this expected?

cc @txau

**Comment by aphilop** [comment]
This seems to be clear now and decisions about refactoring will he handled with #6979
