### ISSUE TITLE
Selecting texts on the pdf using chrome sometimes selects other texts

### ISSUE THREAD

**Issue by josh-huridocs** [huridocs/uwazidocs#7556]
Chrome Version 131.0.6778.140 (Official Build) (arm64)
MacOS 15.0.1 (24A348)
Apple M1

Selecting texts on the pdf using chrome sometimes selects other texts

[scrnli_KVy4MLPpSX14FM.webm](https://github.com/user-attachments/assets/ff7bf0df-2436-403d-923b-885782f6d857)

**Comment by txau** [comment]
@josh-huridocs thanks for reporting, this is actually not a bug but unfortunately a downside of the PDF format. Pretty much all PDF visors behave like that depending on the underlying text layer. It can be improved by re-processing the PDFs with better and newer versions, but nothing we can fix on our end.
